-- Create table to hold the basic structre of a professional claim
DROP TABLE IF EXISTS emdeon_professional_claims_base;
CREATE TABLE emdeon_professional_claims_base(
claim_id string,
accident_related string,
adjudicated_proc_modifier_1 string,
adjudicated_proc_modifier_2 string,
adjudicated_proc_modifier_3 string,
adjudicated_proc_modifier_4 string,
adjudicated_procedure string,
adjudicated_procedure_qual string,
admission_hour string,
amb_hosp_to_hosp string,
amb_nurse_to_diag string,
amb_nurse_to_hosp string,
ambulance_to_hosp string,
assignment_sign string,
bene_not_entitled string,
claim_filing_ind_cd string,
claim_type string,
cob_group_name_1 string,
cob_group_name_2 string,
cob_group_policy_nbr_1 string,
cob_group_policy_nbr_2 string,
cob_ins_type_code_1 string,
cob_ins_type_code_2 string,
cob_payer_claim_filing_ind_code_1 string,
cob_payer_claim_filing_ind_code_2 string,
cob_payer_hpid_1 string,
cob_payer_hpid_2 string,
cob_payer_id_1 string,
cob_payer_id_2 string,
cob_payer_name_1 string,
cob_payer_name_2 string,
cob_payer_seq_code_1 string,
cob_payer_seq_code_2 string,
cob_relationship_cd_1 string,
cob_relationship_cd_2 string,
contract_allow_ind string,
copay string,
date_paid string,
date_received string,
date_service string,
date_service_end string,
diagnosis_code_qual string,
diag_concat string,
svcptr_concat string,
related string,
dialysis_related string,
discharge_hour string,
electronic_claim string,
emergency string,
esrd_patient string,
explanation_code string,
group_name string,
hosp_admis_or_er string,
in_out_network string,
initial_procedure string,
inst_admit_source_std_id string,
inst_admit_type_std_id string,
inst_date_admitted string,
inst_discharge_status_std_id string,
inst_drg_std_id string,
inst_type_of_bill_std_id string,
line_allowed string,
line_charge string,
medical_coverage_type string,
member_adr_city string,
member_adr_line1 string,
member_adr_line2 string,
member_adr_state string,
member_adr_zip string,
member_dob string,
member_fname string,
member_gender string,
member_id string,
member_lname string,
ndc_code string,
new_patient string,
not_covrd_specialt string,
operating_pr_commercial string,
operating_pr_first_name string,
operating_pr_last_name string,
operating_pr_location string,
operating_pr_middle_name string,
operating_pr_npi string,
operating_pr_org_name string,
operating_pr_state_lic string,
operating_pr_upin string,
oral_cavity string,
oth_operating_pr_commercial string,
oth_operating_pr_first_name string,
oth_operating_pr_last_name string,
oth_operating_pr_location string,
oth_operating_pr_middle_name string,
oth_operating_pr_npi string,
oth_operating_pr_org_name string,
oth_operating_pr_state_lic string,
oth_operating_pr_upin string,
paid_amount string,
patient_age string,
patient_control string,
patient_dob string,
patient_fname string,
patient_gender string,
patient_id string,
patient_lname string,
patient_reach_max string,
patient_relation string,
pay_to_plan_address_1 string,
pay_to_plan_address_2 string,
pay_to_plan_city string,
pay_to_plan_clm_ofc_number string,
pay_to_plan_naic_id string,
pay_to_plan_name string,
pay_to_plan_payer_id string,
pay_to_plan_plan_id string,
pay_to_plan_state string,
pay_to_plan_tax_id string,
pay_to_plan_zip string,
pay_to_prov_address_1 string,
pay_to_prov_address_2 string,
pay_to_prov_city string,
pay_to_prov_state string,
pay_to_prov_zip string,
payer_name string,
payer_vendor_id string,
place_of_service_std_id string,
procedure_code string,
procedure_code_qual string,
procedure_modifier_1 string,
procedure_modifier_2 string,
procedure_modifier_3 string,
procedure_modifier_4 string,
procedure_units string,
prov_billing_address_1 string,
prov_billing_address_2 string,
prov_billing_city string,
prov_billing_name_1 string,
prov_billing_name_2 string,
prov_billing_npi string,
prov_billing_ssn string,
prov_billing_state string,
prov_billing_state_license string,
prov_billing_std_taxonomy string,
prov_billing_tax_id string,
prov_billing_upin string,
prov_billing_zip string,
prov_facility_address_1 string,
prov_facility_address_2 string,
prov_facility_city string,
prov_facility_name_1 string,
prov_facility_name_2 string,
prov_facility_npi string,
prov_facility_state string,
prov_facility_state_license string,
prov_facility_tax_id string,
prov_facility_zip string,
prov_referring_commercial_id string,
prov_referring_name_1 string,
prov_referring_name_2 string,
prov_referring_npi string,
prov_referring_state_license string,
prov_referring_tax_id string,
prov_referring_upin string,
prov_rendering_name_1 string,
prov_rendering_name_2 string,
prov_rendering_npi string,
prov_rendering_state_license string,
prov_rendering_std_taxonomy string,
prov_rendering_tax_id string,
prov_rendering_upin string,
prov_specialty string,
release_sign string,
revenue_code string,
service_line_number string,
statement_from string,
statement_to string,
sub_client_id string,
supervising_pr_commercial string,
supervising_pr_first_name string,
supervising_pr_last_name string,
supervising_pr_location string,
supervising_pr_middle_name string,
supervising_pr_npi string,
supervising_pr_org_name string,
supervising_pr_state_lic string,
supervising_pr_upin string,
svc_during_postop string,
tooth_number string,
tooth_surface string,
total_allowed string,
total_charge string,
type_service string
);

DROP TABLE IF EXISTS related_diags_tmp;
CREATE TABLE related_diags_tmp (claim_id string, related string);

DROP TABLE IF EXISTS related_diags;
CREATE TABLE related_diags (claim_id string, related varchar(5000));

DROP TABLE IF EXISTS emdeon_professional_claims_unrelated;
CREATE TABLE emdeon_professional_claims_unrelated (
accident_related string,
admission_hour string,
amb_hosp_to_hosp string,
amb_nurse_to_diag string,
amb_nurse_to_hosp string,
assignment_sign string,
claim_id string,
claim_type string,
contract_allow_ind string,
date_received string,
diagnosis_code_qual string,
dialysis_related string,
discharge_hour string,
electronic_claim string,
esrd_patient string,
explanation_code string,
group_name string,
hosp_admis_or_er string,
in_out_network string,
initial_procedure string,
inst_admit_source_std_id string,
inst_admit_type_std_id string,
inst_date_admitted string,
inst_discharge_status_std_id string,
inst_drg_std_id string,
inst_type_of_bill_std_id string,
medical_coverage_type string,
member_adr_city string,
member_adr_line1 string,
member_adr_line2 string,
member_adr_state string,
member_adr_zip string,
member_dob string,
member_fname string,
member_gender string,
member_id string,
member_lname string,
new_patient string,
not_covrd_specialt string,
patient_age string,
patient_control string,
patient_dob string,
patient_fname string,
patient_gender string,
patient_id string,
patient_lname string,
patient_relation string,
payer_name string,
payer_vendor_id string,
prov_billing_address_1 string,
prov_billing_address_2 string,
prov_billing_city string,
prov_billing_name_1 string,
prov_billing_name_2 string,
prov_billing_npi string,
prov_billing_ssn string,
prov_billing_state string,
prov_billing_state_license string,
prov_billing_std_taxonomy string,
prov_billing_tax_id string,
prov_billing_upin string,
prov_billing_zip string,
prov_facility_address_1 string,
prov_facility_address_2 string,
prov_facility_city string,
prov_facility_name_1 string,
prov_facility_name_2 string,
prov_facility_npi string,
prov_facility_state string,
prov_facility_state_license string,
prov_facility_tax_id string,
prov_facility_zip string,
prov_referring_name_1 string,
prov_referring_name_2 string,
prov_referring_npi string,
prov_referring_tax_id string,
prov_rendering_name_1 string,
prov_rendering_name_2 string,
prov_rendering_npi string,
prov_rendering_state_license string,
prov_rendering_std_taxonomy string,
prov_rendering_tax_id string,
prov_rendering_upin string,
prov_specialty string,
release_sign string,
statement_from string,
statement_to string,
sub_client_id string,
tooth_number string,
total_allowed string,
total_charge string,
date_service string,
date_service_end string,
unrelated string
);

DROP TABLE IF EXISTS emdeon_professional_claims_base;
CREATE TEMPORARY VIEW emdeon_professional_claims_base AS
SELECT emdeon_dx_raw_claims.claim_id AS claim_id,
accident_related,
adjudicated_proc_modifier_1,
adjudicated_proc_modifier_2,
adjudicated_proc_modifier_3,
adjudicated_proc_modifier_4,
adjudicated_procedure,
adjudicated_procedure_qual,
admission_hour,
amb_hosp_to_hosp,
amb_nurse_to_diag,
amb_nurse_to_hosp,
ambulance_to_hosp,
assignment_sign,
bene_not_entitled,
claim_filing_ind_cd,
claim_type,
cob_group_name_1,
cob_group_name_2,
cob_group_policy_nbr_1,
cob_group_policy_nbr_2,
cob_ins_type_code_1,
cob_ins_type_code_2,
cob_payer_claim_filing_ind_code_1,
cob_payer_claim_filing_ind_code_2,
cob_payer_hpid_1,
cob_payer_hpid_2,
cob_payer_id_1,
cob_payer_id_2,
cob_payer_name_1,
cob_payer_name_2,
cob_payer_seq_code_1,
cob_payer_seq_code_2,
cob_relationship_cd_1,
cob_relationship_cd_2,
contract_allow_ind,
copay,
date_paid,
date_received,
date_service,
date_service_end,
diagnosis_code_qual,
concat_ws(':',
primary_diagnosis,
diagnosis_code_2,
diagnosis_code_3,
diagnosis_code_4,
diagnosis_code_5,
diagnosis_code_6,
diagnosis_code_7,
diagnosis_code_8,
diagnosis_code_9,
diagnosis_code_10,
diagnosis_code_11,
diagnosis_code_12,
diagnosis_code_13,
diagnosis_code_14,
diagnosis_code_15,
diagnosis_code_16,
diagnosis_code_17,
diagnosis_code_18,
diagnosis_code_19,
diagnosis_code_20,
diagnosis_code_21,
diagnosis_code_22,
diagnosis_code_23,
diagnosis_code_24,
diagnosis_code_25,
admit_diagnosis
) diag_concat,
concat_ws(':',
diagnosis_pointer_1,
diagnosis_pointer_2,
diagnosis_pointer_3,
diagnosis_pointer_4,
diagnosis_pointer_5,
diagnosis_pointer_6,
diagnosis_pointer_7,
diagnosis_pointer_8
) svcptr_concat,
get_diagnosis_with_priority(
concat_ws(':',
primary_diagnosis,
diagnosis_code_2,
diagnosis_code_3,
diagnosis_code_4,
diagnosis_code_5,
diagnosis_code_6,
diagnosis_code_7,
diagnosis_code_8,
diagnosis_code_9,
diagnosis_code_10,
diagnosis_code_11,
diagnosis_code_12,
diagnosis_code_13,
diagnosis_code_14,
diagnosis_code_15,
diagnosis_code_16,
diagnosis_code_17,
diagnosis_code_18,
diagnosis_code_19,
diagnosis_code_20,
diagnosis_code_21,
diagnosis_code_22,
diagnosis_code_23,
diagnosis_code_24,
diagnosis_code_25,
admit_diagnosis
),
concat_ws(':',
diagnosis_pointer_1,
diagnosis_pointer_2,
diagnosis_pointer_3,
diagnosis_pointer_4,
diagnosis_pointer_5,
diagnosis_pointer_6,
diagnosis_pointer_7,
diagnosis_pointer_8
)) as related,
dialysis_related,
discharge_hour,
electronic_claim,
emergency,
esrd_patient,
explanation_code,
group_name,
hosp_admis_or_er,
in_out_network,
initial_procedure,
inst_admit_source_std_id,
inst_admit_type_std_id,
inst_date_admitted,
inst_discharge_status_std_id,
inst_drg_std_id,
inst_type_of_bill_std_id,
line_allowed,
line_charge,
medical_coverage_type,
member_adr_city,
member_adr_line1,
member_adr_line2,
member_adr_state,
member_adr_zip,
member_dob,
member_fname,
member_gender,
member_id,
member_lname,
ndc_code,
new_patient,
not_covrd_specialt,
operating_pr_commercial,
operating_pr_first_name,
operating_pr_last_name,
operating_pr_location,
operating_pr_middle_name,
operating_pr_npi,
operating_pr_org_name,
operating_pr_state_lic,
operating_pr_upin,
oral_cavity,
oth_operating_pr_commercial,
oth_operating_pr_first_name,
oth_operating_pr_last_name,
oth_operating_pr_location,
oth_operating_pr_middle_name,
oth_operating_pr_npi,
oth_operating_pr_org_name,
oth_operating_pr_state_lic,
oth_operating_pr_upin,
paid_amount,
patient_age,
patient_control,
patient_dob,
patient_fname,
patient_gender,
patient_id,
patient_lname,
patient_reach_max,
patient_relation,
pay_to_plan_address_1,
pay_to_plan_address_2,
pay_to_plan_city,
pay_to_plan_clm_ofc_number,
pay_to_plan_naic_id,
pay_to_plan_name,
pay_to_plan_payer_id,
pay_to_plan_plan_id,
pay_to_plan_state,
pay_to_plan_tax_id,
pay_to_plan_zip,
pay_to_prov_address_1,
pay_to_prov_address_2,
pay_to_prov_city,
pay_to_prov_state,
pay_to_prov_zip,
payer_name,
payer_vendor_id,
CASE WHEN place_of_service_std_id IS NOT NULL AND LENGTH(TRIM(place_of_service_std_id)) != 0 THEN place_of_service_std_id ELSE substring(inst_type_of_bill_std_id , 1, 2) END as place_of_service_std_id,
procedure_code,
procedure_code_qual,
procedure_modifier_1,
procedure_modifier_2,
procedure_modifier_3,
procedure_modifier_4,
procedure_units,
prov_billing_address_1,
prov_billing_address_2,
prov_billing_city,
prov_billing_name_1,
prov_billing_name_2,
prov_billing_npi,
prov_billing_ssn,
prov_billing_state,
prov_billing_state_license,
prov_billing_std_taxonomy,
prov_billing_tax_id,
prov_billing_upin,
prov_billing_zip,
prov_facility_address_1,
prov_facility_address_2,
prov_facility_city,
prov_facility_name_1,
prov_facility_name_2,
prov_facility_npi,
prov_facility_state,
prov_facility_state_license,
prov_facility_tax_id,
prov_facility_zip,
prov_referring_commercial_id,
prov_referring_name_1,
prov_referring_name_2,
prov_referring_npi,
prov_referring_state_license,
prov_referring_tax_id,
prov_referring_upin,
prov_rendering_name_1,
prov_rendering_name_2,
prov_rendering_npi,
prov_rendering_state_license,
prov_rendering_std_taxonomy,
prov_rendering_tax_id,
prov_rendering_upin,
prov_specialty,
release_sign,
revenue_code,
service_line_number,
statement_from,
statement_to,
sub_client_id,
supervising_pr_commercial,
supervising_pr_first_name,
supervising_pr_last_name,
supervising_pr_location,
supervising_pr_middle_name,
supervising_pr_npi,
supervising_pr_org_name,
supervising_pr_state_lic,
supervising_pr_upin,
svc_during_postop,
tooth_number,
tooth_surface,
total_allowed,
total_charge,
type_service
FROM emdeon_dx_raw_claims
    LEFT JOIN emdeon_dx_raw_diagnosis USING (claim_id)
    INNER JOIN emdeon_dx_raw_service USING (claim_id)
WHERE claim_type='P'
CLUSTER BY claim_id;
CACHE TABLE emdeon_professional_claims_base;

CREATE TEMPORARY VIEW emdeon_professional_claims_base2 AS
SELECT * FROM emdeon_professional_claims_base
WHERE ((datediff(date_service_end, date_service) IS NOT NULL
            AND datediff(date_service_end, date_service) > 0
            AND date_add(date_service, 366) > date_service_end)
        OR (datediff(statement_to, statement_from) IS NOT NULL
            AND datediff(statement_to, statement_from) > 0
            AND date_add(statement_from, 366) > statement_to));

CREATE TEMPORARY VIEW emdeon_professional_claims_base3 AS
SELECT * FROM emdeon_professional_claims_base
WHERE NOT ((datediff(date_service_end, date_service) IS NOT NULL
            AND datediff(date_service_end, date_service) > 0
            AND date_add(date_service, 366) > date_service_end)
        OR (datediff(statement_to, statement_from) IS NOT NULL
            AND datediff(statement_to, statement_from) > 0
            AND date_add(statement_from, 366) > statement_to));

INSERT INTO medicalclaims_common_model
SELECT
NULL,
b.claim_id,
hvid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
patient_gender,
patient_age,
patient_dob,
threedigitzip as patient_zip3,
state as patient_state,
claim_type,
date_received,
CASE WHEN date_service IS NOT NULL AND date_service_end IS NOT NULL THEN date_add(date_service, date_explode_indices.d) ELSE date_add(statement_from, date_explode_indices.d) END,
CASE WHEN date_service IS NOT NULL AND date_service_end IS NOT NULL THEN date_add(date_service, date_explode_indices.d) ELSE date_add(statement_from, date_explode_indices.d) END,
inst_date_admitted,
NULL,
inst_admit_type_std_id,
NULL,
NULL,
inst_admit_source_std_id,
NULL,
NULL,
inst_discharge_status_std_id,
NULL,
NULL,
inst_type_of_bill_std_id,
NULL,
NULL,
inst_drg_std_id,
NULL,
NULL,
place_of_service_std_id,
NULL,
NULL,
service_line_number,
split(split(related,':')[n-1],'_')[0] as diagnosis_code,
CASE WHEN diagnosis_code_qual = '9' THEN '01' WHEN diagnosis_code_qual = 'X' THEN '02' END,
split(split(related,':')[n-1],'_')[1] as diagnosis_priority,
NULL,
procedure_code,
procedure_code_qual,
NULL,
procedure_units,
procedure_modifier_1,
procedure_modifier_2,
procedure_modifier_3,
procedure_modifier_4,
revenue_code,
ndc_code,
medical_coverage_type,
line_charge,
line_allowed,
total_charge,
total_allowed,
prov_rendering_npi,
prov_billing_npi,
prov_referring_npi,
prov_facility_npi,
payer_mapping.payer_id,
payer_mapping.payer_name,
payer_mapping.payer_parent_name,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_rendering_tax_id,
NULL,
NULL,
NULL,
prov_rendering_upin,
NULL,
prov_rendering_name_1,
prov_rendering_name_2,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_rendering_std_taxonomy,
prov_specialty as prov_rendering_vendor_specialty,
NULL,
prov_billing_tax_id,
NULL,
prov_billing_ssn,
prov_billing_state_license,
prov_billing_upin,
NULL,
prov_billing_name_1,
prov_billing_name_2,
prov_billing_address_1,
prov_billing_address_2,
prov_billing_city,
prov_billing_state,
prov_billing_zip,
prov_billing_std_taxonomy,
NULL,
NULL,
prov_referring_tax_id,
NULL,
NULL,
prov_referring_state_license,
prov_referring_upin,
prov_referring_commercial_id,
prov_referring_name_1,
prov_referring_name_2,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_facility_tax_id,
NULL,
NULL,
prov_facility_state_license,
NULL,
NULL,
prov_facility_name_1,
prov_facility_name_2,
prov_facility_address_1,
prov_facility_address_2,
prov_facility_city,
prov_facility_state,
prov_facility_zip,
NULL,
NULL,
cob_payer_id_1 as cob_payer_vendor_id_1,
cob_payer_seq_code_1,
cob_payer_hpid_1,
cob_payer_claim_filing_ind_code_1,
cob_ins_type_code_1,
cob_payer_id_2 as cob_payer_vendor_id_2,
cob_payer_seq_code_2,
cob_payer_hpid_2,
cob_payer_claim_filing_ind_code_2,
cob_ins_type_code_2
FROM emdeon_professional_claims_base2 b
    CROSS JOIN split_indices
    CROSS JOIN date_explode_indices
    LEFT JOIN matching_payload ON b.claim_id = claimid
    LEFT JOIN zip3_to_state ON threeDigitZip = zip3
    LEFT JOIN payer_mapping ON payer_vendor_id = payer_id
WHERE split(related,':')[n-1] IS NOT NULL
    AND split(related,':')[n-1] <> ''
    AND (date_add(date_service, date_explode_indices.d) <= date_service_end
        OR (date_add(statement_from, date_explode_indices.d) <= statement_to));

INSERT INTO medicalclaims_common_model
SELECT
NULL,
b.claim_id,
hvid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
patient_gender,
patient_age,
patient_dob,
threedigitzip as patient_zip3,
state as patient_state,
claim_type,
date_received,
CASE WHEN date_service IS NOT NULL THEN date_service ELSE statement_from END,
CASE WHEN date_service_end IS NOT NULL THEN date_service_end ELSE statement_to END,
inst_date_admitted,
NULL,
inst_admit_type_std_id,
NULL,
NULL,
inst_admit_source_std_id,
NULL,
NULL,
inst_discharge_status_std_id,
NULL,
NULL,
inst_type_of_bill_std_id,
NULL,
NULL,
inst_drg_std_id,
NULL,
NULL,
place_of_service_std_id,
NULL,
NULL,
service_line_number,
upper(regexp_replace(regexp_replace(regexp_replace(split(split(related,':')[n-1],'_')[0], ' ', ''), ',', ''), '\\.', '')) as diagnosis_code,
CASE WHEN diagnosis_code_qual = '9' THEN '01' WHEN diagnosis_code_qual = 'X' THEN '02' END,
split(split(related,':')[n-1],'_')[1] as diagnosis_priority,
NULL,
procedure_code,
procedure_code_qual,
NULL,
procedure_units,
procedure_modifier_1,
procedure_modifier_2,
procedure_modifier_3,
procedure_modifier_4,
revenue_code,
ndc_code,
medical_coverage_type,
line_charge,
line_allowed,
total_charge,
total_allowed,
prov_rendering_npi,
prov_billing_npi,
prov_referring_npi,
prov_facility_npi,
payer_mapping.payer_id,
payer_mapping.payer_name,
payer_mapping.payer_parent_name,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_rendering_tax_id,
NULL,
NULL,
NULL,
prov_rendering_upin,
NULL,
prov_rendering_name_1,
prov_rendering_name_2,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_rendering_std_taxonomy,
prov_specialty as prov_rendering_vendor_specialty,
NULL,
prov_billing_tax_id,
NULL,
prov_billing_ssn,
prov_billing_state_license,
prov_billing_upin,
NULL,
prov_billing_name_1,
prov_billing_name_2,
prov_billing_address_1,
prov_billing_address_2,
prov_billing_city,
prov_billing_state,
prov_billing_zip,
prov_billing_std_taxonomy,
NULL,
NULL,
prov_referring_tax_id,
NULL,
NULL,
prov_referring_state_license,
prov_referring_upin,
prov_referring_commercial_id,
prov_referring_name_1,
prov_referring_name_2,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_facility_tax_id,
NULL,
NULL,
prov_facility_state_license,
NULL,
NULL,
prov_facility_name_1,
prov_facility_name_2,
prov_facility_address_1,
prov_facility_address_2,
prov_facility_city,
prov_facility_state,
prov_facility_zip,
NULL,
NULL,
cob_payer_id_1 as cob_payer_vendor_id_1,
cob_payer_seq_code_1,
cob_payer_hpid_1,
cob_payer_claim_filing_ind_code_1,
cob_ins_type_code_1,
cob_payer_id_2 as cob_payer_vendor_id_2,
cob_payer_seq_code_2,
cob_payer_hpid_2,
cob_payer_claim_filing_ind_code_2,
cob_ins_type_code_2
FROM emdeon_professional_claims_base3 b
    CROSS JOIN split_indices
    LEFT JOIN matching_payload ON b.claim_id = claimid
    LEFT JOIN zip3_to_state ON threeDigitZip = zip3
    LEFT JOIN payer_mapping ON payer_vendor_id = payer_id
WHERE split(related,':')[n-1] IS NOT NULL
    AND split(related,':')[n-1] <> '';

-- There can be a lot of raws with the same diagnosis. Only extract unique ones
INSERT INTO related_diags_tmp
SELECT DISTINCT claim_id, related
FROM emdeon_professional_claims_base;

INSERT INTO related_diags
SELECT claim_id, concat_ws(':', collect_list(related)) AS related
FROM related_diags_tmp GROUP BY claim_id;

INSERT INTO emdeon_professional_claims_unrelated
SELECT accident_related,
admission_hour,
amb_hosp_to_hosp,
amb_nurse_to_diag,
amb_nurse_to_hosp,
assignment_sign,
e.claim_id,
claim_type,
contract_allow_ind,
date_received,
diagnosis_code_qual,
dialysis_related,
discharge_hour,
electronic_claim,
esrd_patient,
explanation_code,
group_name,
hosp_admis_or_er,
in_out_network,
initial_procedure,
inst_admit_source_std_id,
inst_admit_type_std_id,
inst_date_admitted,
inst_discharge_status_std_id,
inst_drg_std_id,
inst_type_of_bill_std_id,
medical_coverage_type,
member_adr_city,
member_adr_line1,
member_adr_line2,
member_adr_state,
member_adr_zip,
member_dob,
member_fname,
member_gender,
member_id,
member_lname,
new_patient,
not_covrd_specialt,
patient_age,
patient_control,
patient_dob,
patient_fname,
patient_gender,
patient_id,
patient_lname,
patient_relation,
payer_name,
payer_vendor_id,
prov_billing_address_1,
prov_billing_address_2,
prov_billing_city,
prov_billing_name_1,
prov_billing_name_2,
prov_billing_npi,
prov_billing_ssn,
prov_billing_state,
prov_billing_state_license,
prov_billing_std_taxonomy,
prov_billing_tax_id,
prov_billing_upin,
prov_billing_zip,
prov_facility_address_1,
prov_facility_address_2,
prov_facility_city,
prov_facility_name_1,
prov_facility_name_2,
prov_facility_npi,
prov_facility_state,
prov_facility_state_license,
prov_facility_tax_id,
prov_facility_zip,
prov_referring_name_1,
prov_referring_name_2,
prov_referring_npi,
prov_referring_tax_id,
prov_rendering_name_1,
prov_rendering_name_2,
prov_rendering_npi,
prov_rendering_state_license,
prov_rendering_std_taxonomy,
prov_rendering_tax_id,
prov_rendering_upin,
prov_specialty,
release_sign,
statement_from,
statement_to,
sub_client_id,
tooth_number,
total_allowed,
total_charge,
date_service,
date_service as date_service_end,
string_set_diff(diag_concat,
rd.related) as unrelated 
FROM emdeon_professional_claims_base e 
    INNER JOIN related_diags rd USING (claim_id) 
WHERE service_line_number = '1'
CLUSTER BY claim_id;

CACHE TABLE emdeon_professional_claims_unrelated;

CREATE TEMPORARY VIEW emdeon_professional_claims_unrelated2 AS
SELECT * FROM emdeon_professional_claims_unrelated
WHERE ((datediff(date_service_end, date_service) IS NOT NULL
            AND datediff(date_service_end, date_service) > 0
            AND date_add(date_service, 366) > date_service_end)
        OR (datediff(statement_to, statement_from) IS NOT NULL
            AND datediff(statement_to, statement_from) > 0
            AND date_add(statement_from, 366) > statement_to));

CREATE TEMPORARY VIEW emdeon_professional_claims_unrelated3 AS
SELECT * FROM emdeon_professional_claims_unrelated
WHERE NOT ((datediff(date_service_end, date_service) IS NOT NULL
            AND datediff(date_service_end, date_service) > 0
            AND date_add(date_service, 366) > date_service_end)
        OR (datediff(statement_to, statement_from) IS NOT NULL
            AND datediff(statement_to, statement_from) > 0
            AND date_add(statement_from, 366) > statement_to));

INSERT INTO medicalclaims_common_model
SELECT
NULL,
b.claim_id,
hvid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
patient_gender,
patient_age,
patient_dob,
threeDigitZip as patient_zip3,
state as patient_state,
claim_type,
date_received,
CASE WHEN date_service IS NOT NULL AND date_service_end IS NOT NULL THEN date_add(date_service, date_explode_indices.d) ELSE date_add(statement_from, date_explode_indices.d) END,
CASE WHEN date_service IS NOT NULL AND date_service_end IS NOT NULL THEN date_add(date_service, date_explode_indices.d) ELSE date_add(statement_from, date_explode_indices.d) END,
inst_date_admitted,
NULL,
inst_admit_type_std_id,
NULL,
NULL,
inst_admit_source_std_id,
NULL,
NULL,
inst_discharge_status_std_id,
NULL,
NULL,
inst_type_of_bill_std_id,
NULL,
NULL,
inst_drg_std_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
split(unrelated,':')[n-1] as diagnosis_code,
CASE WHEN diagnosis_code_qual = '9' THEN '01' WHEN diagnosis_code_qual = 'X' THEN '02' END,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
medical_coverage_type,
NULL,
NULL,
total_charge,
total_allowed,
prov_rendering_npi,
prov_billing_npi,
prov_referring_npi,
prov_facility_npi,
payer_mapping.payer_id,
payer_mapping.payer_name,
payer_mapping.payer_parent_name,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_rendering_tax_id,
NULL,
NULL,
NULL,
prov_rendering_upin,
NULL,
prov_rendering_name_1,
prov_rendering_name_2,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_rendering_std_taxonomy,
prov_specialty AS prov_rendering_vendor_specialty,
NULL,
prov_billing_tax_id,
NULL,
prov_billing_ssn,
prov_billing_state_license,
prov_billing_upin,
NULL,
prov_billing_name_1,
prov_billing_name_2,
prov_billing_address_1,
prov_billing_address_2,
prov_billing_city,
prov_billing_state,
prov_billing_zip,
prov_billing_std_taxonomy,
NULL,
NULL,
prov_referring_tax_id,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_referring_name_1,
prov_referring_name_2,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_facility_tax_id,
NULL,
NULL,
prov_facility_state_license,
NULL,
NULL,
prov_facility_name_1,
prov_facility_name_2,
prov_facility_address_1,
prov_facility_address_2,
prov_facility_city,
prov_facility_state,
prov_facility_zip,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM emdeon_professional_claims_unrelated2 b
    CROSS JOIN split_indices
    CROSS JOIN date_explode_indices
    LEFT JOIN matching_payload ON b.claim_id = claimid
    LEFT JOIN zip3_to_state ON threeDigitZip = zip3
    LEFT JOIN payer_mapping ON payer_vendor_id = payer_id
WHERE split(unrelated,':')[n-1] IS NOT NULL
    AND split(unrelated,':')[n-1] <> ''
    AND (date_add(date_service, date_explode_indices.d) <= date_service_end
        OR (date_add(statement_from, date_explode_indices.d) <= statement_to));

INSERT INTO medicalclaims_common_model
SELECT
NULL,
b.claim_id,
hvid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
patient_gender,
patient_age,
patient_dob,
threeDigitZip as patient_zip3,
state as patient_state,
claim_type,
date_received,
CASE WHEN date_service IS NOT NULL THEN date_service ELSE statement_from END,
CASE WHEN date_service_end IS NOT NULL THEN date_service ELSE statement_to END,
inst_date_admitted,
NULL,
inst_admit_type_std_id,
NULL,
NULL,
inst_admit_source_std_id,
NULL,
NULL,
inst_discharge_status_std_id,
NULL,
NULL,
inst_type_of_bill_std_id,
NULL,
NULL,
inst_drg_std_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
split(unrelated,':')[n-1] as diagnosis_code,
CASE WHEN diagnosis_code_qual = '9' THEN '01' WHEN diagnosis_code_qual = 'X' THEN '02' END,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
medical_coverage_type,
NULL,
NULL,
total_charge,
total_allowed,
prov_rendering_npi,
prov_billing_npi,
prov_referring_npi,
prov_facility_npi,
payer_mapping.payer_id,
payer_mapping.payer_name,
payer_mapping.payer_parent_name,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_rendering_tax_id,
NULL,
NULL,
NULL,
prov_rendering_upin,
NULL,
prov_rendering_name_1,
prov_rendering_name_2,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_rendering_std_taxonomy,
prov_specialty AS prov_rendering_vendor_specialty,
NULL,
prov_billing_tax_id,
NULL,
prov_billing_ssn,
prov_billing_state_license,
prov_billing_upin,
NULL,
prov_billing_name_1,
prov_billing_name_2,
prov_billing_address_1,
prov_billing_address_2,
prov_billing_city,
prov_billing_state,
prov_billing_zip,
prov_billing_std_taxonomy,
NULL,
NULL,
prov_referring_tax_id,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_referring_name_1,
prov_referring_name_2,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
prov_facility_tax_id,
NULL,
NULL,
prov_facility_state_license,
NULL,
NULL,
prov_facility_name_1,
prov_facility_name_2,
prov_facility_address_1,
prov_facility_address_2,
prov_facility_city,
prov_facility_state,
prov_facility_zip,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM emdeon_professional_claims_unrelated3 b
    CROSS JOIN split_indices
    LEFT JOIN matching_payload ON b.claim_id = claimid
    LEFT JOIN zip3_to_state ON threeDigitZip = zip3
    LEFT JOIN payer_mapping ON payer_vendor_id = payer_id
WHERE split(unrelated,':')[n-1] IS NOT NULL
    AND split(unrelated,':')[n-1] <> '';

