INSERT INTO clean_patientdata
SELECT
    analyticrowidnumber,
    clinicorganizationidnumber,
    defaultclinicidnumber,
    patientidnumber,
    pd.patientid,
    hvid,
    medicalrecordnumber,
    labidnumber,
    pd.state,
    mask_zip_code(substring(zipcode, 1, 3)) as zipcode,
    sex,
    status_original,
    patientstatus,
    statusisactive,
    primarymodality,
    primarymodality_original,
    primarydialysissetting,
    extract_date(substring(datefirstdialysis, 1, 10), '%Y-%m-%d') as datefirstdialysis,
    extract_date(substring(laststatuschangedate, 1, 10), '%Y-%m-%d') as laststatuschangedate,
    tribecode,
    extract_date(substring(inactivatedate, 1, 10), '%Y-%m-%d') as inactivatedate,
    cap_age(pd.age) as age,
    monthsindialysis,
    transplantwaitlist,
    medicalcoveragemedicare,
    extract_date(substring(medicalcoveragemedicareeffectivedate, 1, 10), '%Y-%m-%d') as medicalcoveragemedicareeffectivedate,
    masterpatientidnumber,
    extract_date(substring(datefirstdialysiscurrentunit, 1, 10), '%Y-%m-%d') as datefirstdialysiscurrentunit
FROM patientdata pd
LEFT JOIN matching_payload ON analyticrowidnumber = claimId
;

INSERT INTO clean_patientmasterscheduleheader
SELECT
    analyticrowidnumber,
    patientdataanalyticrowidnumber,
    clinicorganizationidnumber,
    patientmasterscheduleheaderid,
    patientidnumber,
    clinicid,
    scheduletype,
    extract_date(substring(startdate, 1, 10), '%Y-%m-%d') as startdate,
    extract_date(substring(enddate, 1, 10), '%Y-%m-%d') as enddate,
    starttime,
    endtime,
    scheduleshift,
    patientstatus,
    patientstatus_original,
    statusisactive,
    txtypeidnumber,
    reoccurrencetype,
    recurevery,
    mon,
    tue,
    wed,
    thu,
    fri,
    sat,
    sun,
    disabled,
    extract_date(substring(addeddate, 1, 10), '%Y-%m-%d') as addeddate,
    extract_date(substring(editdate, 1, 10), '%Y-%m-%d') as editdate,
    clinicscheduleid,
    extract_date(substring(originaldate, 1, 10), '%Y-%m-%d') as originaldate,
    reasontransferred,
    referringphysician,
    networkevent,
    extract_date(substring(inactivatedate, 1, 10), '%Y-%m-%d') as inactivatedate,
    sessionsperweek
FROM patientmasterscheduleheader
;

