SELECT 
 column1 AS claim_payment_number,
 column2 AS record_type,
 column3 AS line_number,
 column4 AS service_from_date,
 column5 AS service_to_date,
 column6 AS place_of_service,
 column7 AS adjudicated_procedure_cd,
 column8 AS adjudicated_procedure_cd_qual,
 column9 AS adjudicated_proc_modifier_1,
 column10 AS adjudicated_proc_modifier_2,
 column11 AS adjudicated_proc_modifier_3,
 column12 AS adjudicated_proc_modifier_4,
 column13 AS line_charge_amount,
 column14 AS line_allowed_amount,
 column15 AS group_code_1,
 column16 AS reason_code_1,
 column17 AS adjustment_amount_1,
 column18 AS adjustment_quantity_1,
 column19 AS group_code_2,
 column20 AS reason_code_2,
 column21 AS adjustment_amount_2,
 column22 AS adjustment_quantity_2,
 column23 AS group_code_3,
 column24 AS reason_code_3,
 column25 AS adjustment_amount_3,
 column26 AS adjustment_quantity_3,
 column27 AS group_code_4,
 column28 AS reason_code_4,
 column29 AS adjustment_amount_4,
 column30 AS adjustment_quantity_4,
 column31 AS group_code_5,
 column32 AS reason_code_5,
 column33 AS adjustment_amount_5,
 column34 AS adjustment_quantity_5,
 column35 AS paid_units_of_service,
 column36 AS revenue_code,
 column37 AS line_rendering_prov_npi,
 column38 AS submitted_units_of_service,
 column39,
 column40,
 column41,
 column42,
 column43,
 column44,
 column45,
 column46,
 column47,
 column48,
 column49,
 column50,
 column51,
 column52 AS line_paid_amount,
 column53 AS date_paid,
 column54,
 column55,
 column56,
 column57 AS submitted_procedure_cd,
 column58 AS submitted_procedure_cd_qual,
 column59 AS submitted_proc_modifier_1,
 column60 AS submitted_proc_modifier_2,
 column61 AS submitted_proc_modifier_3,
 column62 AS submitted_proc_modifier_4,
 input_file_name
 FROM change_835_raw
WHERE column2 = 'S'
