#!/bin/bash
set -e

cluster_name=$1
cluster_size=$2
ec2_type="$3"
applications=$4
use_ebs=$5
ebs_size=$6
use_analytics_metastore=$7
cluster_purpose=$8

tstmp=$(date +%Y%m%dT%H%M%S)

# Definte the EMR Instance Groups
MASTER_IG="Name=MASTER,InstanceGroupType=MASTER,"
MASTER_IG+="InstanceCount=1,InstanceType=m3.xlarge"

CORE_IG="InstanceGroupType=CORE,"
CORE_IG+="InstanceCount=${cluster_size},InstanceType=${ec2_type}"
if [ "$use_ebs" == "true" ]
then
  CORE_IG+=",EbsConfiguration={EbsOptimized=true,EbsBlockDeviceConfigs=[{VolumeSpecification={VolumeType=gp2,SizeInGB=${ebs_size}}}]}"
fi

if [ "$use_analytics_metastore" == "true" ]
then
  METASTORE_CONFIG=" --configurations file://$AIRFLOW_HOME/dags/resources/hiveConfiguration.json"
else
  METASTORE_CONFIG=" --configurations file://$AIRFLOW_HOME/dags/resources/sparkConfiguration.json"
fi

EC2_ATTR="KeyName=emr_deployer,SubnetId=subnet-b262ec99,InstanceProfile=EMR_EC2_DefaultRole,ServiceAccessSecurityGroup=sg-39e8c241,EmrManagedMasterSecurityGroup=sg-46e8c23e,EmrManagedSlaveSecurityGroup=sg-47e8c23f"

set -x
aws emr create-cluster                     \
 --release-label emr-5.0.3                 \
 --applications $applications              \
 --service-role EMR_DefaultRole            \
 --enable-debugging                        \
 --ec2-attributes "${EC2_ATTR}"            \
 --name "$cluster_name"                    \
 --tags "\"EMRCluster=${cluster_name}_$(date +%Y%m%d%H%M)\" \"Service=${cluster_purpose}\""	\
 --log-uri s3://salusvlogs/presto/jenkins/${tstmp}/      \
 --instance-groups                         \
   "${MASTER_IG}"                          \
   "${CORE_IG}"                            \
 $METASTORE_CONFIG
