from pyspark.sql.types import *
from spark.common.schema import Schema

schema_v1 = StructType([
    StructField('row_id', LongType(), True),
    StructField('hv_srs_id', StringType(), True),
    StructField('crt_dt', DateType(), True),
    StructField('mdl_vrsn_num', StringType(), True),
    StructField('data_set_nm', StringType(), True),
    StructField('src_vrsn_id', StringType(), True),
    StructField('hvm_vdr_id', IntegerType(), True),
    StructField('hvm_vdr_feed_id', IntegerType(), True),
    StructField('vdr_org_id', StringType(), True),
    StructField('vdr_study_id', StringType(), True),
    StructField('vdr_srs_id', StringType(), True),
    StructField('hvid', StringType(), True),
    StructField('ptnt_birth_yr', IntegerType(), True),
    StructField('ptnt_age_num', StringType(), True),
    StructField('ptnt_gender_cd', StringType(), True),
    StructField('ptnt_state_cd', StringType(), True),
    StructField('ptnt_zip3_cd', StringType(), True),
    StructField('ptnt_height_msrmt', StringType(), True),
    StructField('ptnt_weight_msrmt', StringType(), True),
    StructField('ptnt_bmi_msrmt', StringType(), True),
    StructField('ptnt_smkg_flg', StringType(), True),
    StructField('ptnt_prgncy_flg', StringType(), True),
    StructField('imgg_stdy_dt', DateType(), True),
    StructField('srs_img_cnt', IntegerType(), True),
    StructField('intrptg_prov_nm', StringType(), True),
    StructField('intrptg_prov_npi', StringType(), True),
    StructField('intrptg_prov_id', StringType(), True),
    StructField('intrptg_prov_id_qual', StringType(), True),
    StructField('rfrg_prov_nm', StringType(), True),
    StructField('rfrg_prov_npi', StringType(), True),
    StructField('rfrg_prov_id', StringType(), True),
    StructField('rfrg_prov_id_qual', StringType(), True),
    StructField('ordg_prov_nm', StringType(), True),
    StructField('ordg_prov_npi', StringType(), True),
    StructField('ordg_prov_id', StringType(), True),
    StructField('ordg_prov_id_qual', StringType(), True),
    StructField('cnsltg_prov_nm', StringType(), True),
    StructField('cnsltg_prov_npi', StringType(), True),
    StructField('cnsltg_prov_id', StringType(), True),
    StructField('cnsltg_prov_id_qual', StringType(), True),
    StructField('prmy_care_prov_nm', StringType(), True),
    StructField('prmy_care_prov_npi', StringType(), True),
    StructField('prmy_care_prov_id', StringType(), True),
    StructField('prmy_care_prov_id_qual', StringType(), True),
    StructField('img_mdlty_cd', StringType(), True),
    StructField('ptnt_bdy_prt_latlty_cd', StringType(), True),
    StructField('imgg_proc_cd', StringType(), True),
    StructField('imgg_proc_cd_qual', StringType(), True),
    StructField('imgg_eqpmt_manfctr_nm', StringType(), True),
    StructField('imgg_eqpmt_manfctr_mdl_nm', StringType(), True),
    StructField('imgg_agt_actv_ingdt_nm', StringType(), True),
    StructField('imgg_agt_actv_ingdt_cnctrtn_msrmt', StringType(), True),
    StructField('clr_intrptn_cd', StringType(), True),
    StructField('imgd_bdy_prt_cd', StringType(), True),
    StructField('img_idx_num', IntegerType(), True)
])

data_type = "image"
output_directory = data_type + '/2019-09-05/'
schemas = {
    'schema_v1': Schema(name='schema_v1',
                        schema_structure=schema_v1,
                        distribution_key='row_id',
                        data_type=data_type,
                        provider_partition_column='part_hvm_vdr_feed_id',
                        date_partition_column='part_mth',
                        output_directory=output_directory)
}
