SELECT
    txn.input_file_name,
    txn.orderid_patientid,
    txn.patientnamefirst,
    txn.patientnamemiddle,
    txn.patientnamelast,
    txn.patientdob,
    txn.patientgender,
    txn.ssn,
    txn.patientaddressstreet,
    txn.patientaddressstreet2,
    txn.patientaddresscity,
    txn.patientaddresssubentity,
    txn.patientaddresspostalcode,
    EXPLODE_OUTER(SPLIT(txn.diagnosiscodes, '\\^')) AS diagnosiscodes, 
    txn.diagnosisdescription,
    txn.fasting,
    txn.performinglab_performed,
    txn.labname_performed,
    txn.labaddress_performed,
    txn.labcity_performed,
    txn.labstate_performed,
    txn.labpostalcode_performed,
    txn.performinglab_analyzed,
    txn.labname_analyzed,
    txn.labaddress_analyzed,
    txn.labcity_analyzed,
    txn.labstate_analyzed,
    txn.labpostalcode_analyzed,
    txn.clientid,
    txn.clientname_ordering_practice,
    txn.clientname_result,
    txn.clientaddressstreet,
    txn.clientaddresscity,
    txn.clientaddresssubentity,
    txn.clientaddresspostalcode,
    txn.orderingprovidernpi,
    txn.orderingprovidernamefirst,
    txn.orderingprovidernamemiddle,
    txn.orderingprovidernamelast,
    txn.orderingprovidersuffix,
    txn.orderingprovidercodetype,
    txn.accessionid,
    txn.sourcetestid_site,
    txn.sourcetestid_type,
    txn.stat,
    txn.testid,
    txn.ordertest_or_paneltest,
    txn.resultcpt,
    txn.resulttestcode,
    txn.resulttestname,
    txn.loinccode,
    txn.resultstatus,
    txn.resulttext,
    txn.units_of_measure,
    txn.resultreferencerange_lab_specific,
    txn.resultabnormalflag,
    txn.resultreferencerange,
    txn.drawdate_drawtime,
    txn.userdatetime,
    txn.lis_released_result_date_time,
    txn.reportfinal,
    txn.copyto,
    txn.reported_route_status,
    txn.orderid_test,
    txn.paneltestcode,
    txn.paneltestname,
    txn.hvjoinkey

FROM transaction txn
WHERE UPPER(COALESCE(txn.patientgender, '')) <> 'PATIENTGENDER' 
    /* Eliminate non-U.S. transactions, for privacy. */ 
AND EXISTS 
        (
            SELECT 1 
            FROM ref_geo_state st 
            WHERE UPPER(COALESCE(txn.clientaddresssubentity, txn.patientaddresssubentity)) = st.geo_state_pstl_cd
        )
