/** This table will go to the warehouse,
  but it should use the original file-date
  in the parquet name */
SELECT
    record_id,
    claim_id,
    hvid,
    created,
    model_version,
    data_set,
    data_feed,
    data_vendor,
    patient_gender,
    patient_year_of_birth,
    patient_zip3,
    date_service,
    date_service_end,
    inst_discharge_status_std_id,
    place_of_service_std_id,
    diagnosis_code,
    diagnosis_code_qual,
    diagnosis_priority,
    procedure_code,
    procedure_code_qual,
    procedure_modifier_1,
    procedure_modifier_2,
    procedure_modifier_3,
    procedure_modifier_4,
    revenue_code,
    prov_billing_npi,
    prov_billing_name_1,
    prov_billing_address_1,
    prov_billing_address_2,
    prov_billing_city,
    prov_billing_state,
    prov_billing_zip,
    part_best_date,
    part_provider,
    file_date
FROM esi_join_historic_and_payload_dx
WHERE instr(hvid, '_') = 0