DROP TABLE IF EXISTS part_transactional;
CREATE EXTERNAL TABLE part_transactional (
        first_name                     string,
        last_name                      string,
        date_of_birth                  string,
        gender                         string,
        zip_code                       string,
        street_address                 string,
        street_address_2               string,
        city                           string,
        state                          string,
        customer__patient_id           string,
        ngs_offering                   string,
        fish_cmet                      string,
        fish_cmyc                      string,
        fish_egfr                      string,
        fish_her2__neu                 string,
        fish_pik3ca                    string,
        fish_top2a                     string,
        fish_mutational_1p19q          string,
        fish_mutational_alk            string,
        fish_mutational_ros1           string,
        cish_cmet                      string,
        cish_egfr                      string,
        cish_her2__neu                 string,
        cish_mdm2                      string,
        cish_top2a                     string,
        ihc_ae1__ae3                   string,
        ihc_afp                        string,
        ihc_alk                        string,
        ihc_ar                         string,
        ihc_bcl2                       string,
        ihc_bcrp                       string,
        ihc_bombesin                   string,
        ihc_brcp                       string,
        ihc_ca_19_9                    string,
        ihc_calcitonin                 string,
        ihc_calret                     string,
        ihc_calretinin                 string,
        ihc_cam5_2                     string,
        ihc_cav_1                      string,
        ihc_cd10                       string,
        ihc_cd20                       string,
        ihc_cd20__l26                  string,
        ihc_cd25                       string,
        ihc_cd30                       string,
        ihc_cd31                       string,
        ihc_cd34                       string,
        ihc_cd52                       string,
        ihc_cd56                       string,
        ihc_cd68                       string,
        ihc_cd99                       string,
        ihc_cdx2                       string,
        ihc_cea                        string,
        ihc_chromogranin               string,
        ihc_ck14                       string,
        ihc_ck17                       string,
        ihc_ck19                       string,
        ihc_ck20                       string,
        ihc_ck5                        string,
        ihc_ck5__6                     string,
        ihc_ck7                        string,
        ihc_ck8                        string,
        ihc_c_kit                      string,
        ihc_cmet                       string,
        ihc_cox2                       string,
        ihc_cyclin_d1                  string,
        ihc_dog_1                      string,
        ihc_ebv                        string,
        ihc_ecad                       string,
        ihc_egfr                       string,
        ihc_ema                        string,
        ihc_er                         string,
        ihc_ercc1                      string,
        ihc_gcdfp                      string,
        ihc_gcdfp__brst_ii             string,
        ihc_gcdfp_15                   string,
        ihc_h3k36me3                   string,
        ihc_hcg                        string,
        ihc_her2__neu                  string,
        ihc_hmb45                      string,
        ihc_hsp90                      string,
        ihc_igf1r                      string,
        ihc_inhibin                    string,
        ihc_ki1                        string,
        ihc_ki67                       string,
        ihc_l26                        string,
        ihc_lca                        string,
        ihc_mammaglobin                string,
        ihc_mart_1                     string,
        ihc_melana                     string,
        ihc_melanoma_specific_antigen  string,
        ihc_mgmt                       string,
        ihc_mitf                       string,
        ihc_mlh1                       string,
        ihc_mrp1                       string,
        ihc_msh2                       string,
        ihc_msh6                       string,
        ihc_nse                        string,
        ihc_oc125                      string,
        ihc_p53                        string,
        ihc_p63                        string,
        ihc_p95                        string,
        ihc_pap                        string,
        ihc_pbrm1                      string,
        ihc_pd_1                       string,
        ihc_pdgfr                      string,
        ihc_pd_l1                      string,
        ihc_pgp                        string,
        ihc_pms2                       string,
        ihc_pr                         string,
        ihc_psa                        string,
        ihc_psap                       string,
        ihc_pten                       string,
        ihc_rcc                        string,
        ihc_rcca                       string,
        ihc_rrm1                       string,
        ihc_rrm2                       string,
        ihc_s100                       string,
        ihc_sma                        string,
        ihc_sparc                      string,
        ihc_sparc_monoclonal           string,
        ihc_sparc_polyclonal           string,
        ihc_survivin                   string,
        ihc_synaptophysin              string,
        ihc_thyroglobulin              string,
        ihc_tle3                       string,
        ihc_top2a                      string,
        ihc_topo1                      string,
        ihc_ts                         string,
        ihc_ttf                        string,
        ihc_ttf1                       string,
        ihc_tubb3                      string,
        ihc_uchl_1                     string,
        ihc_vegf                       string,
        ihc_vimentin                   string,
        ihc_wt1                        string,
        ihc_h_score_egfr               string,
        ihc_ia_ecad                    string,
        ihc_ia_er                      string,
        ihc_ia_her2__neu               string,
        ihc_ia_ki67                    string,
        ihc_ia_p53                     string,
        ihc_ia_pr                      string,
        hv_key                         string
        )
    ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    WITH SERDEPROPERTIES (
        'separatorChar' = '|'
        )
    STORED AS TEXTFILE
    LOCATION {input_path}
;

DROP TABLE IF EXISTS additional_columns;
CREATE EXTERNAL TABLE additional_columns (
        patient_id      string,
        ods_id          string,
        accession_date  string,
        sign_out_date   string
        )
    ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    LOCATION {addon_path}
;

-- merge tables
DROP TABLE IF EXISTS raw_transactional;
CREATE TABLE raw_transactional AS (
    SELECT t.*, a.ods_id as ods_id,
        a.accession_date AS accession_date,
        a.sign_out_date AS sign_out_date,
        CAST(NULL as string) as new_accession_date
    FROM part_transactional t
        LEFT JOIN additional_columns a
        ON t.customer__patient_id = a.patient_id
        )
    ;
