SELECT
    hv_medctn_id,
    crt_dt,
    mdl_vrsn_num,
    data_set_nm,
    hvm_vdr_id,
    hvm_vdr_feed_id,
    vdr_org_id,
    vdr_medctn_ord_id,
    vdr_medctn_ord_id_qual,
    hvid,
    ptnt_birth_yr,
    ptnt_gender_cd,
    ptnt_state_cd,
    ptnt_zip3_cd,
    hv_enc_id,
    enc_dt,
    medctn_ord_dt,
    medctn_prov_nucc_taxnmy_cd,
    medctn_prov_alt_speclty_id,
    medctn_prov_alt_speclty_id_qual,
    medctn_prov_fclty_nm,
    medctn_prov_state_cd,
    medctn_prov_zip_cd,
    medctn_start_dt,
    medctn_end_dt,
    medctn_diag_cd,
    medctn_diag_cd_qual,
    medctn_ndc,
    medctn_alt_cd,
    medctn_alt_cd_qual,
    medctn_genc_ok_flg,
    medctn_brd_nm,
    medctn_genc_nm,
    medctn_rx_flg,
    medctn_rx_qty,
    medctn_dly_qty,
    medctn_days_supply_qty,
    medctn_admin_form_nm,
    medctn_strth_txt,
    medctn_dose_txt,
    medctn_admin_rte_txt,
    medctn_remng_rfll_qty,
    medctn_elect_rx_flg,
    data_captr_dt,
    prmy_src_tbl_nm,
    part_hvm_vdr_feed_id,
    part_mth
FROM practice_fusion_emr_norm_pre_emr_medctn
GROUP BY  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
         11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
         21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
         31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 47
