SELECT
    clm.claim_tcn_id	                        AS	claim_tcn_id                     ,
    clm.record_type                             AS	record_type	                     ,
    clm.payer_id                                AS	payer_id	                     ,
    clm.coding_type                             AS	coding_type	                     ,
    clm.received_date	                        AS	received_date                    ,
    clm.claim_type	                            AS	claim_type	                     ,
    column_7                                    AS	column_7	                     ,
    clm.payer_name	                            AS	payer_name	                     ,
    column_9                                    AS	column_9	                     ,
    column_10                                   AS	column_10	                     ,
    column_11                                   AS	column_11	                     ,
    column_12                                   AS	column_12	                     ,
    column_13                                   AS	column_13	                     ,
    column_14                                   AS	column_14	                     ,
    clm.member_birth_year                       AS	member_birth_year                ,
    column_16                                   AS	column_16	                     ,
    column_17                                   AS	column_17	                     ,
    column_18                                   AS	column_18	                     ,
    clm.patient_state                           AS	patient_state	                 ,
    clm.patient_zip3                            AS	patient_zip3	                 ,
    column_21                                   AS	column_21	                     ,
    clm.patient_relationship_code	            AS	patient_relationship_code        ,
    column_23	                                AS	column_23                        ,
    column_24	                                AS	column_24                        ,
    clm.patient_gender_code	                    AS	patient_gender_code              ,
    clm.patient_birth_year	                    AS	patient_birth_year               ,
    column_27	                                AS	column_27	                     ,
    clm.billing_prov_id	                        AS	billing_prov_id	                 ,
    clm.billing_prov_npi	                    AS	billing_prov_npi                 ,
    clm.billing_prov_org_name	                AS	billing_prov_org_name	         ,
    clm.billing_prov_ind_name	                AS	billing_prov_ind_name	         ,
    clm.billing_prov_street_address_1	        AS	billing_prov_street_address_1    ,
    clm.billing_prov_street_address_2	        AS	billing_prov_street_address_2    ,
    clm.billing_prov_state                      AS	billing_prov_state	             ,
    clm.billing_prov_zip                        AS	billing_prov_zip	             ,
    column_37                                   AS	column_37	                     ,
    clm.referring_prov_npi                      AS	referring_prov_npi	             ,
    column_39                                   AS	column_39	                     ,
    clm.referring_prov_name                     AS	referring_prov_name	             ,
    column_41                                   AS	column_41	                     ,
    clm.billing_prov_city                       AS  billing_prov_city	             ,
    clm.rendering_attending_prov_npi            AS	rendering_attending_prov_npi     ,
    clm.rendering_prov_org_name                 AS	rendering_prov_org_name	         ,
    clm.rendering_attending_prov_ind_name       AS	rendering_attending_prov_ind_name,
    column_45                                   AS	column_45                        ,
    clm.facility_name                           AS	facility_name                    ,
    column_47                                   AS	column_47                        ,
    clm.facility_street_address_1               AS	facility_street_address_1        ,
    clm.facility_street_address_2               AS	facility_street_address_2        ,
    clm.facility_city                           AS	facility_city                    ,
    clm.facility_state                          AS	facility_state                   ,
    clm.facility_zip                            AS	facility_zip                     ,
    clm.statement_from_date                     AS	statement_from_date	             ,
    clm.statement_to_date                       AS	statement_to_date	             ,
    clm.total_claim_charge_amt                  AS	total_claim_charge_amt           ,
    column_56                                   AS	column_56                        ,
    clm.drg_code                                AS	drg_code                         ,
    column_58                                   AS	column_58                        ,
    clm.bill_type                               AS	bill_type                        ,
    clm.patient_signature_source_cd             AS	patient_signature_source_cd	     ,
    clm.bebefits_assignment_cert_ind            AS	benefits_assignment_cert_ind     ,
    column_62                                   AS	column_62	                     ,
    clm.principal_icd_procedure_code	        AS	principal_icd_procedure_code     ,
    clm.admitting_diagnosis_code                AS	admitting_diagnosis_code	     ,
    clm.principal_diagnosis_code                AS	principal_diagnosis_code	     ,
    clm.other_diagnosis_code_1                  AS	other_diagnosis_code_1           ,
    clm.other_diagnosis_code_2                  AS	other_diagnosis_code_2           ,
    clm.other_diagnosis_code_3                  AS	other_diagnosis_code_3           ,
    clm.other_diagnosis_code_4                  AS	other_diagnosis_code_4           ,
    clm.other_diagnosis_code_5                  AS	other_diagnosis_code_5           ,
    clm.other_diagnosis_code_6                  AS	other_diagnosis_code_6           ,
    clm.other_diagnosis_code_7                  AS	other_diagnosis_code_7           ,
    clm.other_icd_proc_code_1                   AS	other_icd_proc_code_1            ,
    clm.other_icd_proc_code_2                   AS	other_icd_proc_code_2            ,
    clm.other_icd_proc_code_3                   AS	other_icd_proc_code_3            ,
    clm.other_icd_proc_code_4                   AS	other_icd_proc_code_4            ,
    clm.other_icd_proc_code_5                   AS	other_icd_proc_code_5            ,
    column_78                                   AS	column_78	                     ,
    clm.claim_filing_indicator_cd               AS	claim_filing_indicator_cd        ,
    column_80	                                AS	column_80	                     ,
    clm.accident_related_ind	                AS	accident_related_ind	         ,
    column_82                                   AS	column_82               	     ,
    column_83                                   AS	column_83               	     ,
    column_84                                   AS	column_84               	     ,
    column_85                                   AS	column_85               	     ,
    column_86                                   AS	column_86               	     ,
    column_87                                   AS	column_87               	     ,
    column_88                                   AS	column_88               	     ,
    column_89                                   AS	column_89               	     ,
    column_90                                   AS	column_90               	     ,
    column_91                                   AS	column_91               	     ,
    clm.admission_date	                        AS	admission_date	                 ,
    column_93                                   AS	column_93	                     ,
    clm.admission_type_code	                    AS	admission_type_code	             ,
    clm.admission_source_code	                AS	admission_source_code	         ,
    column_96	                                AS	column_96	                     ,
    clm.patient_status_code                     AS	patient_status_code	             ,
    column_98	                                AS	column_98	                     ,
    clm.other_icd_proc_code_6                   AS	other_icd_proc_code_6	         ,
    clm.other_icd_proc_code_7                   AS	other_icd_proc_code_7	         ,
    clm.other_icd_proc_code_8                   AS	other_icd_proc_code_8	         ,
    clm.other_icd_proc_code_9                   AS	other_icd_proc_code_9	         ,
    clm.billing_pr_taxonomy                     AS	billing_pr_taxonomy	             ,
    clm.billing_pr_state_license                AS	billing_pr_state_license	     ,
    column_105	                                AS	column_105	                     ,
    clm.billing_pr_ssn 	                        AS	billing_pr_ssn	                 ,
    clm.rendering_attending_prov_taxonomy	    AS	rendering_attending_prov_taxonomy,
    clm.rendering_attending_prov_state_license	AS	rendering_attending_prov_state_license,
    column_109	                                AS	column_109	                     ,
    clm.facility_npi	                        AS	facility_npi	                 ,
    clm.facility_state_license	                AS	facility_state_license	         ,

    clm.input_file_name                         AS  input_file_name,
    --------------------------------------------------------
    --- From Payload
    --------------------------------------------------------
    CASE
        WHEN pay.hvid is not null THEN obfuscate_hvid(pay.hvid, 'changerelay')
    ELSE NULL
    END               AS pay_hvid,
    pay.gender        AS pay_gender,
    pay.yearofbirth   AS pay_yearofbirth,
    pay.threedigitzip AS pay_threedigitzip,
    pay.state         AS pay_state,
    --------------------------------------------------------
    --- From passthrough
    --------------------------------------------------------
    pas.pcn     AS pas_pcn,
    --------------------------------------------------------
    --- From plainout
    --------------------------------------------------------
    pln.patient_gender AS pln_patient_gender
FROM claim clm
LEFT OUTER JOIN matching_payload     pay ON  UPPER(clm.claim_tcn_id) = UPPER(pay.claimid)
LEFT OUTER JOIN pas_tiny pas ON  UPPER(clm.claim_tcn_id) = pas.claimid
LEFT OUTER JOIN pln_tiny    pln ON  UPPER(clm.claim_tcn_id) = pln.claim_number


WHERE clm.record_type = 'C'
GROUP BY
1,2,3,4,5,6,7,8,9,10,
11,12,13,14,15,16,17,18,19,20,
21,22,23,24,25,26,27,28,29,30,
31,32,33,34,35,36,37,38,39,40,
41,42,43,44,45,46,47,48,49,50,
51,52,53,54,55,56,57,58,59,60,
61,62,63,64,65,66,67,68,69,70,
71,72,73,74,75,76,77,78,79,80,
81,82,83,84,85,86,87,88,89,90,
91,92,93,94,95,96,97,98,99,
100,101,102,103,104,105,106,
107,108,109,110,111,112,113,114,115,116,117,118,119
