SELECT  
    hv_prov_ord_id,
    crt_dt,
    mdl_vrsn_num,
    data_set_nm,
    hvm_vdr_id,
    hvm_vdr_feed_id,
    vdr_prov_ord_id,
    vdr_prov_ord_id_qual,
    hvid,
    ptnt_birth_yr,
    ptnt_gender_cd,
    ptnt_state_cd,
    ptnt_zip3_cd,
    hv_enc_id,
    enc_dt,
    prov_ord_dt,
    prov_ord_prov_vdr_id,
    prov_ord_prov_vdr_id_qual,
    prov_ord_prov_mdcr_speclty_cd,
    prov_ord_prov_alt_speclty_id,
    prov_ord_prov_alt_speclty_id_qual,
    prov_ord_prov_zip_cd,
    prov_ord_typ_cd,
    prov_ord_typ_cd_qual,
    prov_ord_nm,
    prov_ord_alt_cd,
    prov_ord_alt_cd_qual,
    prov_ord_ndc,
    prov_ord_stat_nm,
    data_captr_dt,
    prmy_src_tbl_nm,
    part_hvm_vdr_feed_id,
    part_mth
FROM tsi_emr_norm_pre_emr_prov_ord_1
GROUP BY 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
         11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
         21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 
         31, 32, 33
