SELECT  
    hv_medctn_id,
    crt_dt,
    mdl_vrsn_num,
    data_set_nm,
    hvm_vdr_id,
    hvm_vdr_feed_id,
    vdr_medctn_ord_id,
    vdr_medctn_ord_id_qual,
    hvid,
    ptnt_birth_yr,
    ptnt_gender_cd,
    ptnt_state_cd,
    ptnt_zip3_cd,
    hv_enc_id,
    enc_dt,
    medctn_prov_npi,
    medctn_prov_qual,
    medctn_prov_vdr_id,
    medctn_prov_vdr_id_qual,
    medctn_prov_mdcr_speclty_cd,
    medctn_prov_alt_speclty_id,
    medctn_prov_alt_speclty_id_qual,
    medctn_prov_zip_cd,
    medctn_start_dt,
    medctn_end_dt,
    medctn_ndc,
    medctn_dispd_qty,
    medctn_strth_txt,
    medctn_dose_uom,
    medctn_remng_rfll_qty,
    medctn_elect_rx_flg,
    medctn_grp_txt,
    data_captr_dt,
    prmy_src_tbl_nm,
    part_hvm_vdr_feed_id,
    part_mth

FROM tsi_emr_norm_pre_emr_med_ord_1
GROUP BY  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
         11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
         21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 
         31, 32, 33, 34, 35, 36
