"""
pregnancy_registry medicalclaims claims schema
"""
# pylint: disable=duplicate-code
from pyspark.sql.types import *
from spark.common.schema import Schema
from spark.common.utility.output_type import DataType

schema_v1 = StructType([
    StructField('record_id', LongType(), True),
    StructField('registry_type', StringType(), True),
    StructField('claim_id', StringType(), True),
    StructField('hvid', StringType(), True),
    StructField('created', DateType(), True),
    StructField('model_version', StringType(), True),
    StructField('data_set', StringType(), True),
    StructField('data_feed', StringType(), True),
    StructField('data_vendor', StringType(), True),
    StructField('source_version', StringType(), True),
    StructField('vendor_org_id', StringType(), True),
    StructField('patient_gender', StringType(), True),
    StructField('patient_year_of_birth', StringType(), True),
    StructField('age_range', StringType(), True),
    StructField('claim_type', StringType(), True),
    StructField('date_received', DateType(), True),
    StructField('date_service', DateType(), True),
    StructField('date_service_end', DateType(), True),
    StructField('inst_date_admitted', DateType(), True),
    StructField('inst_date_discharged', DateType(), True),
    StructField('inst_admit_type_std_id', StringType(), True),
    StructField('inst_admit_type_vendor_id', StringType(), True),
    StructField('inst_admit_type_vendor_desc', StringType(), True),
    StructField('inst_admit_source_std_id', StringType(), True),
    StructField('inst_admit_source_vendor_id', StringType(), True),
    StructField('inst_admit_source_vendor_desc', StringType(), True),
    StructField('inst_discharge_status_std_id', StringType(), True),
    StructField('inst_discharge_status_vendor_id', StringType(), True),
    StructField('inst_discharge_status_vendor_desc', StringType(), True),
    StructField('inst_type_of_bill_std_id', StringType(), True),
    StructField('inst_type_of_bill_vendor_id', StringType(), True),
    StructField('inst_type_of_bill_vendor_desc', StringType(), True),
    StructField('inst_drg_std_id', StringType(), True),
    StructField('inst_drg_vendor_id', StringType(), True),
    StructField('inst_drg_vendor_desc', StringType(), True),
    StructField('place_of_service_std_id', StringType(), True),
    StructField('place_of_service_vendor_id', StringType(), True),
    StructField('place_of_service_vendor_desc', StringType(), True),
    StructField('service_line_number', StringType(), True),
    StructField('service_line_id', StringType(), True),
    StructField('diagnosis_code', StringType(), True),
    StructField('diagnosis_code_qual', StringType(), True),
    StructField('diagnosis_priority', StringType(), True),
    StructField('admit_diagnosis_ind', StringType(), True),
    StructField('procedure_code', StringType(), True),
    StructField('procedure_code_qual', StringType(), True),
    StructField('principal_proc_ind', StringType(), True),
    StructField('procedure_units_billed', FloatType(), True),
    StructField('procedure_units_paid', FloatType(), True),
    StructField('procedure_modifier_1', StringType(), True),
    StructField('procedure_modifier_2', StringType(), True),
    StructField('procedure_modifier_3', StringType(), True),
    StructField('procedure_modifier_4', StringType(), True),
    StructField('revenue_code', StringType(), True),
    StructField('ndc_code', StringType(), True),
    StructField('medical_coverage_type', StringType(), True),
    StructField('line_charge', FloatType(), True),
    StructField('line_allowed', FloatType(), True),
    StructField('total_charge', FloatType(), True),
    StructField('total_allowed', FloatType(), True),
    StructField('payer_vendor_id', StringType(), True),
    StructField('payer_name', StringType(), True),
    StructField('payer_parent_name', StringType(), True),
    StructField('payer_org_name', StringType(), True),
    StructField('payer_plan_id', StringType(), True),
    StructField('payer_plan_name', StringType(), True),
    StructField('payer_type', StringType(), True),
    StructField('prov_rendering_vendor_id', StringType(), True),
    StructField('prov_rendering_std_taxonomy', StringType(), True),
    StructField('prov_rendering_vendor_specialty', StringType(), True),
    StructField('prov_billing_vendor_id', StringType(), True),
    StructField('prov_billing_std_taxonomy', StringType(), True),
    StructField('prov_billing_vendor_specialty', StringType(), True),
    StructField('prov_referring_vendor_id', StringType(), True),
    StructField('prov_referring_std_taxonomy', StringType(), True),
    StructField('prov_referring_vendor_specialty', StringType(), True),
    StructField('prov_facility_vendor_id', StringType(), True),
    StructField('prov_facility_std_taxonomy', StringType(), True),
    StructField('prov_facility_vendor_specialty', StringType(), True),
    StructField('cob_payer_vendor_id_1', StringType(), True),
    StructField('cob_payer_seq_code_1', StringType(), True),
    StructField('cob_payer_hpid_1', StringType(), True),
    StructField('cob_payer_claim_filing_ind_code_1', StringType(), True),
    StructField('cob_ins_type_code_1', StringType(), True),
    StructField('cob_payer_vendor_id_2', StringType(), True),
    StructField('cob_payer_seq_code_2', StringType(), True),
    StructField('cob_payer_hpid_2', StringType(), True),
    StructField('cob_payer_claim_filing_ind_code_2', StringType(), True),
    StructField('cob_ins_type_code_2', StringType(), True),
    StructField('logical_delete_reason', StringType(), True),
    StructField('stg_file_date', DateType(), True)
])

data_type = DataType.MEDICAL_CLAIMS
schemas = {
    'schema_v1': Schema(name='schema_v1',
                        schema_structure=schema_v1,
                        distribution_key='record_id',
                        data_type=DataType(data_type).value,
                        provider_partition_column='part_provider',
                        date_partition_column='part_best_date',
                        output_directory='registry/' + DataType(data_type).value + '/2021-11-21/'
                        )
}
