SELECT 
    Service_Payemnt_Indicator,
    Batch_ID,
    Claim_ID,
    Sequence_Number,
    Product_or_Service_ID_Qualifier,
    Adjudicated_Procedure_Code,
    Adjudicated_Procedure_Modifier_1,
    Adjudicated_Procedure_Modifier_2,
    Adjudicated_Procedure_Modifer_3,
    Adjudicated_Procedure_Modifier_4,
    Procedure_Code_Description,
    Line_Item_Charge_Amount,
    Line_Item_Provider_Payment_Amount,
    NUBC_Revenue_Code,
    Units_of_Service_Paid_Count,
    Original_Product_or_Service_ID_Qualifier,
    Original_Submitted_Procedure_Code,
    Original_Submitted_Procedure_Modifiers_1,
    Original_Submitted_Procedure_Modifiers_2,
    Original_Submitted_Procedure_Modifiers_3,
    Original_Submitted_Procedure_Modifiers_4,
    Original_Units_of_Service_Count,
    Date_Time_Qualifier,
    Service_From_Date,
    Service_To_Date,
    Service_ID_Qualifier_1S,
    Ambulatory_Patient_Group_Number,
    Service_ID_Qualifier_APG,
    Ambulatory_Payment_Classification,
    Service_ID_Qualifier_BB,
    Authorization_Number,
    Service_ID_Qualifier_E9,
    Attachment_Code,
    Service_ID_Qualifier_G1,
    Prior_Authorization_Number,
    Service_ID_Qualifier_G3,
    Predetermination_of_Benefits_ID_Number,
    Service_ID_Qualifier_LU,
    Location_Number,
    Service_ID_Qualifier_RB,
    Rate_Code_Number,
    Line_Item_Control_Number___,
    Rendering_Provider_ID_Qual_1_,
    Rendering_Provider_ID__1,
    Rendering_Provider_ID_Qual_2,
    Rendering_Provider_ID_2,
    Rendering_Provider_ID_Qual_3,
    Rendering_Provider_ID__3,
    Rendering_Provider_ID_Qual_4,
    Rendering_Provider_ID__4,
    Rendering_Provider_ID_Qual_5,
    Rendering_Provider_ID__5,
    Rendering_Provider_ID_Qual_6,
    Rendering_Provider_ID__6,
    Rendering_Provider_ID_Qual_7,
    Rendering_Provider_ID__7,
    Rendering_Provider_ID_Qual_8,
    Rendering_Provider_ID__8,
    Rendering_Provider_ID_Qual_9,
    Rendering_Provider_ID__9,
    Rendering_Provider_ID_Qual_10,
    Rendering_Provider_ID_10,
    Healthcare_Policy_ID_Qual_1,
    Healthcare_Policy_ID__1,
    Healthcare_Policy_ID_Qual_2,
    Healthcare_Policy_ID__2,
    Healthcare_Policy_ID_Qual_3,
    Healthcare_Policy_ID__3,
    Healthcare_Policy_ID_Qual_4,
    Healthcare_Policy_ID__4,
    Healthcare_Policy_ID_Qual_5,
    Healthcare_Policy_ID__5,
    Service_Line_Supplemental_Amount_Identifier_Informational,
    Supplemental_Service_Amount,
    Allowed_Amount,
    Late_Amount,
    Service_Line_Supplemental_Quantity_Identifier_Informational,
    Estimated_Non_Covered,
    Service_Line_Supplemental_Quantity_Identifier_Informational_1,
    Federal_Medicare_or_Medicaid_Payment_Mandate_Category_1,
    Service_Line_Supplemental_Quantity_Identifier_Informational_2,
    Federal_Medicare_or_Medicaid_Payment_Mandate_Category_2,
    Service_Line_Supplemental_Quantity_Identifier_Informational_3,
    Federal_Medicare_or_Medicaid_Payment_Mandate_Category_3,
    Service_Line_Supplemental_Quantity_Identifier_Informational_4,
    Federal_Medicare_or_Medicaid_Payment_Mandate_Category_4,
    Service_Line_Supplemental_Quantity_Identifier_Informational_5,

    svcpvt_svc_ln_suplmtl_amt,
    svcpvt_svc_ln_suplmtl_amt_qual,
    svcpvt_svc_ln_rmrk_cd_seq_num,
    svcpvt_svc_ln_remrk_cd,
    svcpvt_svc_ln_remrk_cd_qual,
    densify_2d_array(ARRAY(
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_1, serviceline.svcpvt_svc_ln_adjmt_grp_cd_1, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_1, serviceline.svcpvt_svc_ln_adjmt_amt_1, serviceline.svcpvt_svc_ln_adjmt_qty_1 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_2, serviceline.svcpvt_svc_ln_adjmt_grp_cd_2, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_2, serviceline.svcpvt_svc_ln_adjmt_amt_2, serviceline.svcpvt_svc_ln_adjmt_qty_2 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_3, serviceline.svcpvt_svc_ln_adjmt_grp_cd_3, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_3, serviceline.svcpvt_svc_ln_adjmt_amt_3, serviceline.svcpvt_svc_ln_adjmt_qty_3 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_4, serviceline.svcpvt_svc_ln_adjmt_grp_cd_4, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_4, serviceline.svcpvt_svc_ln_adjmt_amt_4, serviceline.svcpvt_svc_ln_adjmt_qty_4 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_5, serviceline.svcpvt_svc_ln_adjmt_grp_cd_5, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_5, serviceline.svcpvt_svc_ln_adjmt_amt_5, serviceline.svcpvt_svc_ln_adjmt_qty_5 )
    ))[x.AdjSvcLnGrp][0]                                              AS  svcpvt_svc_ln_adjmt_seq_num ,
    densify_2d_array(ARRAY(
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_1, serviceline.svcpvt_svc_ln_adjmt_grp_cd_1, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_1, serviceline.svcpvt_svc_ln_adjmt_amt_1, serviceline.svcpvt_svc_ln_adjmt_qty_1 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_2, serviceline.svcpvt_svc_ln_adjmt_grp_cd_2, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_2, serviceline.svcpvt_svc_ln_adjmt_amt_2, serviceline.svcpvt_svc_ln_adjmt_qty_2 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_3, serviceline.svcpvt_svc_ln_adjmt_grp_cd_3, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_3, serviceline.svcpvt_svc_ln_adjmt_amt_3, serviceline.svcpvt_svc_ln_adjmt_qty_3 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_4, serviceline.svcpvt_svc_ln_adjmt_grp_cd_4, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_4, serviceline.svcpvt_svc_ln_adjmt_amt_4, serviceline.svcpvt_svc_ln_adjmt_qty_4 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_5, serviceline.svcpvt_svc_ln_adjmt_grp_cd_5, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_5, serviceline.svcpvt_svc_ln_adjmt_amt_5, serviceline.svcpvt_svc_ln_adjmt_qty_5 )
            ))[x.AdjSvcLnGrp][1]                                      AS  svcpvt_svc_ln_adjmt_grp_cd ,
    densify_2d_array(ARRAY(
             ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_1, serviceline.svcpvt_svc_ln_adjmt_grp_cd_1, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_1, serviceline.svcpvt_svc_ln_adjmt_amt_1, serviceline.svcpvt_svc_ln_adjmt_qty_1 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_2, serviceline.svcpvt_svc_ln_adjmt_grp_cd_2, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_2, serviceline.svcpvt_svc_ln_adjmt_amt_2, serviceline.svcpvt_svc_ln_adjmt_qty_2 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_3, serviceline.svcpvt_svc_ln_adjmt_grp_cd_3, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_3, serviceline.svcpvt_svc_ln_adjmt_amt_3, serviceline.svcpvt_svc_ln_adjmt_qty_3 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_4, serviceline.svcpvt_svc_ln_adjmt_grp_cd_4, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_4, serviceline.svcpvt_svc_ln_adjmt_amt_4, serviceline.svcpvt_svc_ln_adjmt_qty_4 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_5, serviceline.svcpvt_svc_ln_adjmt_grp_cd_5, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_5, serviceline.svcpvt_svc_ln_adjmt_amt_5, serviceline.svcpvt_svc_ln_adjmt_qty_5 )
            ))[x.AdjSvcLnGrp][2]                                      AS  svcpvt_svc_ln_adjmt_rsn_txt ,
    densify_2d_array(ARRAY(
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_1, serviceline.svcpvt_svc_ln_adjmt_grp_cd_1, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_1, serviceline.svcpvt_svc_ln_adjmt_amt_1, serviceline.svcpvt_svc_ln_adjmt_qty_1 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_2, serviceline.svcpvt_svc_ln_adjmt_grp_cd_2, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_2, serviceline.svcpvt_svc_ln_adjmt_amt_2, serviceline.svcpvt_svc_ln_adjmt_qty_2 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_3, serviceline.svcpvt_svc_ln_adjmt_grp_cd_3, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_3, serviceline.svcpvt_svc_ln_adjmt_amt_3, serviceline.svcpvt_svc_ln_adjmt_qty_3 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_4, serviceline.svcpvt_svc_ln_adjmt_grp_cd_4, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_4, serviceline.svcpvt_svc_ln_adjmt_amt_4, serviceline.svcpvt_svc_ln_adjmt_qty_4 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_5, serviceline.svcpvt_svc_ln_adjmt_grp_cd_5, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_5, serviceline.svcpvt_svc_ln_adjmt_amt_5, serviceline.svcpvt_svc_ln_adjmt_qty_5 )    
            ))[x.AdjSvcLnGrp][3]                                      AS  svcpvt_svc_ln_adjmt_amt ,
    densify_2d_array(ARRAY(
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_1, serviceline.svcpvt_svc_ln_adjmt_grp_cd_1, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_1, serviceline.svcpvt_svc_ln_adjmt_amt_1, serviceline.svcpvt_svc_ln_adjmt_qty_1 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_2, serviceline.svcpvt_svc_ln_adjmt_grp_cd_2, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_2, serviceline.svcpvt_svc_ln_adjmt_amt_2, serviceline.svcpvt_svc_ln_adjmt_qty_2 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_3, serviceline.svcpvt_svc_ln_adjmt_grp_cd_3, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_3, serviceline.svcpvt_svc_ln_adjmt_amt_3, serviceline.svcpvt_svc_ln_adjmt_qty_3 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_4, serviceline.svcpvt_svc_ln_adjmt_grp_cd_4, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_4, serviceline.svcpvt_svc_ln_adjmt_amt_4, serviceline.svcpvt_svc_ln_adjmt_qty_4 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_5, serviceline.svcpvt_svc_ln_adjmt_grp_cd_5, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_5, serviceline.svcpvt_svc_ln_adjmt_amt_5, serviceline.svcpvt_svc_ln_adjmt_qty_5 )
            ))[x.AdjSvcLnGrp][4]                                      AS  svcpvt_svc_ln_adjmt_qty
FROM veradigm_era_serviceline_pivot_pre serviceline
 CROSS JOIN (SELECT EXPLODE(ARRAY(0, 1, 2, 3, 4)) AS AdjSvcLnGrp) x 
WHERE 
        (densify_2d_array(ARRAY(
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_1, serviceline.svcpvt_svc_ln_adjmt_grp_cd_1, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_1, serviceline.svcpvt_svc_ln_adjmt_amt_1, serviceline.svcpvt_svc_ln_adjmt_qty_1 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_2, serviceline.svcpvt_svc_ln_adjmt_grp_cd_2, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_2, serviceline.svcpvt_svc_ln_adjmt_amt_2, serviceline.svcpvt_svc_ln_adjmt_qty_2 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_3, serviceline.svcpvt_svc_ln_adjmt_grp_cd_3, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_3, serviceline.svcpvt_svc_ln_adjmt_amt_3, serviceline.svcpvt_svc_ln_adjmt_qty_3 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_4, serviceline.svcpvt_svc_ln_adjmt_grp_cd_4, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_4, serviceline.svcpvt_svc_ln_adjmt_amt_4, serviceline.svcpvt_svc_ln_adjmt_qty_4 ),
            ARRAY(serviceline.svcpvt_svc_ln_adjmt_seq_num_5, serviceline.svcpvt_svc_ln_adjmt_grp_cd_5, serviceline.svcpvt_svc_ln_adjmt_rsn_cd_5, serviceline.svcpvt_svc_ln_adjmt_amt_5, serviceline.svcpvt_svc_ln_adjmt_qty_5 )        
            ))[x.AdjSvcLnGrp] != CAST(ARRAY(NULL, NULL, NULL, NULL, NULL) AS ARRAY<STRING>) OR x.AdjSvcLnGrp = 0)
