SELECT
    t.record_id,
    t.claim_id,
    t.hvid,
    t.created,
    t.model_version,
    t.data_set,
    t.data_feed,
    t.data_vendor,
    CAST(NULL AS String) as source_version,
    t.patient_gender,
    CAST(NULL AS String) as patient_age,
    t.patient_year_of_birth,
    t.patient_zip3,
    t.patient_state,
    t.date_service,
    CAST(NULL AS DATE) AS date_written,
    CAST(NULL AS String) as year_of_injury,
    CAST(NULL AS DATE) AS date_authorized,
    CAST(NULL AS String) as time_authorized,
    CAST(NULL AS DATE) AS discharge_date,
    CAST(NULL AS STRING) AS transaction_code_std,
    CAST(NULL AS STRING) AS transaction_code_vendor,
    CAST(NULL AS STRING) AS response_code_std,
    CAST(NULL AS STRING) AS response_code_vendor,
    CAST(NULL AS STRING) AS reject_reason_code_1,
    CAST(NULL AS STRING) AS reject_reason_code_2,
    CAST(NULL AS STRING) AS reject_reason_code_3,
    CAST(NULL AS STRING) AS reject_reason_code_4,
    CAST(NULL AS STRING) AS reject_reason_code_5,
    t.diagnosis_code,
    CAST(NULL AS STRING) AS diagnosis_code_qual,
    t.procedure_code,
    CAST(NULL AS STRING) AS procedure_code_qual,
    t.ndc_code,
    CAST(NULL AS STRING) AS product_service_id,
    CAST(NULL AS STRING) AS product_service_id_qual,
    CAST(NULL AS STRING) AS rx_number,
    CAST(NULL AS STRING) AS rx_number_qual,
    CAST(NULL AS STRING) AS bin_number,
    CAST(NULL AS STRING) AS processor_control_number,
    CAST(NULL AS INT) AS fill_number,
    CAST(NULL AS STRING) AS refill_auth_amount,
    t.dispensed_quantity,
    CAST(NULL AS STRING) AS unit_of_measure,
    CAST(NULL AS INT) AS days_supply,
    CAST(NULL AS STRING) AS pharmacy_npi,
    CAST(NULL AS STRING) AS prov_dispensing_npi,
    CAST(NULL AS STRING) AS payer_id,
    CAST(NULL AS STRING) AS payer_id_qual,
    t.payer_name,
    CAST(NULL AS STRING) AS payer_parent_name,
    CAST(NULL AS STRING) AS payer_org_name,
    CAST(NULL AS STRING) AS payer_plan_id,
    CAST(NULL AS STRING) AS payer_plan_name,
    CAST(NULL AS STRING) AS payer_type,
    CAST(NULL AS STRING) AS compound_code,
    CAST(NULL AS STRING) AS unit_dose_indicator,
    CAST(NULL AS STRING) AS dispensed_as_written,
    CAST(NULL AS STRING) AS prescription_origin,
    CAST(NULL AS STRING) AS submission_clarification,
    CAST(NULL AS STRING) AS orig_prescribed_product_service_code,
    CAST(NULL AS STRING) AS orig_prescribed_product_service_code_qual,
    CAST(NULL AS STRING) AS orig_prescribed_quantity,
    CAST(NULL AS STRING) AS prior_auth_type_code,
    CAST(NULL AS STRING) AS level_of_service,
    CAST(NULL AS STRING) AS reason_for_service,
    CAST(NULL AS STRING) AS professional_service_code,
    CAST(NULL AS STRING) AS result_of_service_code,
    CAST(NULL AS STRING) AS prov_prescribing_npi,
    CAST(NULL AS STRING) AS prov_prescribing_tax_id,
    CAST(NULL AS STRING) AS prov_prescribing_dea_id,
    CAST(NULL AS STRING) AS prov_prescribing_ssn,
    CAST(NULL AS STRING) AS prov_prescribing_state_license,
    CAST(NULL AS STRING) AS prov_prescribing_upin,
    CAST(NULL AS STRING) AS prov_prescribing_commercial_id,
    CAST(NULL AS STRING) AS prov_prescribing_name_1,
    CAST(NULL AS STRING) AS prov_prescribing_name_2,
    CAST(NULL AS STRING) AS prov_prescribing_address_1,
    CAST(NULL AS STRING) AS prov_prescribing_address_2,
    CAST(NULL AS STRING) AS prov_prescribing_city,
    CAST(NULL AS STRING) AS prov_prescribing_state,
    CAST(NULL AS STRING) AS prov_prescribing_zip,
    CAST(NULL AS STRING) AS prov_prescribing_std_taxonomy,
    CAST(NULL AS STRING) AS prov_prescribing_vendor_specialty,
    CAST(NULL AS STRING) AS prov_primary_care_npi,
    t.cob_count,
    CAST(NULL AS FLOAT) AS usual_and_customary_charge,
    CAST(NULL AS FLOAT) AS product_selection_attributed,
    CAST(NULL AS FLOAT) AS other_payer_recognized,
    CAST(NULL AS FLOAT) AS periodic_deductible_applied,
    CAST(NULL AS FLOAT) AS periodic_benefit_exceed,
    CAST(NULL AS FLOAT) AS accumulated_deductible,
    CAST(NULL AS FLOAT) AS remaining_deductible,
    CAST(NULL AS FLOAT) AS remaining_benefit,
    CAST(NULL AS FLOAT) AS copay_coinsurance,
    CAST(NULL AS FLOAT) AS basis_of_cost_determination,
    CAST(NULL AS FLOAT) AS submitted_ingredient_cost,
    CAST(NULL AS FLOAT) AS submitted_dispensing_fee,
    CAST(NULL AS FLOAT) AS submitted_incentive,
    t.submitted_gross_due,
    CAST(NULL AS FLOAT) AS submitted_professional_service_fee,
    CAST(NULL AS FLOAT) AS submitted_patient_pay,
    CAST(NULL AS FLOAT) AS submitted_other_claimed_qual,
    CAST(NULL AS FLOAT) AS submitted_other_claimed,
    CAST(NULL AS FLOAT) AS basis_of_reimbursement_determination,
    CAST(NULL AS FLOAT) AS paid_ingredient_cost,
    CAST(NULL AS FLOAT) AS paid_dispensing_fee,
    CAST(NULL AS FLOAT) AS paid_incentive,
    CAST(NULL AS FLOAT) AS paid_gross_due,
    CAST(NULL AS FLOAT) AS paid_professional_service_fee,
    CAST(NULL AS FLOAT) AS paid_patient_pay,
    CAST(NULL AS FLOAT) AS paid_other_claimed_qual,
    CAST(NULL AS FLOAT) AS paid_other_claimed,
    CAST(NULL AS STRING) AS tax_exempt_indicator,
    CAST(NULL AS STRING) AS coupon_type,
    CAST(NULL AS STRING) AS coupon_number,
    CAST(NULL AS FLOAT) AS coupon_value,
    CAST(NULL AS STRING) AS pharmacy_other_id,
    CAST(NULL AS STRING) AS pharmacy_other_qual,
    t.pharmacy_postal_code,
    CAST(NULL AS STRING) AS prov_dispensing_id,
    CAST(NULL AS STRING) AS prov_dispensing_qual,
    CAST(NULL AS STRING) AS prov_prescribing_id,
    CAST(NULL AS STRING) AS prov_prescribing_qual,
    CAST(NULL AS STRING) AS prov_primary_care_id,
    CAST(NULL AS STRING) AS prov_primary_care_qual,
    CAST(NULL AS STRING) AS other_payer_coverage_type,
    CAST(NULL AS STRING) AS other_payer_coverage_id,
    CAST(NULL AS STRING) AS other_payer_coverage_qual,
    CAST(NULL AS DATE) AS other_payer_date,
    CAST(NULL AS STRING) AS other_payer_coverage_code,
    CAST(NULL AS STRING) AS logical_delete_reason,
    t.part_provider,
    t.part_best_date
FROM mckesson_macro_helix_rx_norm_cf t
