from spark.helpers.source_table import SourceTable

TABLE_CONF = {
    'factallergy': SourceTable(
        'csv',
        separator='|',
        columns=[
            'allergenid',
            'allergyattributeid',
            'allergycategoryid',
            'allergyreactionid',
            'clientid',
            'duration',
            'facilityid',
            'factallergyid',
            'onsetdateid',
            'onsetdatetime',
            'residentid',
            'organizationid'
        ]
    ),
    'factcensus': SourceTable(
        'csv',
        separator='|',
        columns=[
            'censusactionid',
            'censuseffectivedateid',
            'censuseffectivedatetime',
            'censusstatusid',
            'clientid',
            'dischargestatusid',
            'facilityid',
            'factcensusid',
            'fromtoextfacilityid',
            'fromtotypeid',
            'hospitalstayfromdateid',
            'hospitalstayfromdatetime',
            'hospitalstaytodateid',
            'hospitalstaytodatetime',
            'iscensuscompleteind',
            'organizationid',
            'payerid',
            'residentid',
            'transferoutcomeid',
            'transferreasonid',
            'transferstaffid'
        ]
    ),
    'factcareprofile': SourceTable(
        'csv',
        separator='|',
        columns=[
            'careprofilequestionid',
            'clientid',
            'facilityid',
            'factcareprofileid',
            'organizationid',
            'residentid'
        ]
    ),
    'dimallergyattribute': SourceTable(
        'csv',
        separator='|',
        columns=[
            'allergyattributeid',
            'allergyseverity',
            'allergystatus',
            'allergytype'
        ]
    ),
    'dimallergycategory': SourceTable(
        'csv',
        separator='|',
        columns=[
            'allergycategory',
            'allergycategoryid',
            'allergysubcategory'
        ]
    ),
    'dimallergen': SourceTable(
        'csv',
        separator='|',
        columns=[
            'allergen',
            'allergenid'
        ]
    ),
    'dimallergyreaction': SourceTable(
        'csv',
        separator='|',
        columns=[
            'allergyreaction',
            'allergyreactionid',
            'allergysubreaction'
        ]
    ),
    'dimcareprofilequestion': SourceTable(
        'csv',
        separator='|',
        columns=[
            'careprofilequestionid',
            'category',
            'question',
            'response'
        ]
    ),
    'dimdiagnosisclassification': SourceTable(
        'csv',
        separator='|',
        columns=[
            'diagnosisclassification',
            'diagnosisclassificationid'
        ]
    ),
    'dimdiagnosis': SourceTable(
        'csv',
        separator='|',
        columns=[
            'clinicalconditioncategory',
            'clinicalconditioncategorydesc',
            'clinicalconditionlevel1',
            'clinicalconditionlevel1desc',
            'clinicalconditionlevel2',
            'clinicalconditionlevel2desc',
            'diagnosisid',
            'icdcode',
            'icddesc',
            'mdsdiagnosisgroup',
            'mdsdiagnosisgroupdesc'
        ]
    ),
    'dimdiagnosisrank': SourceTable(
        'csv',
        separator='|',
        columns=[
            'diagnosisrank',
            'diagnosisrankid'
        ]
    ),
    'dimdrug': SourceTable(
        'csv',
        separator='|',
        columns=[
            'controlsubstancecode',
            'ddid',
            'drugbasename',
            'drugclass',
            'drugform',
            'druggroup',
            'drugid',
            'drugname',
            'drugstrength',
            'drugsubclass',
            'form',
            'gpi',
            'lvl1druggroup',
            'lvl2drugclass',
            'lvl3drugsubclass',
            'lvl4drugbasename',
            'lvl5drugname',
            'lvl6drugform',
            'lvl7drugstrength',
            'narcotic',
            'pnid',
            'strength',
            'strengthunit'
        ]
    ),
    'factdiagnosis': SourceTable(
        'csv',
        separator='|',
        columns=[
            'clientid',
            'diagnosisclassificationid',
            'diagnosisid',
            'diagnosisrankid',
            'facilityid',
            'factdiagnosisid',
            'isadmissiondiagnosisind',
            'isprincipaldiagnosisind',
            'onsetdateid',
            'onsetdatetime',
            'organizationid',
            'residentid',
            'resolveddateid',
            'resolveddatetime'
        ]
    ),
    'dimimmunization': SourceTable(
        'csv',
        separator='|',
        columns=[
            'immunization',
            'immunizationid'
        ]
    ),
    'dimlabreportstatus': SourceTable(
        'csv',
        separator='|',
        columns=[
            'labreportstatusid',
            'statuscode',
            'statusdescription'
        ]
    ),
    'dimlabtest': SourceTable(
        'csv',
        separator='|',
        columns=[
            'categorycode',
            'categorydescription',
            'iscategoryactiveind',
            'istestactiveind',
            'labtestid',
            'loinccode',
            'testdescription'
        ]
    ),
    'dimobservation': SourceTable(
        'csv',
        separator='|',
        columns=[
            'imperialuom',
            'metricuom',
            'observation',
            'observationid',
            'observationshort'
        ]
    ),
    'dimorganization': SourceTable(
        'csv',
        separator='|',
        columns=[
            'countrycode',
            'organization',
            'organizationcode',
            'organizationgroup',
            'organizationid',
            'organizationtype'
        ]
    ),
    'dimlabresultuom': SourceTable(
        'csv',
        separator='|',
        columns=[
            'labresultuomid',
            'resultuom'
        ]
    ),
    'dimlabtestabnormality': SourceTable(
        'csv',
        separator='|',
        columns=[
            'abnormalitycode',
            'abnormalitydescription',
            'isactiveind',
            'labtestabnormalityid'
        ]
    ),
    'dimlabtestcondition': SourceTable(
        'csv',
        separator='|',
        columns=[
            'conditioncode',
            'conditiondescription',
            'isactiveind',
            'labtestconditionid'
        ]
    ),
    'dimvaccine': SourceTable(
        'csv',
        separator='|',
        columns=[
            'vaccine',
            'vaccinecode',
            'vaccineid',
            'vaccineshort',
            'vaccinestatus'
        ]
    ),
    'factimmunization': SourceTable(
        'csv',
        separator='|',
        columns=[
            'clientid',
            'consent',
            'consentdateid',
            'consentdatetime',
            'facilityid',
            'factimmunizationid',
            'immunizationdateid',
            'immunizationdatetime',
            'immunizationid',
            'organizationid',
            'residentid',
            'vaccineid'
        ]
    ),
    'factlabtest': SourceTable(
        'csv',
        separator='|',
        columns=[
            'clientid',
            'facilityid',
            'factlabtestid',
            'labreportseverityid',
            'labreportstatusid',
            'labresultuomid',
            'labtestabnormalityid',
            'labtestconditionid',
            'labtestid',
            'refrange',
            'reporteddate',
            'reporteddateid',
            'reportinglabextfactid',
            'residentid',
            'resultdatetime',
            'resultdatetimeid',
            'resultvalue',
            'specimencollectiondate',
            'specimencollectiondateid'
        ]
    ),
    'factmedicationorder': SourceTable(
        'csv',
        separator='|',
        columns=[
            'clientid',
            'drugid',
            'facilityid',
            'factmedicationorderid',
            'ordercompleteddateid',
            'ordercompleteddatetime',
            'orderdiscontinueddateid',
            'orderdiscontinueddatetime',
            'orderenddateid',
            'orderenddatetime',
            'orderholddateid',
            'orderholddatetime',
            'orderholdenddateid',
            'orderholdenddatetime',
            'orderstartdateid',
            'orderstartdatetime',
            'organizationid',
            'pharmacyfacilityid',
            'physicianstaffid',
            'residentid',
            'routeofadminid',
            'scheduleenddateid',
            'scheduleenddatetime',
            'schedulestartdateid',
            'schedulestartdatetime'
        ]
    ),
    'factobservation': SourceTable(
        'csv',
        separator='|',
        columns=[
            'factobservationid',
            'organizationid',
            'facilityid',
            'clientid',
            'residentid',
            'observationmethodid',
            'observationid',
            'observationdatetime',
            'observationdateid',
            'observationsystolic',
            'observationdiastolic',
            'observationvaluemetric',
            'observationvalueimperial'
        ]
    ),
    'factvisit': SourceTable(
        'csv',
        separator='|',
        columns=[
            'admitdateid',
            'admitdatetime',
            'admitfactcensusid',
            'admitfromextfacilityid',
            'admitpayerid',
            'clientid',
            'dischargedateid',
            'dischargedatetime',
            'dischargefactcensusid',
            'dischargestaffid',
            'dischargetoextfacilityid',
            'dischargetransferoutcomeid',
            'dischargetransferreasonid',
            'facilityid',
            'factvisitid',
            'isreadmitind',
            'isvisitcompletedind',
            'latestpayerid',
            'lengthofstay',
            'organizationid',
            'residentid',
            'transferstaffid'
        ]
    )
}
