SELECT
    claim_id,
    hvid,
    created,
    model_version,
    data_set,
    data_feed,
    data_vendor,
    patient_gender,
    patient_age,
    patient_year_of_birth,
    patient_zip3,
    patient_state,
    date_service,
    date_specimen,
    date_report,
    time_report,
    loinc_code,
    lab_id,
    test_id,
    test_number,
    test_battery_local_id,
    test_battery_std_id,
    test_battery_name,
    test_ordered_local_id,
    test_ordered_std_id,
    test_ordered_name,
    result_id,
    result,
    result_name,
    result_unit_of_measure,
    result_desc,
    result_comments,
    ref_range_alpha,
    abnormal_flag,
    fasting_status,
    diagnosis_code,
    diagnosis_code_qual,
    procedure_code,
    procedure_code_qual,
    ordering_npi,
    payer_id,
    payer_id_qual,
    payer_name,
    ordering_name,
    ordering_market_type,
    ordering_specialty,
    ordering_vendor_id,
    ordering_state_license,
    ordering_upin,
    ordering_address_1,
    ordering_address_2,
    ordering_city,
    ordering_state,
    ordering_zip,
    logical_delete_reason,
    vendor_record_id,
    part_provider,
    part_best_date
FROM
labtest_quest_rinse_pre_final

GROUP BY  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
         11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
         21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
         31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
         51, 52, 53, 54, 55, 56, 57, 58
