
CREATE TABLE pitney_bowes_locations (
  pb_id                 CHAR(10), 
  stable_id             CHAR(12),
  name                  VARCHAR(128),
  brandname             VARCHAR(128),
  street_1              VARCHAR(64),
  street_2              VARCHAR(64), 
  city                  VARCHAR(32),
  district              VARCHAR(24),
  state_abb             VARCHAR(4),
  state                 VARCHAR(24),
  postcode              VARCHAR(10),
  iso3                  VARCHAR(3),
  country_ac            CHAR(4),
  telephone             VARCHAR(10),
  fax                   VARCHAR(10),
  business_line         VARCHAR(64),
  sic1                  VARCHAR(4),
  sic2                  VARCHAR(4),
  mi_code               VARCHAR(8),
  cat_alias             VARCHAR(128),
  sub_cat_alias         VARCHAR(64),
  longitude             NUMERIC(18,16), 
  latitude              NUMERIC(18,16),
  georesult             VARCHAR(10),
  confidence_code       VARCHAR(10),
  employee_here         INTEGER,
  employee_count        INTEGER
);
