SELECT
	claim_number,
	record_type,	---added for DHC
	line_number,
	service_from,
	service_to,
	place_service,
	procedure,
	procedure_qual,
	procedure_modifier_1,
	procedure_modifier_2,
	procedure_modifier_3,
	procedure_modifier_4,
	line_charge,
	line_allowed,
	units,
	revenue_code,
	diagnosis_pointer_1,
	diagnosis_pointer_2,
	diagnosis_pointer_3,
	diagnosis_pointer_4,
	diagnosis_pointer_5,
	diagnosis_pointer_6,
	diagnosis_pointer_7,
	diagnosis_pointer_8,
	ndc,            
	emergency,      ---added for DHC
	MAX(SPLIT(input_file_name, '/')[SIZE(SPLIT(input_file_name, '/')) - 1])              AS data_set
 FROM lines
GROUP BY
	claim_number,
	record_type,        ---added for DHC
	line_number,
	service_from,
	service_to,
	place_service,
	procedure,
	procedure_qual,
	procedure_modifier_1,
	procedure_modifier_2,
	procedure_modifier_3,
	procedure_modifier_4,
	line_charge,
	line_allowed,
	units,
	revenue_code,
	diagnosis_pointer_1,
	diagnosis_pointer_2,
	diagnosis_pointer_3,
	diagnosis_pointer_4,
	diagnosis_pointer_5,
	diagnosis_pointer_6,
	diagnosis_pointer_7,
	diagnosis_pointer_8,
	ndc,               
	emergency           ---added for DHC
