"""
guardant health labtest source schema
"""
from pyspark.sql.types import StructType, StructField, StringType

schema = StructType([
    StructField('row_id', StringType(), True),
    StructField('variant_type', StringType(), True),
    StructField('gene', StringType(), True),
    StructField('chromosome', StringType(), True),
    StructField('exon', StringType(), True),
    StructField('mutation_aa', StringType(), True),
    StructField('mutation_nt', StringType(), True),
    StructField('maf_percentage', StringType(), True),
    StructField('ref_seq_transcript_id', StringType(), True),
    StructField('genomic_position', StringType(), True),
    StructField('splice_effect', StringType(), True),
    StructField('cdna', StringType(), True),
    StructField('indel_type', StringType(), True),
    StructField('fusion_gene_n', StringType(), True),
    StructField('fusion_position_a', StringType(), True),
    StructField('fusion_position_b', StringType(), True),
    StructField('fusion_direction_a', StringType(), True),
    StructField('fusion_direction_b', StringType(), True),
    StructField('fusion_downstram_gene', StringType(), True),
    StructField('cnv_copy_number', StringType(), True),
    StructField('cosmic_id', StringType(), True),
    StructField('dbsnp_id', StringType(), True),
    StructField('cancer_type', StringType(), True),
    StructField('report_date', StringType(), True),
    StructField('physician_first_name', StringType(), True),
    StructField('physician_last_name', StringType(), True),
    StructField('physician_practice_name', StringType(), True),
    StructField('physician_street_address_1', StringType(), True),
    StructField('physician_street_address_2', StringType(), True),
    StructField('physician_zipcode', StringType(), True),
    StructField('physician_city', StringType(), True),
    StructField('physician_state', StringType(), True),
    StructField('physician_country', StringType(), True),
    StructField('patient_first_name', StringType(), True),
    StructField('patient_last_name', StringType(), True),
    StructField('patient_dob', StringType(), True),
    StructField('patient_gender', StringType(), True),
    StructField('patient_address_1', StringType(), True),
    StructField('patient_address_2', StringType(), True),
    StructField('patient_city', StringType(), True),
    StructField('patient_state', StringType(), True),
    StructField('patient_zip', StringType(), True),
    StructField('patient_country', StringType(), True),
    StructField('hvjoinkey', StringType(), True)
])
