SELECT
    hvid                 ,
    created              ,
    model_version        ,
    data_set             ,
    data_feed            ,
    data_vendor          ,
    patient_age          ,
    patient_year_of_birth,
    source_record_date   ,
    patient_zip3         ,
    patient_state        ,
    patient_gender       ,
    date_start           ,
    date_end             ,
    benefit_type         ,
    payer_type           ,
    payer_grp_txt        ,
    part_provider        ,
    part_best_date
FROM inovalon_enr2_pre_norm_final txn
GROUP BY
    hvid                 ,
    created              ,
    model_version        ,
    data_set             ,
    data_feed            ,
    data_vendor          ,
    patient_age          ,
    patient_year_of_birth,
    source_record_date   ,
    patient_zip3         ,
    patient_state        ,
    patient_gender       ,
    date_start           ,
    date_end             ,
    benefit_type         ,
    payer_type           ,
    payer_grp_txt        ,
    part_provider        ,
    part_best_date
