DROP VIEW IF EXISTS dw.hvm_emr_enc;
CREATE VIEW dw.hvm_emr_enc (
        row_id,
        hv_enc_id,
        crt_dt,
        mdl_vrsn_num,
        data_set_nm,
        src_vrsn_id,
        hvm_vdr_id,
        hvm_vdr_feed_id,
        vdr_org_id,
        vdr_enc_id,
        vdr_enc_id_qual,
        vdr_alt_enc_id,
        vdr_alt_enc_id_qual,
        hvid,
        ptnt_birth_yr,
        ptnt_age_num,
        ptnt_lvg_flg,
        ptnt_dth_dt,
        ptnt_gender_cd,
        ptnt_state_cd,
        ptnt_zip3_cd,
        enc_start_dt,
        enc_end_dt,
        enc_vst_typ_cd,
        enc_rndrg_fclty_taxnmy_id,
        enc_rndrg_fclty_speclty_id,
        enc_rndrg_fclty_state_cd,
        enc_rndrg_fclty_zip_cd,
        enc_rndrg_prov_taxnmy_id,
        enc_rndrg_prov_speclty_id,
        enc_rndrg_prov_state_cd,
        enc_rndrg_prov_zip_cd,
        enc_rfrg_prov_taxnmy_id,
        enc_rfrg_prov_speclty_id,
        enc_rfrg_prov_state_cd,
        enc_rfrg_prov_zip_cd,
        enc_typ_cd,
        enc_typ_cd_qual,
        enc_typ_nm,
        enc_desc,
        enc_pos_cd,
        data_captr_dt,
        rec_stat_cd,
        part_hvm_vdr_feed_id,
        part_mth,
        prmy_src_tbl_nm
        ) AS SELECT
    row_id,
    hv_enc_id,
    crt_dt,
    mdl_vrsn_num,
    data_set_nm,
    src_vrsn_id,
    hvm_vdr_id,
    hvm_vdr_feed_id,
    vdr_org_id,
    vdr_enc_id,
    vdr_enc_id_qual,
    vdr_alt_enc_id,
    vdr_alt_enc_id_qual,
    hvid,
    ptnt_birth_yr,
    ptnt_age_num,
    ptnt_lvg_flg,
    ptnt_dth_dt,
    ptnt_gender_cd,
    ptnt_state_cd,
    ptnt_zip3_cd,
    enc_start_dt,
    enc_end_dt,
    enc_vst_typ_cd,
    COALESCE(enc_rndrg_fclty_nucc_taxnmy_cd, enc_rndrg_fclty_alt_taxnmy_id),
    COALESCE(enc_rndrg_fclty_mdcr_speclty_cd, enc_rndrg_fclty_alt_speclty_id),
    enc_rndrg_fclty_state_cd,
    enc_rndrg_fclty_zip_cd,
    COALESCE(enc_rndrg_prov_nucc_taxnmy_cd, enc_rndrg_prov_alt_taxnmy_id),
    COALESCE(enc_rndrg_prov_mdcr_speclty_cd, enc_rndrg_prov_alt_speclty_id),
    enc_rndrg_prov_state_cd,
    enc_rndrg_prov_zip_cd,
    COALESCE(enc_rfrg_prov_nucc_taxnmy_cd, enc_rfrg_prov_alt_taxnmy_id),
    COALESCE(enc_rfrg_prov_mdcr_speclty_cd, enc_rfrg_prov_alt_speclty_id),
    enc_rfrg_prov_state_cd,
    enc_rfrg_prov_zip_cd,
    enc_typ_cd,
    enc_typ_cd_qual,
    enc_typ_nm,
    enc_desc,
    enc_pos_cd,
    data_captr_dt,
    rec_stat_cd,
    part_hvm_vdr_feed_id,
    part_mth,
    prmy_src_tbl_nm
FROM dw.emr_enc
    ;
