DROP TABLE IF EXISTS {table_name};
CREATE TABLE {table_name} (
        row_id                                 bigint,
        hv_lab_ord_id                          string,
        crt_dt                                 date,
        mdl_vrsn_num                           string,
        data_set_nm                            string,
        src_vrsn_id                            string,
        hvm_vdr_id                             int,
        hvm_vdr_feed_id                        int,
        vdr_org_id                             string,
        vdr_lab_ord_id                         string,
        vdr_lab_ord_id_qual                    string,
        hvid                                   string,
        ptnt_birth_yr                          int,
        ptnt_age_num                           string,
        ptnt_lvg_flg                           string,
        ptnt_dth_dt                            date,
        ptnt_gender_cd                         string,
        ptnt_state_cd                          string,
        ptnt_zip3_cd                           string,
        hv_enc_id                              string,
        enc_dt                                 date,
        lab_ord_dt                             date,
        lab_ord_test_schedd_dt                 date,
        lab_ord_smpl_collctn_dt                date,
        lab_ord_ordg_prov_npi                  string,
        lab_ord_ordg_prov_vdr_id               string,
        lab_ord_ordg_prov_vdr_id_qual          string,
        lab_ord_ordg_prov_alt_id               string,
        lab_ord_ordg_prov_alt_id_qual          string,
        lab_ord_ordg_prov_tax_id               string,
        lab_ord_ordg_prov_dea_id               string,
        lab_ord_ordg_prov_state_lic_id         string,
        lab_ord_ordg_prov_comrcl_id            string,
        lab_ord_ordg_prov_upin                 string,
        lab_ord_ordg_prov_ssn                  string,
        lab_ord_ordg_prov_nucc_taxnmy_cd       string,
        lab_ord_ordg_prov_alt_taxnmy_id        string,
        lab_ord_ordg_prov_alt_taxnmy_id_qual   string,
        lab_ord_ordg_prov_mdcr_speclty_cd      string,
        lab_ord_ordg_prov_alt_speclty_id       string,
        lab_ord_ordg_prov_alt_speclty_id_qual  string,
        lab_ord_ordg_prov_fclty_nm             string,
        lab_ord_ordg_prov_frst_nm              string,
        lab_ord_ordg_prov_last_nm              string,
        lab_ord_ordg_prov_addr_1_txt           string,
        lab_ord_ordg_prov_addr_2_txt           string,
        lab_ord_ordg_prov_state_cd             string,
        lab_ord_ordg_prov_zip_cd               string,
        lab_ord_loinc_cd                       string,
        lab_ord_snomed_cd                      string,
        lab_ord_alt_cd                         string,
        lab_ord_alt_cd_qual                    string,
        lab_ord_test_nm                        string,
        lab_ord_panel_nm                       string,
        lab_ord_diag_cd                        string,
        lab_ord_diag_cd_qual                   string,
        data_captr_dt                          date,
        rec_stat_cd                            string,
        prmy_src_tbl_nm                        string
        )
    {properties}
    ;

