from pyspark.sql.types import *
from spark.common.schema import Schema
from spark.common.utility.output_type import DataType

schema_v4 = StructType([
        StructField('row_id', LongType(), True),
        StructField('hv_vit_sign_id', StringType(), True),
        StructField('crt_dt', DateType(), True),
        StructField('mdl_vrsn_num', StringType(), True),
        StructField('data_set_nm', StringType(), True),
        StructField('src_vrsn_id', StringType(), True),
        StructField('hvm_vdr_id', IntegerType(), True),
        StructField('hvm_vdr_feed_id', IntegerType(), True),
        StructField('vdr_org_id', StringType(), True),
        StructField('vdr_vit_sign_id', StringType(), True),
        StructField('vdr_vit_sign_id_qual', StringType(), True),
        StructField('hvid', StringType(), True),
        StructField('ptnt_birth_yr', IntegerType(), True),
        StructField('ptnt_age_num', StringType(), True),
        StructField('ptnt_lvg_flg', StringType(), True),
        StructField('ptnt_dth_dt', DateType(), True),
        StructField('ptnt_gender_cd', StringType(), True),
        StructField('ptnt_state_cd', StringType(), True),
        StructField('ptnt_zip3_cd', StringType(), True),
        StructField('hv_enc_id', StringType(), True),
        StructField('enc_dt', DateType(), True),
        StructField('vit_sign_dt', DateType(), True),
        StructField('vit_sign_last_msrmt_dt', DateType(), True),
        StructField('vit_sign_rndrg_fclty_npi', StringType(), True),
        StructField('vit_sign_rndrg_fclty_vdr_id', StringType(), True),
        StructField('vit_sign_rndrg_fclty_vdr_id_qual', StringType(), True),
        StructField('vit_sign_rndrg_fclty_alt_id', StringType(), True),
        StructField('vit_sign_rndrg_fclty_alt_id_qual', StringType(), True),
        StructField('vit_sign_rndrg_fclty_tax_id', StringType(), True),
        StructField('vit_sign_rndrg_fclty_dea_id', StringType(), True),
        StructField('vit_sign_rndrg_fclty_state_lic_id', StringType(), True),
        StructField('vit_sign_rndrg_fclty_comrcl_id', StringType(), True),
        StructField('vit_sign_rndrg_fclty_nucc_taxnmy_cd', StringType(), True),
        StructField('vit_sign_rndrg_fclty_alt_taxnmy_id', StringType(), True),
        StructField('vit_sign_rndrg_fclty_alt_taxnmy_id_qual', StringType(), True),
        StructField('vit_sign_rndrg_fclty_mdcr_speclty_cd', StringType(), True),
        StructField('vit_sign_rndrg_fclty_alt_speclty_id', StringType(), True),
        StructField('vit_sign_rndrg_fclty_alt_speclty_id_qual', StringType(), True),
        StructField('vit_sign_rndrg_fclty_nm', StringType(), True),
        StructField('vit_sign_rndrg_fclty_addr_1_txt', StringType(), True),
        StructField('vit_sign_rndrg_fclty_addr_2_txt', StringType(), True),
        StructField('vit_sign_rndrg_fclty_state_cd', StringType(), True),
        StructField('vit_sign_rndrg_fclty_zip_cd', StringType(), True),
        StructField('vit_sign_rndrg_prov_npi', StringType(), True),
        StructField('vit_sign_rndrg_prov_vdr_id', StringType(), True),
        StructField('vit_sign_rndrg_prov_vdr_id_qual', StringType(), True),
        StructField('vit_sign_rndrg_prov_alt_id', StringType(), True),
        StructField('vit_sign_rndrg_prov_alt_id_qual', StringType(), True),
        StructField('vit_sign_rndrg_prov_tax_id', StringType(), True),
        StructField('vit_sign_rndrg_prov_dea_id', StringType(), True),
        StructField('vit_sign_rndrg_prov_state_lic_id', StringType(), True),
        StructField('vit_sign_rndrg_prov_comrcl_id', StringType(), True),
        StructField('vit_sign_rndrg_prov_upin', StringType(), True),
        StructField('vit_sign_rndrg_prov_ssn', StringType(), True),
        StructField('vit_sign_rndrg_prov_nucc_taxnmy_cd', StringType(), True),
        StructField('vit_sign_rndrg_prov_alt_taxnmy_id', StringType(), True),
        StructField('vit_sign_rndrg_prov_alt_taxnmy_id_qual', StringType(), True),
        StructField('vit_sign_rndrg_prov_mdcr_speclty_cd', StringType(), True),
        StructField('vit_sign_rndrg_prov_alt_speclty_id', StringType(), True),
        StructField('vit_sign_rndrg_prov_alt_speclty_id_qual', StringType(), True),
        StructField('vit_sign_rndrg_prov_frst_nm', StringType(), True),
        StructField('vit_sign_rndrg_prov_last_nm', StringType(), True),
        StructField('vit_sign_rndrg_prov_addr_1_txt', StringType(), True),
        StructField('vit_sign_rndrg_prov_addr_2_txt', StringType(), True),
        StructField('vit_sign_rndrg_prov_state_cd', StringType(), True),
        StructField('vit_sign_rndrg_prov_zip_cd', StringType(), True),
        StructField('vit_sign_typ_cd', StringType(), True),
        StructField('vit_sign_typ_cd_qual', StringType(), True),
        StructField('vit_sign_typ_nm', StringType(), True),
        StructField('vit_sign_typ_desc', StringType(), True),
        StructField('vit_sign_snomed_cd', StringType(), True),
        StructField('vit_sign_msrmt', StringType(), True),
        StructField('vit_sign_uom', StringType(), True),
        StructField('vit_sign_qual', StringType(), True),
        StructField('vit_sign_abnorm_flg', StringType(), True),
        StructField('vit_sign_norm_min_msrmt', StringType(), True),
        StructField('vit_sign_norm_max_msrmt', StringType(), True),
        StructField('data_captr_dt', DateType(), True),
        StructField('rec_stat_cd', StringType(), True),
        StructField('prmy_src_tbl_nm', StringType(), True)
])

schema_v6 = StructType([
    StructField('row_id', LongType(), True),
    StructField('hv_vit_sign_id', StringType(), True),
    StructField('crt_dt', DateType(), True),
    StructField('mdl_vrsn_num', StringType(), True),
    StructField('data_set_nm', StringType(), True),
    StructField('src_vrsn_id', StringType(), True),
    StructField('hvm_vdr_id', IntegerType(), True),
    StructField('hvm_vdr_feed_id', IntegerType(), True),
    StructField('vdr_org_id', StringType(), True),
    StructField('vdr_vit_sign_id', StringType(), True),
    StructField('vdr_vit_sign_id_qual', StringType(), True),
    StructField('vdr_alt_vit_sign_id', StringType(), True),
    StructField('vdr_alt_vit_sign_id_qual', StringType(), True),
    StructField('hvid', StringType(), True),
    StructField('ptnt_birth_yr', IntegerType(), True),
    StructField('ptnt_age_num', StringType(), True),
    StructField('ptnt_lvg_flg', StringType(), True),
    StructField('ptnt_dth_dt', DateType(), True),
    StructField('ptnt_gender_cd', StringType(), True),
    StructField('ptnt_state_cd', StringType(), True),
    StructField('ptnt_zip3_cd', StringType(), True),
    StructField('hv_enc_id', StringType(), True),
    StructField('enc_dt', DateType(), True),
    StructField('vit_sign_dt', DateType(), True),
    StructField('vit_sign_last_msrmt_dt', DateType(), True),
    StructField('vit_sign_rndrg_fclty_npi', StringType(), True),
    StructField('vit_sign_rndrg_fclty_vdr_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_vdr_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_fclty_tax_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_state_lic_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_comrcl_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_nucc_taxnmy_cd', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_taxnmy_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_taxnmy_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_fclty_mdcr_speclty_cd', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_speclty_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_speclty_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_fclty_nm', StringType(), True),
    StructField('vit_sign_rndrg_fclty_addr_1_txt', StringType(), True),
    StructField('vit_sign_rndrg_fclty_addr_2_txt', StringType(), True),
    StructField('vit_sign_rndrg_fclty_state_cd', StringType(), True),
    StructField('vit_sign_rndrg_fclty_zip_cd', StringType(), True),
    StructField('vit_sign_rndrg_prov_npi', StringType(), True),
    StructField('vit_sign_rndrg_prov_vdr_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_vdr_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_prov_tax_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_state_lic_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_comrcl_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_upin', StringType(), True),
    StructField('vit_sign_rndrg_prov_ssn', StringType(), True),
    StructField('vit_sign_rndrg_prov_nucc_taxnmy_cd', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_taxnmy_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_taxnmy_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_prov_mdcr_speclty_cd', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_speclty_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_speclty_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_prov_frst_nm', StringType(), True),
    StructField('vit_sign_rndrg_prov_last_nm', StringType(), True),
    StructField('vit_sign_rndrg_prov_addr_1_txt', StringType(), True),
    StructField('vit_sign_rndrg_prov_addr_2_txt', StringType(), True),
    StructField('vit_sign_rndrg_prov_state_cd', StringType(), True),
    StructField('vit_sign_rndrg_prov_zip_cd', StringType(), True),
    StructField('vit_sign_typ_cd', StringType(), True),
    StructField('vit_sign_typ_cd_qual', StringType(), True),
    StructField('vit_sign_typ_nm', StringType(), True),
    StructField('vit_sign_typ_desc', StringType(), True),
    StructField('vit_sign_snomed_cd', StringType(), True),
    StructField('vit_sign_msrmt', StringType(), True),
    StructField('vit_sign_uom', StringType(), True),
    StructField('vit_sign_qual', StringType(), True),
    StructField('vit_sign_abnorm_flg', StringType(), True),
    StructField('vit_sign_norm_min_msrmt', StringType(), True),
    StructField('vit_sign_norm_max_msrmt', StringType(), True),
    StructField('data_src_cd', StringType(), True),
    StructField('data_captr_dt', DateType(), True),
    StructField('rec_stat_cd', StringType(), True),
    StructField('prmy_src_tbl_nm', StringType(), True)
])

schema_v7 = StructType([
    StructField('row_id', LongType(), True),
    StructField('hv_vit_sign_id', StringType(), True),
    StructField('crt_dt', DateType(), True),
    StructField('mdl_vrsn_num', StringType(), True),
    StructField('data_set_nm', StringType(), True),
    StructField('src_vrsn_id', StringType(), True),
    StructField('hvm_vdr_id', IntegerType(), True),
    StructField('hvm_vdr_feed_id', IntegerType(), True),
    StructField('vdr_org_id', StringType(), True),
    StructField('vdr_vit_sign_id', StringType(), True),
    StructField('vdr_vit_sign_id_qual', StringType(), True),
    StructField('vdr_alt_vit_sign_id', StringType(), True),
    StructField('vdr_alt_vit_sign_id_qual', StringType(), True),
    StructField('hvid', StringType(), True),
    StructField('ptnt_birth_yr', IntegerType(), True),
    StructField('ptnt_age_num', StringType(), True),
    StructField('ptnt_lvg_flg', StringType(), True),
    StructField('ptnt_dth_dt', DateType(), True),
    StructField('ptnt_gender_cd', StringType(), True),
    StructField('ptnt_state_cd', StringType(), True),
    StructField('ptnt_zip3_cd', StringType(), True),
    StructField('hv_enc_id', StringType(), True),
    StructField('enc_dt', DateType(), True),
    StructField('vit_sign_dt', DateType(), True),
    StructField('vit_sign_last_msrmt_dt', DateType(), True),
    StructField('vit_sign_rndrg_fclty_npi', StringType(), True),
    StructField('vit_sign_rndrg_fclty_vdr_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_vdr_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_fclty_tax_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_dea_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_state_lic_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_comrcl_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_nucc_taxnmy_cd', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_taxnmy_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_taxnmy_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_fclty_mdcr_speclty_cd', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_speclty_id', StringType(), True),
    StructField('vit_sign_rndrg_fclty_alt_speclty_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_fclty_nm', StringType(), True),
    StructField('vit_sign_rndrg_fclty_addr_1_txt', StringType(), True),
    StructField('vit_sign_rndrg_fclty_addr_2_txt', StringType(), True),
    StructField('vit_sign_rndrg_fclty_state_cd', StringType(), True),
    StructField('vit_sign_rndrg_fclty_zip_cd', StringType(), True),
    StructField('vit_sign_rndrg_prov_npi', StringType(), True),
    StructField('vit_sign_rndrg_prov_vdr_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_vdr_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_prov_tax_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_dea_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_state_lic_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_comrcl_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_upin', StringType(), True),
    StructField('vit_sign_rndrg_prov_ssn', StringType(), True),
    StructField('vit_sign_rndrg_prov_nucc_taxnmy_cd', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_taxnmy_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_taxnmy_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_prov_mdcr_speclty_cd', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_speclty_id', StringType(), True),
    StructField('vit_sign_rndrg_prov_alt_speclty_id_qual', StringType(), True),
    StructField('vit_sign_rndrg_prov_frst_nm', StringType(), True),
    StructField('vit_sign_rndrg_prov_last_nm', StringType(), True),
    StructField('vit_sign_rndrg_prov_addr_1_txt', StringType(), True),
    StructField('vit_sign_rndrg_prov_addr_2_txt', StringType(), True),
    StructField('vit_sign_rndrg_prov_state_cd', StringType(), True),
    StructField('vit_sign_rndrg_prov_zip_cd', StringType(), True),
    StructField('vit_sign_typ_cd', StringType(), True),
    StructField('vit_sign_typ_cd_qual', StringType(), True),
    StructField('vit_sign_typ_nm', StringType(), True),
    StructField('vit_sign_typ_desc', StringType(), True),
    StructField('vit_sign_snomed_cd', StringType(), True),
    StructField('vit_sign_msrmt', StringType(), True),
    StructField('vit_sign_uom', StringType(), True),
    StructField('vit_sign_qual', StringType(), True),
    StructField('vit_sign_abnorm_flg', StringType(), True),
    StructField('vit_sign_norm_min_msrmt', StringType(), True),
    StructField('vit_sign_norm_max_msrmt', StringType(), True),
    StructField('vit_sign_stat_cd', StringType(), True),
    StructField('vit_sign_stat_cd_qual', StringType(), True),
    StructField('data_src_cd', StringType(), True),
    StructField('data_captr_dt', DateType(), True),
    StructField('rec_stat_cd', StringType(), True),
    StructField('prmy_src_tbl_nm', StringType(), True)
])


data_type = DataType.EMR
schemas = {
    'schema_v4': Schema(name='schema_v4',
                        schema_structure=schema_v4,
                        distribution_key='row_id',
                        data_type=data_type,
                        provider_partition_column='part_hvm_vdr_feed_id',
                        date_partition_column='part_mth',
                        output_directory=DataType(data_type).value + '/2017-08-23/vital_sign'
                        ),
    'schema_v6': Schema(name='schema_v6',
                        schema_structure=schema_v6,
                        distribution_key='row_id',
                        data_type=data_type,
                        provider_partition_column='part_hvm_vdr_feed_id',
                        date_partition_column='part_mth',
                        output_directory=DataType(data_type).value + '/2018-02-12/vital_sign'
                        ),
    'schema_v7': Schema(name='schema_v7',
                        schema_structure=schema_v7,
                        distribution_key='row_id',
                        data_type=data_type,
                        provider_partition_column='part_hvm_vdr_feed_id',
                        date_partition_column='part_mth',
                        output_directory=DataType(data_type).value + '/2017-08-23/vital_sign'
                        )
}
