--2019-10-30 Allscripts/NextGen asked to sending their EMR
--data to Humana
--SELECT * FROM allscripts_med_claims_1
--UNION
--SELECT * FROM allscripts_med_claims_2
--UNION
--SELECT * FROM allscripts_med_claims_3
--UNION
--SELECT * FROM allscripts_med_claims_4
--UNION
--SELECT * FROM nextgen_med_claims_1
--UNION
--SELECT * FROM nextgen_med_claims_2
--UNION
--SELECT * FROM nextgen_med_claims_3
--UNION
--SELECT * FROM nextgen_med_claims_4
