DROP TABLE IF EXISTS transactions;
CREATE EXTERNAL TABLE transactions (
        creation_date                                   string,
        creation_time                                   string,
        version_number                                  string,
        transaction_code                                string,
        processor_control_number                        string,
        service_provider_id                             string,
        service_provider_id_qualifier                   string,
        date_of_service                                 string,
        date_of_birth                                   string,
        patient_gender_code                             string,
        patient_first_name                              string,
        patient_last_name                               string,
        patient_street_address                          string,
        paitent_city                                    string,
        patient_state                                   string,
        patient_zip                                     string,
        patient_id_qualifier                            string,
        patient_id                                      string,
        provider_id                                     string,
        provider_id_qualifier                           string,
        prescriber_id                                   string,
        primary_care_provider_id                        string,
        prescriber_last_name                            string,
        prescriber_id_qualifier                         string,
        cardholder_id                                   string,
        group_id                                        string,
        patient_relationship_code                       string,
        prescription_service_reference_number           string,
        fill_number                                     string,
        days_supply                                     string,
        compound_code                                   string,
        product_service_id                              string,
        dispense_as_written                             string,
        date_prescription_written                       string,
        number_of_refills_authorized                    string,
        level_of_service                                string,
        unit_dose_indicator                             string,
        product_service_id_qualifier                    string,
        quantity_dispensed                              string,
        prescription_service_reference_number_qualifier string,
        unit_of_measure                                 string,
        diagnosis_code                                  string,
        diagnosis_code_qualifier                        string,
        response_code                                   string,
        reject_code_1                                   string,
        reject_code_2                                   string,
        reject_code_3                                   string,
        reject_code_4                                   string,
        reject_code_5                                   string,
        unique_patient_id                               string,
        pharmacy_claim_id                               string,
        pharmacy_claim_ref_id                           string,
        taxonomy_code                                   string,
        hv_join_key                                     string
    )
    ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.RegexSerDe'
    WITH SERDEPROPERTIES 
    (
        "input.regex" = "^(.{{8}})(.{{6}})(.{{2}})(.{{2}})(.{{10}})(.{{15}})(.{{2}})(.{{8}})(.{{8}})(.{{1}})(.{{25}})(.{{35}})(.{{30}})(.{{30}})(.{{2}})(.{{5}})(.{{2}})(.{{20}})(.{{15}})(.{{2}})(.{{15}})(.{{15}})(.{{25}})(.{{2}})(.{{30}})(.{{18}})(.{{1}})(.{{12}})(.{{5}})(.{{5}})(.{{1}})(.{{19}})(.{{1}})(.{{8}})(.{{5}})(.{{2}})(.{{1}})(.{{2}})(.{{11}})(.{{1}})(.{{2}})(.{{15}})(.{{2}})(.{{1}})(.{{3}})(.{{3}})(.{{3}})(.{{3}})(.{{3}})(.{{15}})(.{{44}})(.{{44}})(.{{10}})(.{{36}}).*"
    )
    STORED AS TEXTFILE
    LOCATION {input_path}
    ;
