SELECT
    MONOTONICALLY_INCREASING_ID()  AS record_id,
    'pregnancy'                AS registry_type,
    txn.claim_id,
    txn.hvid,
    txn.created,
    txn.model_version,
    txn.data_set,
    txn.data_feed,
    txn.data_vendor,
    txn.patient_gender, --txn.race,
    txn.patient_year_of_birth,
    txn.claim_type,
    txn.date_received,
    txn.date_service,
    txn.date_service_end,
    txn.inst_discharge_status_std_id,
    txn.inst_type_of_bill_std_id,

    txn.inst_drg_std_id,
    txn.inst_drg_vendor_id,

    txn.place_of_service_std_id,
    txn.diagnosis_code,
    txn.diagnosis_code_qual,
    txn.admit_diagnosis_ind,
    txn.procedure_code,
    txn.procedure_code_qual,
    txn.procedure_units_billed,
    txn.procedure_modifier_1,
    txn.revenue_code,
    --txn.total_charge,
    txn.prov_rendering_vendor_id,
    txn.prov_billing_vendor_id,
    txn.logical_delete_reason,
    CAST(EXTRACT_DATE('{VDR_FILE_DT}', '%Y-%m-%d') AS DATE) AS stg_file_date,
    txn.part_provider,
    txn.part_best_date

FROM inv_norm_50_dx_cf_expl txn
