DROP TABLE IF EXISTS transactions;
CREATE EXTERNAL TABLE transactions (
        claim_line_id             string,
        claim_id                  string,
        line_seq_no               string,
        facility_id               string,
        create_time               string,
        pat_acct_no               string,
        pat_lastname              string,
        pat_firstname             string,
        pat_dob                   string,
        pat_gender                string,
        pat_policy_no             string,
        pat_rel_to_insured        string,
        pat_id_qual               string,
        pat_id                    string,
        sub_lastname              string,
        sub_firstname             string,
        sub_policy_no             string,
        sub_id_qual               string,
        sub_id                    string,
        submitted_chg_total       string,
        diag_principal            string,
        diag_2                    string,
        diag_3                    string,
        diag_4                    string,
        diag_5                    string,
        diag_6                    string,
        diag_7                    string,
        diag_8                    string,
        prior_auth_no             string,
        group_no                  string,
        group_name                string,
        payer_resp                string,
        first_dos                 string,
        prior_payer_count         string,
        prior_payer_paid_amt      string,
        bill_prov_name            string,
        bill_prov_taxonomy_code   string,
        bill_prov_npid            string,
        bill_prov_id_qual         string,
        bill_prov_id              string,
        payer_id                  string,
        payer_name                string,
        isa_date_time             string,
        isa_control_no            string,
        gs_date_time              string,
        gs_control_no             string,
        bht_date_time             string,
        bht_control_no            string,
        purpose_code              string,
        insurance_type            string,
        submit_reason_code        string,
        prov_line_control_no      string,
        proc_code_qual            string,
        proc_code                 string,
        mod_1                     string,
        mod_2                     string,
        mod_3                     string,
        mod_4                     string,
        submitted_chg             string,
        submitted_units           string,
        linked_diag_1             string,
        linked_diag_2             string,
        linked_diag_3             string,
        linked_diag_4             string,
        facility_code             string,
        date_svc_start            string,
        date_svc_end              string,
        rend_prov_name            string,
        rend_prov_taxonomy_code   string,
        rend_prov_npid            string,
        rend_prov_id_qual         string,
        rend_prov_id              string,
        refer_prov_name           string,
        refer_prov_taxonomy_code  string,
        refer_prov_npid           string,
        refer_prov_id_qual        string,
        refer_prov_id             string,
        prior_payers_amt_paid     string,
        ord_prov_name             string,
        ord_prov_npid             string,
        ord_prov_id_qual          string,
        ord_prov_id               string,
        serv_facility_name        string,
        serv_facility_id_qual     string,
        serv_facility_id          string,
        serv_facility_address     string,
        serv_facility_city        string,
        serv_facility_state       string,
        serv_facility_zip         string,
        hvjoinkey                 string
        )
    ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
    WITH SERDEPROPERTIES (
        'mapping.claim_line_id' = 'claim_line_id',
        'mapping.claim_id' = 'claim_id',
        'mapping.line_seq_no' = 'line_seq_no',
        'mapping.facility_id' = 'facility_id',
        'mapping.create_time' = 'create_time',
        'mapping.pat_acct_no' = 'pat_acct_no',
        'mapping.pat_lastname' = 'pat_lastname',
        'mapping.pat_firstname' = 'pat_firstname',
        'mapping.pat_dob' = 'pat_dob',
        'mapping.pat_gender' = 'pat_gender',
        'mapping.pat_policy_no' = 'pat_policy_no',
        'mapping.pat_rel_to_insured' = 'pat_rel_to_insured',
        'mapping.pat_id_qual' = 'pat_id_qual',
        'mapping.pat_id' = 'pat_id',
        'mapping.sub_lastname' = 'sub_lastname',
        'mapping.sub_firstname' = 'sub_firstname',
        'mapping.sub_policy_no' = 'sub_policy_no',
        'mapping.sub_id_qual' = 'sub_id_qual',
        'mapping.sub_id' = 'sub_id',
        'mapping.submitted_chg_total' = 'submitted_chg_total',
        'mapping.diag_principal' = 'diag_principal',
        'mapping.diag_2' = 'diag_2',
        'mapping.diag_3' = 'diag_3',
        'mapping.diag_4' = 'diag_4',
        'mapping.diag_5' = 'diag_5',
        'mapping.diag_6' = 'diag_6',
        'mapping.diag_7' = 'diag_7',
        'mapping.diag_8' = 'diag_8',
        'mapping.prior_auth_no' = 'prior_auth_no',
        'mapping.group_no' = 'group_no',
        'mapping.group_name' = 'group_name',
        'mapping.payer_resp' = 'payer_resp',
        'mapping.first_dos' = 'first_dos',
        'mapping.prior_payer_count' = 'prior_payer_count',
        'mapping.prior_payer_paid_amt' = 'prior_payer_paid_amt',
        'mapping.bill_prov_name' = 'bill_prov_name',
        'mapping.bill_prov_taxonomy_code' = 'bill_prov_taxonomy_code',
        'mapping.bill_prov_npid' = 'bill_prov_npid',
        'mapping.bill_prov_id_qual' = 'bill_prov_id_qual',
        'mapping.bill_prov_id' = 'bill_prov_id',
        'mapping.payer_id' = 'payer_id',
        'mapping.payer_name' = 'payer_name',
        'mapping.isa_date_time' = 'isa_date_time',
        'mapping.isa_control_no' = 'isa_control_no',
        'mapping.gs_date_time' = 'gs_date_time',
        'mapping.gs_control_no' = 'gs_control_no',
        'mapping.bht_date_time' = 'bht_date_time',
        'mapping.bht_control_no' = 'bht_control_no',
        'mapping.purpose_code' = 'purpose_code',
        'mapping.insurance_type' = 'insurance_type',
        'mapping.submit_reason_code' = 'submit_reason_code',
        'mapping.prov_line_control_no' = 'prov_line_control_no',
        'mapping.proc_code_qual' = 'proc_code_qual',
        'mapping.proc_code' = 'proc_code',
        'mapping.mod_1' = 'mod_1',
        'mapping.mod_2' = 'mod_2',
        'mapping.mod_3' = 'mod_3',
        'mapping.mod_4' = 'mod_4',
        'mapping.submitted_chg' = 'submitted_chg',
        'mapping.submitted_units' = 'submitted_units',
        'mapping.linked_diag_1' = 'linked_diag_1',
        'mapping.linked_diag_2' = 'linked_diag_2',
        'mapping.linked_diag_3' = 'linked_diag_3',
        'mapping.linked_diag_4' = 'linked_diag_4',
        'mapping.facility_code' = 'facility_code',
        'mapping.date_svc_start' = 'date_svc_start',
        'mapping.date_svc_end' = 'date_svc_end',
        'mapping.rend_prov_name' = 'rend_prov_name',
        'mapping.rend_prov_taxonomy_code' = 'rend_prov_taxonomy_code',
        'mapping.rend_prov_npid' = 'rend_prov_npid',
        'mapping.rend_prov_id_qual' = 'rend_prov_id_qual',
        'mapping.rend_prov_id' = 'rend_prov_id',
        'mapping.refer_prov_name' = 'refer_prov_name',
        'mapping.refer_prov_taxonomy_code' = 'refer_prov_taxonomy_code',
        'mapping.refer_prov_npid' = 'refer_prov_npid',
        'mapping.refer_prov_id_qual' = 'refer_prov_id_qual',
        'mapping.refer_prov_id' = 'refer_prov_id',
        'mapping.prior_payers_amt_paid' = 'prior_payers_amt_paid',
        'mapping.ord_prov_name' = 'ord_prov_name',
        'mapping.ord_prov_npid' = 'ord_prov_npid',
        'mapping.ord_prov_id_qual' = 'ord_prov_id_qual',
        'mapping.ord_prov_id' = 'ord_prov_id',
        'mapping.serv_facility_name' = 'serv_facility_name',
        'mapping.serv_facility_id_qual' = 'serv_facility_id_qual',
        'mapping.serv_facility_id' = 'serv_facility_id',
        'mapping.serv_facility_address' = 'serv_facility_address',
        'mapping.serv_facility_city' = 'serv_facility_city',
        'mapping.serv_facility_state' = 'serv_facility_state',
        'mapping.serv_facility_zip' = 'serv_facility_zip',
        'mapping.hvjoinkey' = 'hvJoinKey'
        )
    STORED AS TEXTFILE
    LOCATION {input_path}
    ;
