DROP TABLE IF EXISTS raw_transactional;
CREATE TABLE raw_transactional (
        first_name                     text ENCODE lzo,
        last_name                      text ENCODE lzo,
        date_of_birth                  text ENCODE lzo,
        gender                         text ENCODE lzo,
        zip_code                       text ENCODE lzo,
        street_address                 text ENCODE lzo,
        street_address 2               text ENCODE lzo,
        city                           text ENCODE lzo,
        state                          text ENCODE lzo,
        customer__patient_id           text ENCODE lzo,
        ngs_offering                   text ENCODE lzo,
        fish_cmet                      text ENCODE lzo,
        fish_cmyc                      text ENCODE lzo,
        fish_egfr                      text ENCODE lzo,
        fish_her2__neu                 text ENCODE lzo,
        fish_pik3ca                    text ENCODE lzo,
        fish_top2a                     text ENCODE lzo,
        fish-mutational_1p19q          text ENCODE lzo,
        fish-mutational_alk            text ENCODE lzo,
        fish-mutational_ros1           text ENCODE lzo,
        cish_cmet                      text ENCODE lzo,
        cish_egfr                      text ENCODE lzo,
        cish_her2__neu                 text ENCODE lzo,
        cish_mdm2                      text ENCODE lzo,
        cish_top2a                     text ENCODE lzo,
        ihc_ae1__ae3                   text ENCODE lzo,
        ihc_afp                        text ENCODE lzo,
        ihc_alk                        text ENCODE lzo,
        ihc_ar                         text ENCODE lzo,
        ihc_bcl2                       text ENCODE lzo,
        ihc_bcrp                       text ENCODE lzo,
        ihc_bombesin                   text ENCODE lzo,
        ihc_brcp                       text ENCODE lzo,
        ihc_ca 19.9                    text ENCODE lzo,
        ihc_calcitonin                 text ENCODE lzo,
        ihc_calret                     text ENCODE lzo,
        ihc_calretinin                 text ENCODE lzo,
        ihc_cam5.2                     text ENCODE lzo,
        ihc_cav-1                      text ENCODE lzo,
        ihc_cd10                       text ENCODE lzo,
        ihc_cd20                       text ENCODE lzo,
        ihc_cd20__l26                  text ENCODE lzo,
        ihc_cd25                       text ENCODE lzo,
        ihc_cd30                       text ENCODE lzo,
        ihc_cd31                       text ENCODE lzo,
        ihc_cd34                       text ENCODE lzo,
        ihc_cd52                       text ENCODE lzo,
        ihc_cd56                       text ENCODE lzo,
        ihc_cd68                       text ENCODE lzo,
        ihc_cd99                       text ENCODE lzo,
        ihc_cdx2                       text ENCODE lzo,
        ihc_cea                        text ENCODE lzo,
        ihc_chromogranin               text ENCODE lzo,
        ihc_ck14                       text ENCODE lzo,
        ihc_ck17                       text ENCODE lzo,
        ihc_ck19                       text ENCODE lzo,
        ihc_ck20                       text ENCODE lzo,
        ihc_ck5                        text ENCODE lzo,
        ihc_ck5__6                     text ENCODE lzo,
        ihc_ck7                        text ENCODE lzo,
        ihc_ck8                        text ENCODE lzo,
        ihc_c-kit                      text ENCODE lzo,
        ihc_cmet                       text ENCODE lzo,
        ihc_cox2                       text ENCODE lzo,
        ihc_cyclin-d1                  text ENCODE lzo,
        ihc_dog-1                      text ENCODE lzo,
        ihc_ebv                        text ENCODE lzo,
        ihc_ecad                       text ENCODE lzo,
        ihc_egfr                       text ENCODE lzo,
        ihc_ema                        text ENCODE lzo,
        ihc_er                         text ENCODE lzo,
        ihc_ercc1                      text ENCODE lzo,
        ihc_gcdfp                      text ENCODE lzo,
        ihc_gcdfp__brst_ii             text ENCODE lzo,
        ihc_gcdfp-15                   text ENCODE lzo,
        ihc_h3k36me3                   text ENCODE lzo,
        ihc_hcg                        text ENCODE lzo,
        ihc_her2__neu                  text ENCODE lzo,
        ihc_hmb45                      text ENCODE lzo,
        ihc_hsp90                      text ENCODE lzo,
        ihc_igf1r                      text ENCODE lzo,
        ihc_inhibin                    text ENCODE lzo,
        ihc_ki1                        text ENCODE lzo,
        ihc_ki67                       text ENCODE lzo,
        ihc_l26                        text ENCODE lzo,
        ihc_lca                        text ENCODE lzo,
        ihc_mammaglobin                text ENCODE lzo,
        ihc_mart-1                     text ENCODE lzo,
        ihc_melana                     text ENCODE lzo,
        ihc_melanoma_specific_antigen  text ENCODE lzo,
        ihc_mgmt                       text ENCODE lzo,
        ihc_mitf                       text ENCODE lzo,
        ihc_mlh1                       text ENCODE lzo,
        ihc_mrp1                       text ENCODE lzo,
        ihc_msh2                       text ENCODE lzo,
        ihc_msh6                       text ENCODE lzo,
        ihc_nse                        text ENCODE lzo,
        ihc_oc125                      text ENCODE lzo,
        ihc_p53                        text ENCODE lzo,
        ihc_p63                        text ENCODE lzo,
        ihc_p95                        text ENCODE lzo,
        ihc_pap                        text ENCODE lzo,
        ihc_pbrm1                      text ENCODE lzo,
        ihc_pd-1                       text ENCODE lzo,
        ihc_pdgfr                      text ENCODE lzo,
        ihc_pd-l1                      text ENCODE lzo,
        ihc_pgp                        text ENCODE lzo,
        ihc_pms2                       text ENCODE lzo,
        ihc_pr                         text ENCODE lzo,
        ihc_psa                        text ENCODE lzo,
        ihc_psap                       text ENCODE lzo,
        ihc_pten                       text ENCODE lzo,
        ihc_rcc                        text ENCODE lzo,
        ihc_rcca                       text ENCODE lzo,
        ihc_rrm1                       text ENCODE lzo,
        ihc_rrm2                       text ENCODE lzo,
        ihc_s100                       text ENCODE lzo,
        ihc_sma                        text ENCODE lzo,
        ihc_sparc                      text ENCODE lzo,
        ihc_sparc_monoclonal           text ENCODE lzo,
        ihc_sparc_polyclonal           text ENCODE lzo,
        ihc_survivin                   text ENCODE lzo,
        ihc_synaptophysin              text ENCODE lzo,
        ihc_thyroglobulin              text ENCODE lzo,
        ihc_tle3                       text ENCODE lzo,
        ihc_top2a                      text ENCODE lzo,
        ihc_topo1                      text ENCODE lzo,
        ihc_ts                         text ENCODE lzo,
        ihc_ttf                        text ENCODE lzo,
        ihc_ttf1                       text ENCODE lzo,
        ihc_tubb3                      text ENCODE lzo,
        ihc_uchl-1                     text ENCODE lzo,
        ihc_vegf                       text ENCODE lzo,
        ihc_vimentin                   text ENCODE lzo,
        ihc_wt1                        text ENCODE lzo,
        ihc-h-score_egfr               text ENCODE lzo,
        ihc-ia_ecad                    text ENCODE lzo,
        ihc-ia_er                      text ENCODE lzo,
        ihc-ia_her2__neu               text ENCODE lzo,
        ihc-ia_ki67                    text ENCODE lzo,
        ihc-ia_p53                     text ENCODE lzo,
        ihc-ia_pr                      text ENCODE lzo
) DISTKEY(customer__patient_id) SORTKEY(customer__patient_id);

COPY raw_transactional FROM 's3://healthveritydev/musifer/caris/transactional.bz2' CREDENTIALS :credentials BZIP2 EMPTYASNULL DELIMITER '|';

DROP TABLE IF EXISTS matching_payload;
CREATE TABLE exploded_payload (
        pk             text ENCODE lzo,
        hvid           text ENCODE lzo,
        parentId       text ENCODE lzo,
        childId        text ENCODE lzo,
        personId       text ENCODE lzo,
        threeDigitZip  text ENCODE lzo,
        gender         text ENCODE lzo,
        yearOfBirth    text ENCODE lzo
        ) DISTKEY(hvid) SORTKEY(hvid);

-- an exploded payload is all is needed to generate hlls
DROP TABLE IF EXISTS exploded_payload;
CREATE TABLE exploded_payload (
        pk             text ENCODE lzo,
        hvid           text ENCODE lzo,
        parentId       text ENCODE lzo,
        childId        text ENCODE lzo,
        personId       text ENCODE lzo,
        threeDigitZip  text ENCODE lzo,
        gender         text ENCODE lzo,
        yearOfBirth    text ENCODE lzo
        ) DISTKEY(hvid) SORTKEY(hvid);

COPY exploded_payload FROM 's3://healthveritydev/musifer/caris/exploded.json.bz2' CREDENTIALS :credentials BZIP2 FORMAT AS JSON 's3://healthveritydev/musifer/payloadpaths/caris_explodedpayloadpaths.json';

DROP TABLE IF EXISTS parent_child_map;
CREATE TABLE parent_child_map (
        hvid         text ENCODE lzo,
        parentId     text ENCODE lzo
        ) DISTKEY(hvid) SORTKEY(hvid);

COPY parent_child_map FROM 's3://salusv/matching/fetch-parent-ids/payload/fetch-parent-ids/20160705_Claims_US_CF_Hash_File_HV_Encrypt.dat.decrypted.json2016-10-13T22-06-23.0-1000000.json.bz2' CREDENTIALS :credentials BZIP2 FORMAT AS JSON 's3://healthveritydev/musifer/payloadpaths/parent-child-payloadpaths.json';

DROP TABLE IF EXISTS full_exploded_payload;
CREATE TABLE full_exploded_payload (
        pk           text ENCODE lzo,
        hvid         text ENCODE lzo,
        personId     text ENCODE lzo,
        state        text ENCODE lzo,
        gender       text ENCODE lzo,
        age          text ENCODE lzo
        ) DISTKEY(hvid) SORTKEY(hvid);
