DROP VIEW IF EXISTS default.events;
CREATE VIEW default.events (
    record_id,
    hvid,
    created,
    model_version,
    data_set,
    data_feed,
    data_vendor,
    source_version,
    patient_age,
    patient_year_of_birth,
    patient_zip3,
    patient_state,
    patient_gender,
    source_record_id,
    source_record_qual,
    source_record_date, 
    event,
    event_val,
    event_val_uom,
    event_date,
    event_zip,
    event_revenue,
    event_category_code,
    event_category_code_qual,
    event_category_name,
    event_category_flag,
    event_category_flag_qual,
    logical_delete_reason,
    part_provider,
    part_best_date
) AS SELECT 
    record_id,
    hvid,
    created,
    model_version,
    data_set,
    data_feed,
    data_vendor,
    source_version,
    patient_age,
    patient_year_of_birth,
    patient_zip3,
    patient_state,
    patient_gender,
    source_record_id,
    source_record_qual,
    source_record_date, 
    event,
    event_val,
    event_val_uom,
    event_date,
    event_zip,
    event_revenue,
    event_category_code,
    event_category_code_qual,
    event_category_name,
    event_category_flag,
    event_category_flag_qual,
    logical_delete_reason,
    part_provider,
    CASE WHEN part_best_date IN ('NULL', '0_PREDATES_HVM_HISTORY')
    THEN '0_PREDATES_HVM_HISTORY'
    ELSE part_best_date
    END AS part_best_date
FROM events_v4
UNION ALL
SELECT 
    record_id,
    hvid,
    created,
    model_version,
    data_set,
    data_feed,
    data_vendor,
    source_version,
    patient_age,
    patient_year_of_birth,
    patient_zip,
    patient_state,
    patient_gender,
    source_record_id,
    source_record_qual,
    source_record_date, 
    event,
    event_val,
    NULL AS event_val_uom,
    event_date,
    NULL AS event_zip,
    NULL AS event_revenue,
    NULL AS event_category_code,
    NULL AS event_category_code_qual,
    NULL AS event_category_name,
    NULL AS event_category_flag,
    NULL AS event_category_flag_qual,
    NULL AS logical_delete_reason,
    part_provider,
    CASE WHEN part_best_date IN ('NULL', '0_PREDATES_HVM_HISTORY')
    THEN '0_PREDATES_HVM_HISTORY'
    ELSE part_best_date
    END AS part_best_date
FROM events_old;
