DROP TABLE IF EXISTS {table_name};
CREATE TABLE {table_name} (
    record_id               bigint,
    hvid                    string,
    created                 date,
    model_version           string,
    data_set                string,
    data_feed               string,
    data_vendor             string,
    source_version          string,
    patient_id              string,
    patient_member_id       string,
    patient_group_id        string,
    patient_group_name      string,
    patient_control_number  string,
    patient_email           string,
    patient_phone           string,
    patient_ssn             string,
    patient_first_name      string,
    patient_last_name       string,
    patient_age             string,
    patient_date_of_birth   date,
    patient_year_of_birth   string,
    patient_zip             string,
    patient_zip3            string,
    patient_address         string,
    patient_city            string,
    patient_state           string,
    patient_gender          string,
    source_record_id        string,
    source_record_qual      string,
    source_record_date      string,
    event                   string,
    event_val               string,
    event_val_uom           string,
    event_date              string,
    part_provider           string,
    part_processdate        string
)
{properties};
