SELECT
    claim_tcn_id	                            AS 	    claim_number,
    record_type	                                AS 	    record_type,
    payer_id	                                AS      other_diagnosis_code_8,
    coding_type	                                AS      other_diagnosis_code_9,
    received_date	                            AS      other_diagnosis_code_10,
    claim_type      	                        AS      other_diagnosis_code_11,
    column_7    	                            AS      other_diagnosis_code_12,
    payer_name	                                AS      other_diagnosis_code_13,
    column_9    	                            AS      other_diagnosis_code_14,
    column_10   	                            AS      other_diagnosis_code_15,
    column_11	                                AS      other_diagnosis_code_16,
    column_12	                                AS      other_diagnosis_code_17,
    column_13	                                AS      other_diagnosis_code_18,
    column_14	                                AS      other_diagnosis_code_19,
    member_birth_year	                        AS      other_diagnosis_code_20,
    column_16	                                AS      other_diagnosis_code_21,
    column_17	                                AS      other_diagnosis_code_22,
    column_18	                                AS      other_diagnosis_code_23,
    patient_state	                            AS      other_diagnosis_code_24,
    patient_zip3	                            AS      other_icd_proc_code_10,
    column_21	                                AS      other_icd_proc_code_11,
    patient_relationship_code                   AS      other_icd_proc_code_12,
    column_23	                                AS      other_icd_proc_code_13,
    column_24	                                AS      other_icd_proc_code_14,
    patient_gender_code	                        AS      other_icd_proc_code_15,
    patient_birth_year	                        AS      other_icd_proc_code_16,
    column_27                                   AS      other_icd_proc_code_17,
    billing_prov_id	                            AS      other_icd_proc_code_18,
    billing_prov_npi	                        AS      other_icd_proc_code_19,
    billing_prov_org_name	                    AS      other_icd_proc_code_20,
    billing_prov_ind_name	                    AS      other_icd_proc_code_21,
    billing_prov_street_address_1               AS      other_icd_proc_code_22,
    billing_prov_street_address_2               AS      other_icd_proc_code_23,
    billing_prov_city                           AS      other_icd_proc_code_24,
    billing_prov_state	                        AS      claim_filing_ind_cd,
    billing_prov_zip	                        AS      referring_prov_state_license,
    column_37                                   AS      column_37,
    referring_prov_npi	                        AS      referring_prov_commercial_id,
    column_39	                                AS      pay_to_prov_address_1,
    referring_prov_name	                        AS      pay_to_prov_address_2,
    column_41	                                AS      pay_to_prov_city,
    rendering_attending_prov_npi                AS      pay_to_prov_zip,
    rendering_prov_org_name	                    AS      pay_to_prov_state,
    rendering_attending_prov_ind_name	        AS      column_44,
    column_45	                                AS      supervising_prov_last_name,
    facility_name	                            AS      supervising_prov_first_name,
    column_47	                                AS      supervising_prov_middle_name,
    facility_street_address_1                   AS      supervising_prov_npi,
    facility_street_address_2                   AS      supervising_prov_state_license,
    facility_city	                            AS      column_50,
    facility_state	                            AS      supervising_prov_commercial_id,
    facility_zip	                            AS      supervising_prov_location,
    statement_from_date	                        AS      column_53,
    statement_to_date	                        AS      operating_prov_last_name,
    total_claim_charge_amt	                    AS      operating_prov_first_name,
    column_56	                                AS      operating_prov_middle_name,
    drg_code	                                AS      operating_prov_npi,
    column_58	                                AS      operating_prov_state_license,
    bill_type	                                AS      column_59,
    patient_signature_source_cd	                AS      operating_prov_commercial,
    bebefits_assignment_cert_ind                AS      operating_prov_location,
    column_62	                                AS      column_62,
    principal_icd_procedure_code                AS      oth_operating_prov_last_name,
    admitting_diagnosis_code                    AS      oth_operating_prov_first_name,
    principal_diagnosis_code                    AS      oth_supervising_prov_middle_name,
    other_diagnosis_code_1	                    AS      oth_operating_prov_npi,
    other_diagnosis_code_2	                    AS      oth_operating_prov_state_license,
    other_diagnosis_code_3	                    AS      column_68,
    other_diagnosis_code_4	                    AS      oth_operating_prov_commercial_id,
    other_diagnosis_code_5	                    AS      oth_operating_prov_location,
    other_diagnosis_code_6	                    AS      pay_to_plan_name,
    other_diagnosis_code_7	                    AS      pay_to_plan_address_1,
    other_icd_proc_code_1	                    AS      pay_to_plan_address_2,
    other_icd_proc_code_2	                    AS      pay_to_plan_city,
    other_icd_proc_code_3	                    AS      pay_to_plan_zip,
    other_icd_proc_code_4	                    AS      pay_to_plan_state,
    other_icd_proc_code_5	                    AS      pay_to_plan_naic_id,
    column_78	                                AS      pay_to_plan_payer_id,
    claim_filing_indicator_cd                   AS      pay_to_plan_plan_id,
    column_80	                                AS      pay_to_plan_clm_ofc_number,
    accident_related_ind	                    AS      pay_to_plan_tax_id,
    column_82	                                AS      cob1_payer_name,
    column_83	                                AS      cob1_payer_id,
    column_84	                                AS      cob1_hpid,
    column_85	                                AS      cob1_resp_seq_cd,
    column_86                                   AS      column_86,
    column_87                                   AS      column_87,
    column_88                                   AS      column_88,
    column_89	                                AS      cob1_ins_type_cd,
    column_90	                                AS      cob1_clm_filing_ind_cd,
    column_91	                                AS      cob2_payer_name,
    admission_date	                            AS      cob2_payer_id,
    column_93	                                AS      cob2_hpid,
    admission_type_code	                        AS      cob2_resp_seq_cd,
    admission_source_code	                    AS      column_95,
    column_96                                   AS      column_96,
    patient_status_code	                        AS      column_97,
    column_98	                                AS      cob2_ins_type_cd,
    other_icd_proc_code_6	                    AS      cob2_clm_filing_ind_cd,
    other_icd_proc_code_7	                    AS      cob3_payer_name,
    other_icd_proc_code_8	                    AS      cob3_payer_id,
    other_icd_proc_code_9	                    AS      cob3_hpid,
    billing_pr_taxonomy	                        AS      cob3_resp_seq_cd,
    billing_pr_state_license                    AS      column_104,
    column_105                                  AS      column_105,
    billing_pr_ssn	                            AS      column_106,
    rendering_attending_prov_taxonomy	        AS      cob3_ins_type_cd,
    rendering_attending_prov_state_license	    AS      cob3_clm_filing_ind_cd,
    column_109	                                AS      cob4_payer_name,
    facility_npi	                            AS      cob4_payer_id,
    facility_state_license	                    AS      cob4_hpid
FROM claim clm
WHERE clm.record_type = 'D'
GROUP BY
1,2,3,4,5,6,7,8,9,10,
11,12,13,14,15,16,17,18,19,20,
21,22,23,24,25,26,27,28,29,30,
31,32,33,34,35,36,37,38,39,40,
41,42,43,44,45,46,47,48,49,50,
51,52,53,54,55,56,57,58,59,60,
61,62,63,64,65,66,67,68,69,70,
71,72,73,74,75,76,77,78,79,80,
81,82,83,84,85,86,87,88,89,90,
91,92,93,94,95,96,97,98,99,
100,101,102,103,104,105,106,
107,108,109,110,111
