from spark.helpers.source_table import SourceTable

TABLE_CONF = {
    'clm': SourceTable(
        'csv',
        separator='|',
        trimmify_nullify=False,
        confirm_schema=True,
        columns=[
            'claimuid',
            'memberuid',
            'provideruid',
            'claimstatuscode',
            'servicedate',
            'servicethrudate',
            'ubpatientdischargestatuscode',
            'serviceunitquantity',
            'denieddayscount',
            'rxproviderindicator',
            'pcpproviderindicator',
            'roomboardindicator',
            'majorsurgeryindicator',
            'excludefromdischargeindicator',
            'claimformtypecode',
            'institutionaltypecode',
            'professionaltypecode',
            'billingprovideruid',
            'renderingprovideruid',
            'renderingprovidernpi',
            'billingprovidernpi',
            'createddate'
        ]
    ),
    'ccd': SourceTable(
        'csv',
        separator='|',
        trimmify_nullify=False,
        confirm_schema=True,
        columns=[
            'claimuid',
            'memberuid',
            'servicedate',
            'servicethrudate',
            'codetype',
            'ordinalposition',
            'codevalue',
            'derivedindicator',
            'createddate'
        ]
    ),
    'mbr': SourceTable(
        'csv',
        separator='|',
        confirm_schema=True,
        columns=[
            'memberuid',
            'birthyear',
            'gendercode',
            'statecode',
            'zip3value',
            'raceethnicitytypecode',
            'createddate'
        ]
    ),
    'prv': SourceTable(
        'csv',
        separator='|',
        confirm_schema=True,
        columns=[
            'provideruid',
            'lastname',
            'firstname',
            'middlename',
            'companyname',
            'npi1',
            'npitypecode1',
            'parentorganization1',
            'npi2',
            'npitypecode2',
            'parentorganization2',
            'primarypracticeaddress',
            'secondarypracticeaddress',
            'practicecity',
            'practicestate',
            'practicezip',
            'practicezip4',
            'practicephone',
            'primarybillingaddress',
            'secondarybillingaddress',
            'billingcity',
            'billingstate',
            'billingzip',
            'billingzip4',
            'billingphone',
            'taxonomycode1',
            'taxonomytype1',
            'taxonomyclassification1',
            'taxonomyspecialization1',
            'taxonomycode2',
            'taxonomytype2',
            'taxonomyclassification2',
            'taxonomyspecialization2',
            'createddate'
        ]
    ),
    'psp': SourceTable(
        'csv',
        separator='|',
        confirm_schema=True,
        columns=[
            'provideruid',
            'nameprefix',
            'name',
            'namesuffix',
            'address1',
            'address2',
            'city',
            'state',
            'zip',
            'phone',
            'fax',
            'deanumber',
            'npinumber',
            'createddate'
        ]
    )
}
