COPY emdeon_rx_norm

(recordid,date_authorized,time_authorized,bin_number,versionnumber,transaction_code,processor_control_number
,transactioncount,serviceproviderid,serviceprovideridqualifier,date_service,year_of_birth,patientlocation,patientfirstname
,patientlastname,patientstreetaddress,patientstateprovince,patient_zip3,patientidqualifier,patientid,providerid,prov_dispensing_qual,prescriberid
,primarycareproviderid,prescriberlastname,prov_prescribing_qual,prov_primary_care_qual,groupid,cardholderid,personcode,patientrelationshipcode,eligibilityclarificationcode
,homeplan,cob_count,other_payer_coverage_type,other_payer_coverage_qual,other_payer_coverage_id,otherpayeramountpaidqualifier,otherpayeramountpaidsubmitted,other_payer_date
,carrierid,date_injury,claimreferenceid,other_payer_coverage_code,rx_number,fill_number,days_supply,compound_code,productserviceid,dispensed_as_written,date_written,refill_auth_amount
,level_of_service,prescription_origin,submission_clarification,unit_dose_indicator,productserviceidqualifier,dispensed_quantity,orig_prescribed_product_service_code,orig_prescribed_quantity,orig_prescribed_product_service_code_qual
,rx_number_qual,prior_auth_type_code,unit_of_measure,reason_for_service,professional_service_code,result_of_service_code,coupon_type,coupon_number,coupon_value,submitted_ingredient_cost,submitted_dispensing_fee
,basis_of_cost_determination,usual_and_customary_charge,submitted_patient_pay,submitted_gross_due,submitted_incentive,submitted_professional_service_fee,submitted_other_claimed_qual,submitted_other_claimed,submitted_flat_sales_tax
,submitted_percent_sales_tax_amount,submitted_percent_sales_tax_rate,submitted_percent_sales_tax_basis,diagnosis_code,diagnosis_code_qual,response_code,paid_patient_pay,paid_ingredient_cost,paid_dispensing_fee,paid_gross_due
,accumulated_deductible,remaining_deductible,remaining_benefit,periodic_deductible_applied,copay_coinsurance,product_selection_attributed,periodic_benefit_exceed
,incentive_paid,basis_of_reimbursement_determination,sales_tax,tax_exempt_indicator,paid_flat_sales_tax,paid_percentage_sales_tax_amount,paid_percent_sales_tax_rate
,paid_percent_sales_tax_basis,paid_professional_service_fee,paid_other_claimed_qual,paid_other_claimed,other_payer_recognized,payer_plan_id,ncpdpnumber
,pharmacy_npi,plantype,pharmacy_postal_code,reject_reason_code_1,reject_reason_code_2,reject_reason_code_3,reject_reason_code_4,reject_reason_code_5,payer_id
,payer_id_qual,payer_plan_name,payer_type,claim_id,procedure_code,procedure_code_qual,ndc_code,product_service_id,product_service_id_qual,prov_dispensing_npi,prov_prescribing_npi
,prov_primary_care_npi,pharmacy_other_id,pharmacy_other_id_qual,prov_dispensing_id,prov_prescribing_id,prov_primary_care_id,gender,patient_state,hvid)

FROM :'S3_INPUT_PATH'
WITH CREDENTIALS :'AWS_CREDENTIALS'
DATEFORMAT 'YYYYMMDD'
ACCEPTANYDATE
BLANKSASNULL
EMPTYASNULL
MAXERROR 100000
COMPUPDATE ON
IGNOREHEADER 1
NULL AS 'null'
DELIMITER '|' bzip2

