DROP TABLE IF EXISTS transactions_raw;
CREATE EXTERNAL TABLE transactions_raw (
        panel                       string,
        panel_version               string,
        other_tests_ordered         string,
        sex                         string,
        age_at_test                 string,
        doc_id                      string,
        summ_call                   string,
        big_blob                    string,
        genes_tested                string,
        genes_found                 string,
        variants                    string,
        frontpage                   string,
        driver                      string,
        c10                         string,
        c20                         string,
        mean_coverage               string,
        average_variant_depth       string,
        rundate                     string,
        physician_account           string,
        ordering_physician          string,
        doc_listed_on_final_report  string,
        ordering_physician_npi      string,
        submission_date             string,
        billing_type                string,
        icd9_code_1                 string,
        icd9_code_2                 string,
        icd9_code_3                 string,
        icd9_code_4                 string,
        icd10_code_1                string,
        icd10_code_2                string,
        icd10_code_3                string,
        icd10_code_4                string,
        gender                      string,
        patient_state               string,
        patient_country             string,
        primary_insurance_company   string,
        secondary_insurance_company string,
        claimid                     string,
        hvjoinkey                   string
        )
    ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
    WITH SERDEPROPERTIES (
        'mapping.panel'                        = 'panel',
        'mapping.panel_version'                = 'panel_version',
        'mapping.other_tests_ordered'          = 'other_tests_ordered',
        'mapping.sex'                          = 'sex',
        'mapping.age_at_test'                  = 'age_at_test',
        'mapping.doc_id'                       = 'doc_id',
        'mapping.summ_call'                    = 'summ_call',
        'mapping.big_blob'                     = 'big_blob',
        'mapping.genes_tested'                 = 'genes_tested',
        'mapping.genes_found'                  = 'genes_found',
        'mapping.variants'                     = 'variants',
        'mapping.frontpage'                    = 'frontpage',
        'mapping.driver'                       = 'driver',
        'mapping.c10'                          = 'c10',
        'mapping.c20'                          = 'c20',
        'mapping.mean_coverage'                = 'mean_coverage',
        'mapping.average_variant_depth'        = 'average_variant_depth',
        'mapping.rundate'                      = 'rundate',
        'mapping.physician_account'            = 'physician/account',
        'mapping.ordering_physician'           = 'ordering_physician',
        'mapping.doc_listed_on_final_report'   = 'DOC. LISTED ON FINAL REPORT',
        'mapping.ordering_physician_npi'       = 'ORDERING PHYSICIAN NPI',
        'mapping.submission_date'              = 'submission_date',
        'mapping.billing_type'                 = 'billing_type',
        'mapping.icd9_code_1'                  = 'ICD-9 CODE #1',
        'mapping.icd9_code_2'                  = 'ICD-9 CODE #2',
        'mapping.icd9_code_3'                  = 'ICD-9 CODE #3',
        'mapping.icd9_code_4'                  = 'ICD-9 CODE #4',
        'mapping.icd10_code_1'                 = 'ICD-10 CODE #1',
        'mapping.icd10_code_2'                 = 'ICD-10 CODE #2',
        'mapping.icd10_code_3'                 = 'ICD-10 CODE #3',
        'mapping.icd10_code_4'                 = 'ICD-10 CODE #4',
        'mapping.gender'                       = 'gender',
        'mapping.patient_state'                = 'patient_state',
        'mapping.patient_country'              = 'patient_country',
        'mapping.primary_insurance_company'    = 'primary_insurance_company',
        'mapping.secondary_insurance_company'  = 'secondary_insurance_company',
        'mapping.claimid'                      = 'claimID',
        'mapping.hvjoinkey'                    = 'hvJoinKey'
        )
STORED AS TEXTFILE
LOCATION {input_path};
