MEDICALCLAIMS = 'medicalclaims'
PHARMACYCLAIMS = 'pharmacyclaims'
LABTESTS = 'labtests'
EVENTS = 'events'
ENROLLMENT = 'enrollment'

EMR_ENCOUNTER = 'emr_encounter'
EMR_PROCEDURE = 'emr_procedure'
EMR_DIAGNOSIS = 'emr_diagnosis'
EMR_PROVIDER_ORDER = 'emr_provider_order'
EMR_LAB_ORDER = 'emr_lab_order'
EMR_LAB_RESULT = 'emr_lab_result'
EMR_MEDICATION = 'emr_medication'
EMR_CLINICAL_OBSERVATION = 'emr_clinical_observation'
EMR_VITAL_SIGN = 'emr_vital_sign'
