"""
procedure crf schema
"""

from pyspark.sql.types import *
from spark.common.schema import Schema

schema = Schema(
    name='schema_v1',
    data_type='custom_mart',
    output_directory='ccf/2021-08-31/procedure_crf/',
    distribution_key='record_id',
    provider_partition_column='part_provider',
    date_partition_column='part_mth',
    schema_structure=StructType([
        StructField('record_id', LongType(), True),
        StructField('crt_dt', DateType(), True),
        StructField('data_set_nm', StringType(), True),
        StructField('hvid', StringType(), True),
        StructField('ptnt_birth_yr', IntegerType(), True),
        StructField('ptnt_age_num', StringType(), True),
        StructField('ptnt_gender_cd', StringType(), True),
        StructField('ptnt_state_cd', StringType(), True),
        StructField('ptnt_zip3_cd', StringType(), True),
        StructField('deidentified_master_patient_id', StringType(), True),
        StructField('deidentified_patient_id', StringType(), True),
        StructField('data_source', StringType(), True),
        StructField('proc_id', StringType(), True),
        StructField('visit_encounter_id', StringType(), True),
        StructField('proc_concept_name', StringType(), True),
        StructField('proc_concept_code', StringType(), True),
        StructField('proc_system_name', StringType(), True),
        StructField('src_proc_concept_code', StringType(), True),
        StructField('src_proc_system_name', StringType(), True),
        StructField('src_proc_concept_name', StringType(), True),
        StructField('proc_status_concept_name', StringType(), True),
        StructField('proc_status_concept_code', StringType(), True),
        StructField('proc_start_date', StringType(), True),
        StructField('proc_end_date', StringType(), True),
        StructField('procedure_domain', StringType(), True),
        StructField('physician_notes_proc_avail', StringType(), True),
        StructField('category', StringType(), True),
        StructField('date_of_event', StringType(), True),
        StructField('event_type', StringType(), True),
        StructField('indication', StringType(), True),
        StructField('max_extent_active_disease', StringType(), True),
        StructField('max_extent_of_exam', StringType(), True),
        StructField('modified_mayo_endoscopy_score', StringType(), True),
        StructField('sum_of_mayo_endo_subscore', StringType(), True),
        StructField('diagnosis', StringType(), True),
        StructField('location', StringType(), True),
        StructField('size_of_ulcers', StringType(), True),
        StructField('affected_surface', StringType(), True),
        StructField('ulcerated_surface', StringType(), True),
        StructField('presence_of_narrowings', StringType(), True),
        StructField('mayo_endoscopic_subscore', StringType(), True),
        StructField('visualized', StringType(), True),
        StructField('erythema', StringType(), True),
        StructField('vascular_pattern', StringType(), True),
        StructField('friability', StringType(), True),
        StructField('mucosal_breaks', StringType(), True),
        StructField('ses_cd_subscore', StringType(), True),
        StructField('procedure_results', StringType(), True),
        StructField('erosions', StringType(), True),
        StructField('stricture', StringType(), True),
        StructField('stricture_severity', StringType(), True),
        StructField('rutgeerts_score', StringType(), True),
        StructField('pathology', StringType(), True),
        StructField('prmy_src_tbl_nm', StringType(), True)
    ])
)
