SELECT  
crt_dt,
mdl_vrsn_num,
data_set_nm,
hvm_vdr_id,
hvm_vdr_feed_id,
hv_medctn_id,
vdr_org_id,
hvid,
ptnt_birth_yr,
ptnt_age_num,
ptnt_gender_cd,
ptnt_state_cd,
ptnt_zip3_cd,
medctn_ord_dt,
medctn_admin_dt,
medctn_ordg_prov_vdr_id,
medctn_ordg_prov_vdr_id_qual,
medctn_ordg_prov_alt_id,
medctn_ordg_prov_alt_id_qual,
medctn_ordg_prov_alt_speclty_id,
medctn_ordg_prov_alt_speclty_id_qual,
medctn_ordg_prov_state_cd,
medctn_start_dt,
medctn_end_dt,
medctn_ndc,
medctn_brd_nm,
medctn_genc_nm,
medctn_admin_form_nm,
medctn_dose_txt,
medctn_dose_txt_qual,
medctn_dose_uom,
medctn_admin_rte_txt,
medctn_last_rfll_dt,
rec_stat_cd,
prmy_src_tbl_nm,
part_hvm_vdr_feed_id,
part_mth
FROM amazingcharts_medication_11_pre_norm

GROUP BY  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
          15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
          28, 29, 30, 31, 32, 33, 34, 35, 36, 37
