SELECT  
    crt_dt,
    mdl_vrsn_num,
    data_set_nm,
    hvm_vdr_id,
    hvm_vdr_feed_id,
    hv_enc_id,
    vdr_org_id,
    vdr_enc_id,
    vdr_enc_id_qual,
    hvid,
    ptnt_birth_yr,
    ptnt_age_num,
    ptnt_gender_cd,
    ptnt_state_cd,
    ptnt_zip3_cd,
    enc_start_dt,
    enc_rndrg_prov_vdr_id,
    enc_rndrg_prov_vdr_id_qual,
    enc_rndrg_prov_alt_id,
    enc_rndrg_prov_alt_id_qual,
    enc_rndrg_prov_alt_speclty_id,
    enc_rndrg_prov_alt_speclty_id_qual,
    enc_rndrg_prov_state_cd,
    data_captr_dt,
    prmy_src_tbl_nm,
    part_hvm_vdr_feed_id,
    part_mth
FROM amazingcharts_encounter_1_pre_norm

GROUP BY  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
         11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
         21, 22, 23, 24, 25, 26, 27
