SELECT  
    hv_proc_id,
    crt_dt,
    mdl_vrsn_num,
    data_set_nm,
    src_vrsn_id,
    hvm_vdr_id,
    hvm_vdr_feed_id,
    vdr_org_id,
    vdr_proc_id,
    vdr_proc_id_qual,
    vdr_alt_proc_id,
    vdr_alt_proc_id_qual,
    hvid,
    ptnt_birth_yr,
    ptnt_age_num,
    ptnt_lvg_flg,
    ptnt_dth_dt,
    ptnt_gender_cd,
    ptnt_state_cd,
    ptnt_zip3_cd,
    hv_enc_id,
    enc_dt,
    proc_dt,
    proc_prov_npi,
    proc_prov_qual,
    proc_prov_vdr_id,
    proc_prov_vdr_id_qual,
    proc_prov_alt_id,
    proc_prov_alt_id_qual,
    proc_prov_tax_id,
    proc_prov_state_lic_id,
    proc_prov_comrcl_id,
    proc_prov_upin,
    proc_prov_ssn,
    proc_prov_nucc_taxnmy_cd,
    proc_prov_alt_taxnmy_id,
    proc_prov_alt_taxnmy_id_qual,
    proc_prov_mdcr_speclty_cd,
    proc_prov_alt_speclty_id,
    proc_prov_alt_speclty_id_qual,
    proc_prov_frst_nm,
    proc_prov_last_nm,
    proc_prov_fclty_nm,
    proc_prov_addr_1_txt,
    proc_prov_addr_2_txt,
    proc_prov_state_cd,
    proc_prov_zip_cd,
    proc_rndrg_fclty_npi,
    proc_rndrg_fclty_vdr_id,
    proc_rndrg_fclty_vdr_id_qual,
    proc_rndrg_fclty_alt_id,
    proc_rndrg_fclty_alt_id_qual,
    proc_rndrg_fclty_tax_id,
    proc_rndrg_fclty_state_lic_id,
    proc_rndrg_fclty_comrcl_id,
    proc_rndrg_fclty_nucc_taxnmy_cd,
    proc_rndrg_fclty_alt_taxnmy_id,
    proc_rndrg_fclty_alt_taxnmy_id_qual,
    proc_rndrg_fclty_mdcr_speclty_cd,
    proc_rndrg_fclty_alt_speclty_id,
    proc_rndrg_fclty_alt_speclty_id_qual,
    proc_rndrg_fclty_nm,
    proc_rndrg_fclty_addr_1_txt,
    proc_rndrg_fclty_addr_2_txt,
    proc_rndrg_fclty_state_cd,
    proc_rndrg_fclty_zip_cd,
    proc_rndrg_prov_npi,
    proc_rndrg_prov_vdr_id,
    proc_rndrg_prov_vdr_id_qual,
    proc_rndrg_prov_alt_id,
    proc_rndrg_prov_alt_id_qual,
    proc_rndrg_prov_tax_id,
    proc_rndrg_prov_state_lic_id,
    proc_rndrg_prov_comrcl_id,
    proc_rndrg_prov_upin,
    proc_rndrg_prov_ssn,
    proc_rndrg_prov_nucc_taxnmy_cd,
    proc_rndrg_prov_alt_taxnmy_id,
    proc_rndrg_prov_alt_taxnmy_id_qual,
    proc_rndrg_prov_mdcr_speclty_cd,
    proc_rndrg_prov_alt_speclty_id,
    proc_rndrg_prov_alt_speclty_id_qual,
    proc_rndrg_prov_frst_nm,
    proc_rndrg_prov_last_nm,
    proc_rndrg_prov_addr_1_txt,
    proc_rndrg_prov_addr_2_txt,
    proc_rndrg_prov_state_cd,
    proc_rndrg_prov_zip_cd,
    proc_cd,
    proc_cd_qual,
    proc_cd_1_modfr,
    proc_cd_2_modfr,
    proc_cd_3_modfr,
    proc_cd_4_modfr,
    proc_cd_modfr_qual,
    proc_snomed_cd,
    proc_prty_cd,
    proc_prty_cd_qual,
    proc_alt_cd,
    proc_alt_cd_qual,
    proc_ndc,
    proc_pos_cd,
    proc_unit_qty,
    proc_uom,
    proc_diag_cd,
    proc_diag_cd_qual,
    proc_stat_cd,
    proc_stat_cd_qual,
    proc_typ_cd,
    proc_typ_cd_qual,
    proc_admin_rte_cd,
    proc_admin_site_cd,
    proc_grp_txt,
    data_src_cd,
    data_captr_dt,
    rec_stat_cd,
    prmy_src_tbl_nm,
    part_hvm_vdr_feed_id,
    part_mth
FROM
(
    (
    SELECT * FROM amazingcharts_procedure_1_pre_norm procedure_1
        WHERE NOT EXISTS
        (
            SELECT 1 FROM amazingcharts_procedure_3_pre_norm procedure_3
            WHERE procedure_1.proc_dt = procedure_3.proc_dt
                AND procedure_1.hvid = procedure_3.hvid
                AND procedure_1.proc_cd = procedure_3.proc_cd
        )
    )
    UNION ALL
    SELECT * FROM amazingcharts_procedure_2_pre_norm
    UNION ALL
    SELECT * FROM amazingcharts_procedure_3_pre_norm
) 
GROUP BY  
    1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
    16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
    46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
    61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
    76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
    91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104,
    105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
    117, 118, 119
