DROP TABLE IF EXISTS quest_raw;
CREATE TABLE quest_raw (
        accn_id text encode lzo,
        dosid text encode lzo,
        local_order_code text encode lzo,
        standard_order_code text encode lzo,
        order_name text encode lzo,
        loinc_code text encode lzo,
        local_result_code text encode lzo,
        result_name text encode lzo,
        date_of_service text encode lzo,
        date_collected text encode lzo,
        diagnosis_code text encode lzo,
        icd_codeset_ind text encode lzo
        );

DROP TABLE IF EXISTS normalized_output;
CREATE TABLE normalized_output (
        record_id int identity(0,1),
        claim_id text encode lzo,
        hvid text encode lzo,
        created date DEFAULT :today,
        model_version text DEFAULT '1' ENCODE lzo,
        data_set text DEFAULT :filename ENCODE lzo,
        data_feed text DEFAULT 'quest lab' ENCODE lzo,
        data_vendor text DEFAULT 'quest' ENCODE lzo,
        source_version text encode lzo,
        patient_gender text encode lzo,
        patient_age text encode lzo,
        patient_year_of_birth text encode lzo,
        patient_zip3 text encode lzo,
        patient_state text encode lzo,
        date_service text encode lzo,
        date_specimen text encode lzo,
        date_report text encode lzo,
        time_report text encode lzo,
        loinc_code text encode lzo,
        lab_id text encode lzo,
        test_id text encode lzo,
        test_number text encode lzo,
        test_battery_local_id text encode lzo,
        test_battery_std_id text encode lzo,
        test_battery_name text encode lzo,
        test_ordered_local_id text encode lzo,
        test_ordered_std_id text encode lzo,
        test_ordered_name text encode lzo,
        result text encode lzo,
        result_name text encode lzo,
        result_unit_of_measure text encode lzo,
        result_desc text encode lzo,
        result_comments text encode lzo,
        ref_range_low text encode lzo,
        ref_range_high text encode lzo,
        ref_range_alpha text encode lzo,
        abnormal_flag text encode lzo,
        fasting_status text encode lzo,
        diagnosis_code text encode lzo,
        diagnosis_code_qual text encode lzo,
        diagnosis_code_priorty text encode lzo,
        procedure_code text encode lzo,
        procedure_code_qual text encode lzo,
        lab_npi text encode lzo,
        ordering_npi text encode lzo,
        payer_id text encode lzo,
        payer_id_qual text encode lzo,
        payer_name text encode lzo,
        payer_parent_name text encode lzo,
        payer_org_name text encode lzo,
        payer_plan_id text encode lzo,
        payer_plan_name text encode lzo,
        payer_type text encode lzo,
        lab_other_id text encode lzo,
        lab_other_qual text encode lzo,
        ordering_other_id text encode lzo,
        ordering_other_qual text encode lzo,
        ordering_market_type text encode lzo,
        ordering_specialty text encode lzo
        );
