-- DROP TABLE IF EXISTS transactional_raw;
-- CREATE TABLE transactional_raw (
        -- accn_id              text ENCODE lzo,
        -- dosid                text ENCODE lzo,
        -- local_order_code     text ENCODE lzo,
        -- standard_order_code  text ENCODE lzo,
        -- order_name           text ENCODE lzo,
        -- loinc_code           text ENCODE lzo,
        -- local_result_code    text ENCODE lzo,
        -- result_name          text ENCODE lzo,
        -- date_of_service      text ENCODE lzo,
        -- date_collected       text ENCODE lzo,
        -- diagnosis_code       text ENCODE lzo,
        -- icd_codeset_ind      text ENCODE lzo
        -- );

-- DROP TABLE IF EXISTS matching_payload;
-- CREATE TABLE matching_payload (
        -- claimid        varchar ENCODE lzo,
        -- hvid           text ENCODE lzo,
        -- parentid       text ENCODE lzo,
        -- threeDigitZip  char(3) ENCODE lzo,
        -- yearOfBirth    text ENCODE lzo,
        -- gender         text ENCODE lzo,
        -- state          text ENCODE lzo,
        -- age            text ENCODE lzo
        -- ) DISTKEY(claimid) SORTKEY(claimid);

DROP TABLE IF EXISTS normalized_output;
CREATE TABLE normalized_output (
        record_id               bigint IDENTITY(0,1),
        claim_id                text ENCODE lzo,
        hvid                    text ENCODE lzo,
        created                 date DEFAULT :today,
        model_version           text DEFAULT '1' ENCODE lzo,
        data_set                text DEFAULT :filename ENCODE lzo,
        data_feed               text DEFAULT 'quest lab' ENCODE lzo,
        data_vendor             text DEFAULT 'quest' ENCODE lzo,
        source_version          text ENCODE lzo,
        patient_gender          text ENCODE lzo,
        patient_age             text ENCODE lzo,
        patient_year_of_birth   text ENCODE lzo,
        patient_zip3            text ENCODE lzo,
        patient_state           text ENCODE lzo,
        date_service            text ENCODE lzo,
        date_specimen           text ENCODE lzo,
        date_report             text ENCODE lzo,
        time_report             text ENCODE lzo,
        loinc_code              text ENCODE lzo,
        lab_id                  text ENCODE lzo,
        test_id                 text ENCODE lzo,
        test_number             text ENCODE lzo,
        test_battery_local_id   text ENCODE lzo,
        test_battery_std_id     text ENCODE lzo,
        test_battery_name       text ENCODE lzo,
        test_ordered_local_id   text ENCODE lzo,
        test_ordered_std_id     text ENCODE lzo,
        test_ordered_name       text ENCODE lzo,
        result                  text ENCODE lzo,
        result_name             text ENCODE lzo,
        result_unit_of_measure  text ENCODE lzo,
        result_desc             text ENCODE lzo,
        result_comments         text ENCODE lzo,
        ref_range_low           text ENCODE lzo,
        ref_range_high          text ENCODE lzo,
        ref_range_alpha         text ENCODE lzo,
        abnormal_flag           text ENCODE lzo,
        fasting_status          text ENCODE lzo,
        diagnosis_code          text ENCODE lzo,
        diagnosis_code_qual     text ENCODE lzo,
        diagnosis_code_priorty  text ENCODE lzo,
        procedure_code          text ENCODE lzo,
        procedure_code_qual     text ENCODE lzo,
        lab_npi                 text ENCODE lzo,
        ordering_npi            text ENCODE lzo,
        payer_id                text ENCODE lzo,
        payer_id_qual           text ENCODE lzo,
        payer_name              text ENCODE lzo,
        payer_parent_name       text ENCODE lzo,
        payer_org_name          text ENCODE lzo,
        payer_plan_id           text ENCODE lzo,
        payer_plan_name         text ENCODE lzo,
        payer_type              text ENCODE lzo,
        lab_other_id            text ENCODE lzo,
        lab_other_qual          text ENCODE lzo,
        ordering_other_id       text ENCODE lzo,
        ordering_other_qual     text ENCODE lzo,
        ordering_market_type    text ENCODE lzo,
        ordering_specialty      text ENCODE lzo
        );
