DROP TABLE IF EXISTS lab_common_model;
CREATE TABLE lab_common_model (
        record_id               bigint IDENTITY(0,1),
        claim_id                text ENCODE lzo,
        hvid                    text ENCODE lzo,
        created                 date DEFAULT :today,
        model_version           text DEFAULT '1' ENCODE lzo,
        data_set                text DEFAULT :filename ENCODE lzo,
        data_feed               text DEFAULT :feedname ENCODE lzo,
        data_vendor             text DEFAULT :vendor ENCODE lzo,
        source_version          text ENCODE lzo,
        patient_gender          text ENCODE lzo,
        patient_age             text ENCODE lzo,
        patient_year_of_birth   text ENCODE lzo,
        patient_zip3            text ENCODE lzo,
        patient_state           text ENCODE lzo,
        date_service            text ENCODE lzo,
        date_specimen           text ENCODE lzo,
        date_report             text ENCODE lzo,
        time_report             text ENCODE lzo,
        loinc_code              text ENCODE lzo,
        lab_id                  text ENCODE lzo,
        test_id                 text ENCODE lzo,
        test_number             text ENCODE lzo,
        test_battery_local_id   text ENCODE lzo,
        test_battery_std_id     text ENCODE lzo,
        test_battery_name       text ENCODE lzo,
        test_ordered_local_id   text ENCODE lzo,
        test_ordered_std_id     text ENCODE lzo,
        test_ordered_name       text ENCODE lzo,
        result_id               text ENCODE lzo,
        result                  text ENCODE lzo,
        result_name             text ENCODE lzo,
        result_unit_of_measure  text ENCODE lzo,
        result_desc             text ENCODE lzo,
        result_comments         text ENCODE lzo,
        ref_range_low           text ENCODE lzo,
        ref_range_high          text ENCODE lzo,
        ref_range_alpha         text ENCODE lzo,
        abnormal_flag           text ENCODE lzo,
        fasting_status          text ENCODE lzo,
        diagnosis_code          text ENCODE lzo,
        diagnosis_code_qual     text ENCODE lzo,
        diagnosis_code_priorty  text ENCODE lzo,
        procedure_code          text ENCODE lzo,
        procedure_code_qual     text ENCODE lzo,
        lab_npi                 text ENCODE lzo,
        ordering_npi            text ENCODE lzo,
        payer_id                text ENCODE lzo,
        payer_id_qual           text ENCODE lzo,
        payer_name              text ENCODE lzo,
        payer_parent_name       text ENCODE lzo,
        payer_org_name          text ENCODE lzo,
        payer_plan_id           text ENCODE lzo,
        payer_plan_name         text ENCODE lzo,
        payer_type              text ENCODE lzo,
        lab_other_id            text ENCODE lzo,
        lab_other_qual          text ENCODE lzo,
        ordering_other_id       text ENCODE lzo,
        ordering_other_qual     text ENCODE lzo,
        ordering_market_type    text ENCODE lzo,
        ordering_specialty      text ENCODE lzo
        );
