DROP TABLE IF EXISTS pdx_rx_txn_alltime_dw;
CREATE EXTERNAL TABLE pdx_rx_txn_alltime_dw (
    pharmacy_ncpdp_number                                               STRING,
    supplier_defined_store_number                                       STRING,
    mail_service_number                                                 STRING,
    pharmacy_zip_code                                                   STRING,
    prescription_number_filler                                          STRING,
    date_written                                                        STRING,
    date_filled                                                         STRING,
    date_delivered_fulfilled                                            STRING,
    new_refill_counter                                                  STRING,
    dispensed_ndc_number                                                STRING,
    dispensed_drug_name                                                 STRING,
    prescribed_ndc_number                                               STRING,
    prescribed_drug_name                                                STRING,
    partial_fill_status                                                 STRING,
    quantity_dispensed                                                  STRING,
    days_supply                                                         STRING,
    ingredient_cost                                                     STRING,
    ingredient_cost_paid                                                STRING,
    dispensing_fee                                                      STRING,
    dispensing_fee_paid                                                 STRING,
    copay_coinsurance_amount                                            STRING,
    total_amount_paid_by_patient                                        STRING,
    reimbursed_amount                                                   STRING,
    basis_of_ingredient_cost_submitted                                  STRING,
    basis_of_ingredient_cost_reimbursed                                 STRING,
    total_transaction_price_collected                                   STRING,
    payment_type                                                        STRING,
    indicator_for_coupon_type                                           STRING,
    coupon_face_value                                                   STRING,
    coupon_id                                                           STRING,
    indicator_for_vouchers_free_goods_discounts_or_indigent_programs    STRING,
    plan_code                                                           STRING,
    indicator_for_discount_cash_card_program                            STRING,
    group_number                                                        STRING,
    bank_identification_number                                          STRING,
    number_of_refills_authorized                                        STRING,
    refills_remaining                                                   STRING,
    dispensed_as_written                                                STRING,
    prescriber_last_name                                                STRING,
    prescriber_first_name                                               STRING,
    prescriber_middle_initial                                           STRING,
    prescriber_dea_number                                               STRING,
    state_license_number_for_prescriber                                 STRING,
    state_of_assigned_number_for_prescriber                             STRING,
    prescriber_npi                                                      STRING,
    prescriber_city                                                     STRING,
    prescriber_state                                                    STRING,
    prescriber_zip_code                                                 STRING,
    prescriber_phone_number                                             STRING,
    pharmacy_npi                                                        STRING,
    patient_birth_year                                                  STRING,
    coordination_of_benefits_counter                                    STRING,
    patient_gender_code                                                 STRING,
    patient_zip_code                                                    STRING,
    patient_location_code                                               STRING,
    deidentified_patient_code                                           STRING,
    origin_of_rx                                                        STRING,
    indicator_for_e_prescribed_transaction                              STRING,
    level_of_service                                                    STRING,
    central_fill_flag                                                   STRING,
    claim_indicator                                                     STRING,
    processor_control_number                                            STRING,
    compound_code                                                       STRING,
    chain_code                                                          STRING,
    diagnosis_code                                                      STRING,
    injectable_units_dispensed                                          STRING,
    hin_number                                                          STRING,
    medicare_part_d_flag                                                STRING,
    refill_change_flag                                                  STRING,
    unit_of_measure                                                     STRING,
    medical_benefit_claim_indicator                                     STRING,
    filler                                                              STRING,
    prescriber_id_qualifier                                             STRING,
    person_code                                                         STRING,
    patient_relationship_code                                           STRING,
    ncpdp_patient_id_qualifier                                          STRING,
    cardholder_id                                                       STRING,
    ncpdp_patient_id                                                    STRING,
    patient_last_name                                                   STRING,
    patient_first_name                                                  STRING,
    patient_street_address                                              STRING,
    patient_zip                                                         STRING,
    patient_date_of_birth                                               STRING,
    hvjoinkey                                                           STRING
    )
    PARTITIONED BY (part_processdate STRING)
    ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.RegexSerDe'
    WITH SERDEPROPERTIES (
        'serialization.format' = '1',
        'input.regex' = '^(.{7})(.{7})(.{4})(.{9})(.{15})(.{8})(.{8})(.{8})(.{2})(.{11})(.{28})(.{11})(.{28})(.{1})(.{7}.{3})(.{3})(.{6}.{2})(.{6}.{2})(.{6}.{2})(.{6}.{2})(.{6}.{2})(.{6}.{2})(.{6}.{2})(.{1})(.{1})(.{6}.{2})(.{1})(.{2})(.{6}.{2})(.{15})(.{2})(.{9})(.{2})(.{15})(.{6})(.{2})(.{2})(.{1})(.{15})(.{10})(.{1})(.{9})(.{15})(.{2})(.{10})(.{15})(.{2})(.{5})(.{10})(.{10})(.{4})(.{2})(.{1})(.{5})(.{2})(.{40})(.{1})(.{1})(.{1})(.{1})(.{1})(.{10})(.{1})(.{2})(.{10})(.{8})(.{9})(.{1})(.{1})(.{2})(.{1})(.{6})(.{2})(.{3})(.{1})(.{2})(.{20})(.{20})(.{15})(.{12})(.{30})(.{5})(.{10})(.{36}).*'
    )
    STORED AS
    INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
    OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
    LOCATION 's3://salusv/incoming/pharmacyclaims/pdx/'
    ;