SELECT
    txn.data_set_nm                  ,
    txn.src_era_claim_id             ,
    txn.src_claim_id                 ,
    txn.claim_type_cd                ,
    txn.edi_interchange_creation_dt  ,
    txn.edi_interchange_creation_time,
    txn.txn_handling_cd              ,
    txn.tot_actual_provdr_paymt_amt  ,
    txn.credit_debit_fl_cd           ,
    txn.paymt_method_cd              ,
    txn.paymt_eff_dt                 ,
    txn.payer_claim_cntl_nbr         ,
    txn.payer_claim_cntl_nbr_origl   ,
    txn.payer_nm                     ,
    txn.payer_cms_plan_id            ,
    txn.payer_id                     ,
    txn.payer_naic_id                ,
    txn.payer_group_nbr              ,
    txn.payer_claim_flng_ind_cd      ,
    txn.payee_tax_id                 ,
    txn.payee_npi                    ,
    txn.payee_nm                     , 
    txn.payee_addr_1                 ,
    txn.payee_addr_2                 ,
    txn.payee_addr_city              ,
    txn.payee_addr_state             ,
    txn.payee_addr_zip               ,
    txn.rendr_provdr_npi             , 
    txn.rendr_provdr_upin            ,
    txn.rendr_provdr_comm_nbr        ,
    txn.rendr_provdr_loc_nbr         ,
    txn.rendr_provdr_stlc_nbr        ,
    txn.rendr_provdr_last_nm         ,
    txn.rendr_provdr_first_nm        ,
    txn.claim_sts_cd                 ,
    txn.tot_claim_charg_amt          ,
    txn.tot_paid_amt                 ,
    txn.patnt_rspbty_amt             ,
    txn.fclty_type_pos_cd            ,
    txn.claim_freq_cd                ,
    txn.stmnt_from_dt                ,
    txn.stmnt_to_dt                  ,
    txn.covrg_expired_dt             ,
    txn.claim_received_dt            ,
    txn.drg_cd                       ,
    txn.drg_amt                      ,
    txn.clm_cas                      ,
    txn.src_era_svc_id               ,
    txn.src_svc_id                   ,
    txn.line_item_cntl_nbr           ,
    txn.svc_rendr_provdr_npi         ,
    txn.svc_rendr_provdr_upin        ,
    txn.svc_rendr_provdr_comm_nbr    ,
    txn.svc_rendr_provdr_loc_nbr     ,
    txn.svc_rendr_provdr_stlc_nbr    ,
    txn.adjtd_proc_cd_qual           ,
    txn.adjtd_proc_cd                ,
    txn.adjtd_proc_modfr_1           ,
    txn.adjtd_proc_modfr_2           ,
    txn.adjtd_proc_modfr_3           ,
    txn.adjtd_proc_modfr_4           ,
    txn.line_item_charg_amt          ,
    txn.line_item_allowed_amt        ,
    txn.line_item_paid_amt           ,
    txn.revnu_cd                     ,
    txn.paid_units                   ,
    txn.submd_proc_cd_qual           ,
    txn.submd_proc_cd                ,
    txn.submd_proc_modfr_1           ,
    txn.submd_proc_modfr_2           ,
    txn.submd_proc_modfr_3           ,
    txn.submd_proc_modfr_4           ,
    txn.origl_units_of_svc_cnt       ,
    txn.svc_from_dt                  ,
    txn.svc_to_dt                    ,
    --------------------------------------------------------------------------------------------------------------------------------        
    -------------------- claim adjustment section
    --------------------------------------------------------------------------------------------------------------------------------        
    priority+1                                                                                                             AS svc_ln_adjmt_seq_num,
    SUBSTR(TRIM(txn.value), 1                          , LOCATE(':', TRIM(txn.value))-1                          )         AS svc_ln_adjmt_grp_cd,
    SUBSTR(TRIM(txn.value), LOCATE(':', TRIM(txn.value))+1, LOCATE('=', TRIM(txn.value))-1 - LOCATE(':', TRIM(txn.value))) AS svc_ln_adjmt_rsn_cd,
    CAST(SUBSTR(TRIM(txn.value), LOCATE('>', TRIM(txn.value))+1                                                  )  AS FLOAT)      AS svc_ln_adjmt_amt,
    --------------------------------------------------------------------------------------------------------------------------------            
    txn.pos_cd                        ,
    txn.instnl_typ_of_bll_cd
    --------------------------------------------------------------------------------------------------------------------------------            
FROM practice_insight_PRE_serviceline_pos_tob_cas txn
