SELECT
    txn.pt_zip_address,
    txn.patient_gender_code,
    txn.pt_state_address,
    txn.pcn,
    txn.switch_transaction_number,
    txn.date_of_fill,
    txn.date_rx_written,
    txn.date_of_injury,
    txn.date_switched,
    txn.type_column,
    txn.transaction_response_status,
    txn.reject_codes,
    txn.reject_codes_2,
    txn.reject_codes_3,
    txn.reject_codes_4,
    txn.reject_codes_5,
    txn.diagnosis_code,
    txn.diagnosis_code_qualifier,
    txn.product_service_id,
    txn.product_service_qualifier,
    txn.bin,
    txn.fill_number,
    txn.number_of_refills_authorized,
    txn.quantity_dispensed,
    txn.unit_of_measure,
    txn.days_supply,
    txn.service_number,
    txn.plan,
    txn.compound_code,
    txn.unit_dose_indicator,
    txn.daw_code,
    txn.rx_origin_code,
    txn.submission_clarification_code,
    txn.orig_prescribed_prod_svc_code,
    txn.orig_prescribed_prod_svc_qualifier,
    txn.original_prescribed_quantity,
    txn.level_of_service,
    txn.reason_for_service_code,
    txn.professional_service_code,
    txn.result_of_service_code,
    txn.prescriber_id,
    txn.prescriber_last_name,
    txn.prescriber_first_name,
    txn.prescriber_street_address,
    txn.prescriber_city_address,
    txn.prescriber_state_address,
    txn.prescriber_zip_address,
    txn.primary_care_provider_id,
    txn.cob_other_payment_count,
    txn.other_payer_amount_recognized_raw,
    txn.amount_applied_to_periodic_deductible,
    txn.amount_exceeding_periodic_benefit_maximum,
    txn.accumulated_deductible_paid,
    txn.remaining_deductible_amount,
    txn.remaining_benefit_amount,
    txn.amount_of_copay_coinsurance,
    txn.basis_cost_determination,
    txn.ingredient_cost,
    txn.dispensing_fee,
    txn.incentive_amount,
    txn.gross_amount_due,
    txn.professional_service_fee,
    txn.pt_paid_amount,
    txn.other_amount_claimed_qualifier,
    txn.other_amount_claimed_submitted,
    txn.basis_of_reimbursement_determination,
    txn.ingredient_cost_paid,
    txn.dispensing_fee_paid,
    txn.incentive_amount_paid,
    txn.total_amount_paid,
    txn.professional_service_fee_paid_raw,
    txn.patient_pay_amount,
    txn.other_amount_paid_qualifier,
    txn.other_amount_paid,
    txn.tax_exempt_indicator,
    txn.coupon_type,
    txn.coupon_number,
    txn.coupon_value_amount,
    txn.other_payer_coverage_type,
    txn.other_payer_id,
    txn.other_payer_id_qualifier,
    txn.other_payer_date,
    txn.other_coverage_code,
    txn.plan_description,
    txn.place_of_service_code,
    /* JKS 12/19/19 -  txn.prescriber_id_duplicate was added */    
    txn.prescriber_id_duplicate,
    pay.hvid,
    pay.threedigitzip,
    pay.yearofbirth,
    pay.gender,
    pay.age,
    pay.state,
    pay.RXNumber as rx_number,
    pay.privateIdOne as pharmacy_npi,
    MAX(txn.hvjoinkey)                                                                      AS hvjoinkey,
    MAX(txn.input_file_name)                                                                AS input_file_name
FROM txn
LEFT OUTER JOIN matching_payload pay ON txn.hvjoinkey = pay.hvjoinkey
WHERE UPPER(COALESCE(txn.patient_gender_code, 'X')) <>  UPPER('patient_gender_code')
GROUP BY 1,	2,	3,	4,	5,	6,	7,	8,	9,	10,
        11,	12,	13,	14,	15,	16,	17,	18,	19,	20,
        21,	22,	23,	24,	25,	26,	27,	28,	29,	30,
        31,	32,	33,	34,	35,	36,	37,	38,	39,	40,
        41,	42,	43,	44,	45,	46,	47,	48,	49,	50,
        51,	52,	53,	54,	55,	56,	57,	58,	59,	60,
        61,	62,	63,	64,	65,	66,	67,	68,	69,	70,
        71,	72,	73,	74,	75,	76,	77,	78,	79,	80,
        81,	82,	83,	84,	85,	86,	87,	88,	89,	90, 
        91, 92, 93,94
