SELECT
    NULL                  AS row_id,
    CONCAT('54_', ts.pk)  AS hv_proc_id,
    NULL                  AS crt_dt,
    NULL                  AS mdl_vrsn_num,
    ts.source_file_name   AS data_set_nm,
    NULL                  AS src_vrsn_id,
    NULL                  AS hvm_vdr_id,
    NULL                  AS hvm_vdr_feed_id,
    NULL                  AS vdr_org_id,
    ts.pk                 AS vdr_proc_id,
    CASE
      WHEN ts.pk IS NOT NULL
      THEN 'VENDOR'
    END                   AS vdr_proc_id_qual,
    mp.hvid               AS hvid,
    mp.yearOfBirth        AS ptnt_birth_yr,
    ce.ageAtDiagnosis     AS ptnt_age_num,
    NULL                  AS ptnt_lvg_flg,
    NULL                  AS ptnt_dth_dt,
    mp.gender             AS ptnt_gender_cd,
    mp.state              AS ptnt_state_cd,
    mp.threeDigitZip      AS ptnt_zip3_cd,
    NULL                  AS hv_enc_id,
    NULL                  AS enc_dt,
    NULL                  AS proc_dt,
    NULL                  AS proc_rndrg_fclty_npi,
    NULL                  AS proc_rndrg_fclty_vdr_id,
    NULL                  AS proc_rndrg_fclty_vdr_id_qual,
    NULL                  AS proc_rndrg_fclty_alt_id,
    NULL                  AS proc_rndrg_fclty_alt_id_qual,
    NULL                  AS proc_rndrg_fclty_tax_id,
    NULL                  AS proc_rndrg_fclty_dea_id,
    NULL                  AS proc_rndrg_fclty_state_lic_id,
    NULL                  AS proc_rndrg_fclty_comrcl_id,
    NULL                  AS proc_rndrg_fclty_nucc_taxnmy_cd,
    NULL                  AS proc_rndrg_fclty_alt_taxnmy_id,
    NULL                  AS proc_rndrg_fclty_alt_taxnmy_id_qual,
    NULL                  AS proc_rndrg_fclty_mdcr_speclty_cd,
    NULL                  AS proc_rndrg_fclty_alt_speclty_id,
    NULL                  AS proc_rndrg_fclty_alt_speclty_id_qual,
    NULL                  AS proc_rndrg_fclty_nm,
    NULL                  AS proc_rndrg_fclty_addr_1_txt,
    NULL                  AS proc_rndrg_fclty_addr_2_txt,
    NULL                  AS proc_rndrg_fclty_state_cd,
    NULL                  AS proc_rndrg_fclty_zip_cd,
    NULL                  AS proc_rndrg_prov_npi,
    NULL                  AS proc_rndrg_prov_vdr_id,
    NULL                  AS proc_rndrg_prov_vdr_id_qual,
    NULL                  AS proc_rndrg_prov_alt_id,
    NULL                  AS proc_rndrg_prov_alt_id_qual,
    NULL                  AS proc_rndrg_prov_tax_id,
    NULL                  AS proc_rndrg_prov_dea_id,
    NULL                  AS proc_rndrg_prov_state_lic_id,
    NULL                  AS proc_rndrg_prov_comrcl_id,
    NULL                  AS proc_rndrg_prov_upin,
    NULL                  AS proc_rndrg_prov_ssn,
    NULL                  AS proc_rndrg_prov_nucc_taxnmy_cd,
    NULL                  AS proc_rndrg_prov_alt_taxnmy_id,
    NULL                  AS proc_rndrg_prov_alt_taxnmy_id_qual,
    NULL                  AS proc_rndrg_prov_mdcr_speclty_cd,
    NULL                  AS proc_rndrg_prov_alt_speclty_id,
    NULL                  AS proc_rndrg_prov_alt_speclty_id_qual,
    NULL                  AS proc_rndrg_prov_frst_nm,
    NULL                  AS proc_rndrg_prov_last_nm,
    NULL                  AS proc_rndrg_prov_addr_1_txt,
    NULL                  AS proc_rndrg_prov_addr_2_txt,
    NULL                  AS proc_rndrg_prov_state_cd,
    NULL                  AS proc_rndrg_prov_zip_cd,
    ts.treatmentmodality  AS proc_cd,
    CASE
      WHEN ts.treatmentmodality IS NOT NULL
      THEN 'VENDOR'
    END                   AS proc_cd_qual,
    NULL                  AS proc_cd_1_modfr,
    NULL                  AS proc_cd_2_modfr,
    NULL                  AS proc_cd_3_modfr,
    NULL                  AS proc_cd_4_modfr,
    NULL                  AS proc_cd_modfr_qual,
    NULL                  AS proc_snomed_cd,
    NULL                  AS proc_prty_cd,
    NULL                  AS proc_prty_cd_qual,
    NULL                  AS proc_alt_cd,
    NULL                  AS proc_alt_cd_qual,
    NULL                  AS proc_pos_cd,
    NULL                  AS proc_unit_qty,
    NULL                  AS proc_uom,
    parse_out_transmed_diagnosis(
        ce.primarysite
        )                 AS proc_diag_cd,
    NULL                  AS proc_diag_cd_qual,
    NULL                  AS data_captr_dt,
    NULL                  AS rec_stat_cd,
    'treatmentsite'       AS prmy_src_tbl_nm,
    {date_input}          AS date_input,
    SUBSTRING(
        {date_input}, 0, 7
        )                 AS part_mth
FROM transactions_treatmentsite ts
    LEFT JOIN transactions_cancerepisode ce ON ts.cancerepisodefk = ce.pk
    LEFT JOIN matching_payload mp ON ts.patientfk = mp.claimid
WHERE ts.treatmentmodality IS NOT NULL
