SELECT
    NULL                  AS row_id,
    CONCAT('54_', ce.pk)  AS hv_clin_obsn_id,
    NULL                  AS crt_dt,
    NULL                  AS mdl_vrsn_num,
    ce.source_file_name   AS data_set_nm,
    NULL                  AS src_vrsn_id,
    NULL                  AS hvm_vdr_id,
    NULL                  AS hvm_vdr_feed_id,
    NULL                  AS vdr_org_id,
    ce.pk                 AS vdr_clin_obsn_id,
    'VENDOR'              AS vdr_clin_obsn_id_qual,
    mp.hvid               AS hvid,
    mp.yearOfBirth        AS ptnt_birth_yr,
    ce.ageAtDiagnosis     AS ptnt_age_num,
    NULL                  AS ptnt_lvg_flg,
    NULL                  AS ptnt_dth_dt,
    mp.gender             AS ptnt_gender_cd,
    mp.state              AS ptnt_state_cd,
    mp.threeDigitZip      AS ptnt_zip3_cd,
    NULL                  AS hv_enc_id,
    NULL                  AS enc_dt,
    NULL                  AS clin_obsn_dt,
    NULL                  AS clin_obsn_rndrg_fclty_npi,
    NULL                  AS clin_obsn_rndrg_fclty_vdr_id,
    NULL                  AS clin_obsn_rndrg_fclty_vdr_id_qual,
    NULL                  AS clin_obsn_rndrg_fclty_alt_id,
    NULL                  AS clin_obsn_rndrg_fclty_alt_id_qual,
    NULL                  AS clin_obsn_rndrg_fclty_tax_id,
    NULL                  AS clin_obsn_rndrg_fclty_dea_id,
    NULL                  AS clin_obsn_rndrg_fclty_state_lic_id,
    NULL                  AS clin_obsn_rndrg_fclty_comrcl_id,
    NULL                  AS clin_obsn_rndrg_fclty_nucc_taxnmy_cd,
    NULL                  AS clin_obsn_rndrg_fclty_alt_taxnmy_id,
    NULL                  AS clin_obsn_rndrg_fclty_alt_taxnmy_id_qual,
    NULL                  AS clin_obsn_rndrg_fclty_mdcr_speclty_cd,
    NULL                  AS clin_obsn_rndrg_fclty_alt_speclty_id,
    NULL                  AS clin_obsn_rndrg_fclty_alt_speclty_id_qual,
    NULL                  AS clin_obsn_rndrg_fclty_nm,
    NULL                  AS clin_obsn_rndrg_fclty_addr_1_txt,
    NULL                  AS clin_obsn_rndrg_fclty_addr_2_txt,
    NULL                  AS clin_obsn_rndrg_fclty_state_cd,
    NULL                  AS clin_obsn_rndrg_fclty_zip_cd,
    NULL                  AS clin_obsn_rndrg_prov_npi,
    NULL                  AS clin_obsn_rndrg_prov_vdr_id,
    NULL                  AS clin_obsn_rndrg_prov_vdr_id_qual,
    NULL                  AS clin_obsn_rndrg_prov_alt_id,
    NULL                  AS clin_obsn_rndrg_prov_alt_id_qual,
    NULL                  AS clin_obsn_rndrg_prov_tax_id,
    NULL                  AS clin_obsn_rndrg_prov_dea_id,
    NULL                  AS clin_obsn_rndrg_prov_state_lic_id,
    NULL                  AS clin_obsn_rndrg_prov_comrcl_id,
    NULL                  AS clin_obsn_rndrg_prov_upin,
    NULL                  AS clin_obsn_rndrg_prov_ssn,
    NULL                  AS clin_obsn_rndrg_prov_nucc_taxnmy_cd,
    NULL                  AS clin_obsn_rndrg_prov_alt_taxnmy_id,
    NULL                  AS clin_obsn_rndrg_prov_alt_taxnmy_id_qual,
    NULL                  AS clin_obsn_rndrg_prov_mdcr_speclty_cd,
    NULL                  AS clin_obsn_rndrg_prov_alt_speclty_id,
    NULL                  AS clin_obsn_rndrg_prov_alt_speclty_id_qual,
    NULL                  AS clin_obsn_rndrg_prov_frst_nm,
    NULL                  AS clin_obsn_rndrg_prov_last_nm,
    NULL                  AS clin_obsn_rndrg_prov_addr_1_txt,
    NULL                  AS clin_obsn_rndrg_prov_addr_2_txt,
    NULL                  AS clin_obsn_rndrg_prov_state_cd,
    NULL                  AS clin_obsn_rndrg_prov_zip_cd,
    NULL                  AS clin_obsn_onset_dt,
    NULL                  AS clin_obsn_resltn_dt,
    NULL                  AS clin_obsn_data_src_cd,
    NULL                  AS clin_obsn_data_src_cd_qual,
    NULL                  AS clin_obsn_data_src_nm,
    NULL                  AS clin_obsn_data_src_desc,
    NULL                  AS clin_obsn_data_ctgy_cd,
    NULL                  AS clin_obsn_data_ctgy_cd_qual,
    NULL                  AS clin_obsn_data_ctgy_nm,
    NULL                  AS clin_obsn_data_ctgy_desc,
    NULL                  AS clin_obsn_typ_cd,
    NULL                  AS clin_obsn_typ_cd_qual,
    NULL                  AS clin_obsn_typ_nm,
    NULL                  AS clin_obsn_typ_desc,
    NULL                  AS clin_obsn_substc_cd,
    NULL                  AS clin_obsn_substc_cd_qual,
    NULL                  AS clin_obsn_substc_nm,
    NULL                  AS clin_obsn_substc_desc,
    NULL                  AS clin_obsn_cd,
    NULL                  AS clin_obsn_cd_qual,
    NULL                  AS clin_obsn_nm,
    NULL                  AS clin_obsn_desc,
    parse_out_transmed_diagnosis(
        ce.primarysite
        )                 AS clin_obsn_diag_cd,
    NULL                  AS clin_obsn_diag_cd_qual,
    NULL                  AS clin_obsn_diag_nm,
    NULL                  AS clin_obsn_diag_desc,
    NULL                  AS clin_obsn_snomed_cd,
    ARRAY(
        ce.tumorgrade, ce.stage, ce.histology
        )[exploder.n]     AS clin_obsn_result_cd,
    CASE
      WHEN exploder.n = 0 THEN 'CANCER_STAGE_T'
      WHEN exploder.n = 1 THEN 'CANCER_STAGE'
      WHEN exploder.n = 2 THEN 'CANCER_STAGE_PATHOLOGY'
    END                   AS clin_obsn_result_cd_qual,
    NULL                  AS clin_obsn_result_nm,
    NULL                  AS clin_obsn_result_desc,
    NULL                  AS clin_obsn_msrmt,
    NULL                  AS clin_obsn_uom,
    NULL                  AS clin_obsn_qual,
    NULL                  AS clin_obsn_abnorm_flg,
    NULL                  AS clin_obsn_norm_min_msrmt,
    NULL                  AS clin_obsn_norm_max_msrmt,
    NULL                  AS data_captr_dt,
    NULL                  AS rec_stat_cd,
    'cancerepisode'       AS prmy_src_tbl_nm,
    {date_input}          AS date_input,
    SUBSTRING(
        {date_input}, 0, 7
        )                 AS part_mth
FROM transactions_cancerepisode ce
    LEFT JOIN matching_payload mp ON ce.patientfk = mp.claimid
    CROSS JOIN result_cd_exploder exploder
WHERE ARRAY(ce.tumorgrade, ce.stage, ce.histology)[exploder.n] IS NOT NULL
