INSERT INTO pharmacyclaims_common_model
SELECT
    NULL,                       --record_id
    SKUtilizationKey,           --claim_id
    NULL,                       --hvid
    NULL,                       --created
    NULL,                       --model_version
    NULL,                       --data_set
    NULL,                       --data_feed
    NULL,                       --data_vendor
    NULL,                       --source_version
    NULL,                       --patient_gender
    NULL,                       --patient_age
    NULL,                       --patient_year_of_birth
    NULL,                       --patient_zip3
    NULL,                       --patient_state
    DispenseDttm,               --date_service
    EffectiveStartDate,         --date_written
    NULL,                       --date_of_injury
    NULL,                       --year_of_injury
    NULL,                       --date_authorized
    NULL,                       --time_authorized
    NULL,                       --transaction_code_std
    NULL,                       --transaction_code_vendor
    NULL,                       --response_code_std
    NULL,                       --response_code_vendor
    NULL,                       --reject_reason_code_1
    NULL,                       --reject_reason_code_2
    NULL,                       --reject_reason_code_3
    NULL,                       --reject_reason_code_4
    NULL,                       --reject_reason_code_5
    DrgCode,                    --diagnosis_code
    '99',                       --diagnosis_code_qual
    NULL,                       --procedure_code
    NULL,                       --procedure_code_qual
    NDC,                        --ndc_code
    HDC,                        --product_service_id
    '99',                       --product_service_id_qual
    NULL,                       --rx_number
    NULL,                       --rx_number_qual
    NULL,                       --bin_number
    NULL,                       --processor_control_number
    NULL,                       --fill_number
    NULL,                       --refill_auth_amount
    QTY,                        --dispensed_quantity
    UOMQTY,                     --unit_of_measure
    NULL,                       --days_supply
    NULL,                       --pharmacy_npi
    NULL,                       --prov_dispensing_npi
    NULL,                       --payer_id
    NULL,                       --payer_id_qual
    NULL,                       --payer_name
    NULL,                       --payer_parent_name
    NULL,                       --payer_org_name
    NULL,                       --payer_plan_id
    NULL,                       --payer_plan_name
    NULL,                       --payer_type
    NULL,                       --compound_code
    NULL,                       --unit_dose_indicator
    NULL,                       --dispensed_as_written
    NULL,                       --prescription_origin
    NULL,                       --submission_clarification
    NULL,                       --orig_prescribed_product_service_code
    NULL,                       --orig_prescribed_product_service_code_qual
    NULL,                       --orig_prescribed_quantity
    NULL,                       --prior_auth_type_code
    NULL,                       --level_of_service
    NULL,                       --reason_for_service
    NULL,                       --professional_service_code
    NULL,                       --result_of_service_code
    NULL,                       --prov_prescribing_npi
    NULL,                       --prov_primary_care_npi
    NULL,                       --cob_count
    NULL,                       --usual_and_customary_charge
    NULL,                       --product_selection_attributed
    NULL,                       --other_payer_recognized
    NULL,                       --periodic_deductible_applied
    NULL,                       --periodic_benefit_exceed
    NULL,                       --accumulated_deductible
    NULL,                       --remaining_deductible
    NULL,                       --remaining_benefit
    NULL,                       --copay_coinsurance
    NULL,                       --basis_of_cost_determination
    ExtendedCost,               --submitted_ingredient_cost
    NULL,                       --submitted_dispensing_fee
    NULL,                       --submitted_incentive
    Revenue,                    --submitted_gross_due
    NULL,                       --submitted_professional_service_fee
    NULL,                       --submitted_patient_pay
    NULL,                       --submitted_other_claimed_qual
    NULL,                       --submitted_other_claimed
    NULL,                       --basis_of_reimbursement_determination
    NULL,                       --paid_ingredient_cost
    NULL,                       --paid_dispensing_fee
    NULL,                       --paid_incentive
    NULL,                       --paid_gross_due
    NULL,                       --paid_professional_service_fee
    NULL,                       --paid_patient_pay
    NULL,                       --paid_other_claimed_qual
    NULL,                       --paid_other_claimed
    NULL,                       --tax_exempt_indicator
    NULL,                       --coupon_type
    NULL,                       --coupon_number
    NULL,                       --coupon_value
    SKClientTypeKey,            --pharmacy_other_id
    '99',                       --pharmacy_other_qual
    NULL,                       --pharmacy_postal_code
    NULL,                       --prov_dispensing_id
    NULL,                       --prov_dispensing_qual
    PrescribingPhysicianCode,   --prov_prescribing_id
    '99',                       --prov_prescribing_qual
    PhysicianCode,              --prov_primary_care_id
    '99',                       --prov_primary_care_qual
    NULL,                       --other_payer_coverage_type
    NULL,                       --other_payer_coverage_id
    NULL,                       --other_payer_coverage_qual
    NULL,                       --other_payer_date
    NULL,                       --other_payer_coverage_code
    NULL                        --logical_delete_reason
FROM cardinal_dcoa_transactions;

