SELECT
    t.record_id,
    t.claim_id,
    t.hvid,
    t.created,
    t.model_version,
    t.data_set,
    t.data_feed,
    t.data_vendor,
    CAST(NULL AS String) as source_version,
    t.patient_gender,
    t.patient_age,
    t.patient_year_of_birth,
    t.patient_zip3,
    t.patient_state,
    t.date_service,
    t.date_written,
    CAST(NULL AS String) as year_of_injury,
    t.date_authorized,
    t.time_authorized,
    CAST(NULL AS DATE) AS discharge_date,
    CAST(NULL AS STRING) AS transaction_code_std,
    t.transaction_code_vendor,
    t.response_code_std,
    CAST(NULL AS STRING) AS response_code_vendor,
    t.reject_reason_code_1,
    t.reject_reason_code_2,
    t.reject_reason_code_3,
    t.reject_reason_code_4,
    t.reject_reason_code_5,
    t.diagnosis_code,
    CAST(NULL AS STRING) AS diagnosis_code_qual,
    t.procedure_code,
    t.procedure_code_qual,
    t.ndc_code,
    t.product_service_id,
    t.product_service_id_qual,
    CASE WHEN t.level_of_service ='6' THEN NULL ELSE t.rx_number END AS rx_number,
    t.rx_number_qual,
    t.bin_number,
    t.processor_control_number,
    t.fill_number,
    t.refill_auth_amount,
    t.dispensed_quantity,
    t.unit_of_measure,
    t.days_supply,
    CASE WHEN t.level_of_service ='6' THEN NULL ELSE t.pharmacy_npi END AS pharmacy_npi,
    CASE WHEN t.level_of_service ='6' THEN NULL ELSE t.prov_dispensing_npi END AS prov_dispensing_npi,
    t.payer_id,
    t.payer_id_qual,
    t.payer_name,
    CAST(NULL AS STRING) AS payer_parent_name,
    t.payer_org_name,
    t.payer_plan_id,
    t.payer_plan_name,
    t.payer_type,
    t.compound_code,
    t.unit_dose_indicator,
    t.dispensed_as_written,
    t.prescription_origin,
    t.submission_clarification,
    t.orig_prescribed_product_service_code,
    t.orig_prescribed_product_service_code_qual,
    t.orig_prescribed_quantity,
    t.prior_auth_type_code,
    t.level_of_service,
    t.reason_for_service,
    t.professional_service_code,
    t.result_of_service_code,
    CASE WHEN t.level_of_service ='6' THEN NULL ELSE t.prov_prescribing_npi END AS prov_prescribing_npi,
    CAST(NULL AS STRING) AS prov_prescribing_tax_id,
    CAST(NULL AS STRING) AS prov_prescribing_dea_id,
    CAST(NULL AS STRING) AS prov_prescribing_ssn,
    CAST(NULL AS STRING) AS prov_prescribing_state_license,
    CAST(NULL AS STRING) AS prov_prescribing_upin,
    CAST(NULL AS STRING) AS prov_prescribing_commercial_id,
    CAST(NULL AS STRING) AS prov_prescribing_name_1,
    CAST(NULL AS STRING) AS prov_prescribing_name_2,
    CAST(NULL AS STRING) AS prov_prescribing_address_1,
    CAST(NULL AS STRING) AS prov_prescribing_address_2,
    CAST(NULL AS STRING) AS prov_prescribing_city,
    CAST(NULL AS STRING) AS prov_prescribing_state,
    CAST(NULL AS STRING) AS prov_prescribing_zip,
    CAST(NULL AS STRING) AS prov_prescribing_std_taxonomy,
    CAST(NULL AS STRING) AS prov_prescribing_vendor_specialty,
    CASE WHEN t.level_of_service ='6' THEN NULL ELSE t.prov_primary_care_npi END AS prov_primary_care_npi,
    t.cob_count,
    t.usual_and_customary_charge,
    t.product_selection_attributed,
    t.other_payer_recognized,
    t.periodic_deductible_applied,
    t.periodic_benefit_exceed,
    t.accumulated_deductible,
    t.remaining_deductible,
    t.remaining_benefit,
    t.copay_coinsurance,
    t.basis_of_cost_determination,
    t.submitted_ingredient_cost,
    t.submitted_dispensing_fee,
    t.submitted_incentive,
    t.submitted_gross_due,
    t.submitted_professional_service_fee,
    t.submitted_patient_pay,
    t.submitted_other_claimed_qual,
    CAST(NULL AS FLOAT) AS submitted_other_claimed,
    t.basis_of_reimbursement_determination,
    t.paid_ingredient_cost,
    t.paid_dispensing_fee,
    t.paid_incentive,
    t.paid_gross_due,
    t.paid_professional_service_fee,
    t.paid_patient_pay,
    t.paid_other_claimed_qual,
    t.paid_other_claimed,
    t.tax_exempt_indicator,
    t.coupon_type,
    t.coupon_number,
    t.coupon_value,
    t.pharmacy_other_id,
    t.pharmacy_other_qual,
    t.pharmacy_postal_code,
    t.prov_dispensing_id,
    t.prov_dispensing_qual,
    CAST(NULL AS STRING) AS prov_prescribing_id,
    CAST(NULL AS STRING) AS prov_prescribing_qual,
    t.prov_primary_care_id,
    t.prov_primary_care_qual,
    t.other_payer_coverage_type,
    t.other_payer_coverage_id,
    t.other_payer_coverage_qual,
    t.other_payer_date,
    t.other_payer_coverage_code,
    t.logical_delete_reason,
    t.part_provider,
    t.part_best_date
FROM mckesson_res_norm_cf t
